Created test for Adapter names
smartcontractkit/external-adapters-js pull request #1056
Opened 2021-11-01 19:46 UTC by silaslenihan

## Closes #ISSUE_NUMBER_GOES_HERE

## Description
Adds a simple test that ensures the source names are formatted properly

## Changes
Adds a test to `packages/core/legos` that tests the names of adapters.

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

2021-11-02 01:32 UTC, austinborn reviewed
Thank you for contributing! Would you mind moving this to `.../legos/test/unit/legos.test.ts`?

2021-11-02 01:43 UTC, silaslenihan commented on packages/core/legos/test/legos.test.ts
> +      expect(source.includes('-')).toBe(false)
@bryanjowers and @justinkaseman perhaps can give more insight as I have just rejoined the team and don't have access to clubhouse yet, but there is a clubhouse card called "EA Legos unit test for names" which says that every adapter name should be tested for correct formatting (ie: no dashes), which is the purpose of this PR. Not entirely sure whether there are other criteria in determining a correctly formatted EA name, but I am waiting on a response from Justin on that one.

2021-11-02 14:02 UTC, austinborn commented on packages/core/legos/test/legos.test.ts
> +      expect(source.includes('-')).toBe(false)
Got it, I can link this to that ticket and add the ticket #.

2021-11-02 14:02 UTC, austinborn approved these changes

2021-11-02 14:03 UTC, austinborn requested changes
Can you also make sure the unit tests pass before merging?

2021-11-02 14:08 UTC, silaslenihan commented on packages/core/legos/test/legos.test.ts
> +      expect(source.includes('-')).toBe(false)
Thanks!

2021-11-05 18:21 UTC, justinkaseman approved these changes
LGTM.

The changes we talked about will go into another PR and ticket.

2021-11-17 11:59 UTC, boxhock commented
@austinborn Mind re-approving and merging this PR?

2021-11-17 14:22 UTC, austinborn approved these changes

2021-11-17 14:22 UTC, merged