Coinmarketcap historical endpoint
smartcontractkit/external-adapters-js pull request #1075
Opened 2021-11-05 15:29 UTC by bogos

## Closes ##1052

## Description

......

## Changes

- Add coinmarketcap historical endpoint

## Steps to Test

1. yarn test coinmarketcap

## Quality Assurance

- [X ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [ X] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

2021-11-05 16:33 UTC, austinborn requested changes

2021-11-05 16:33 UTC, austinborn commented on packages/sources/coinmarketcap/src/endpoint/historical.ts
> +  const skip_invalid = validator.validated.data.skipInvalid || true
Will this... work as intended? Assuming `validator.validated.data.skipInvalid` is a boolean or undefined, `validator.validated.data.skipInvalid === false` will return `true` for `skip_invalid`. Alternative would be `?? true`, which returns `true` when the lefthand side is `null` or `undefined`.

2021-11-10 01:15 UTC, austinborn submitted a review, later dismissed

2021-11-17 12:04 UTC, boxhock requested changes
Just one minor issue, otherwise looks good

2021-11-17 12:04 UTC, boxhock commented on packages/sources/coinmarketcap/README.md
> +https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/historical33333
I'm guessing these 3's are not supposed to be here? :sweat_smile: 

```suggestion
https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/historical
```

2021-11-19 10:22 UTC, boxhock requested changes
Just noticed this, should be good to merge after the README is updated

2021-11-19 10:22 UTC, boxhock commented on packages/sources/coinmarketcap/README.md
> +|           |   `quote`, `to`, `market`, `convert`    |                    The symbol of the currency to convert to                     |
It seems like this input param is not defaulting to "USD", and should be required

2021-11-19 15:16 UTC, boxhock commented on packages/sources/coinmarketcap/README.md
> +|           |   `quote`, `to`, `market`, `convert`    |                    The symbol of the currency to convert to                     |
Same goes for the above, should not be default "BTC"

2021-11-29 12:19 UTC, boxhock approved these changes

2021-11-29 12:19 UTC, merged