Reorganize root README and add CONTRIBUTING.md
smartcontractkit/external-adapters-js pull request #1194
Opened 2021-11-24 22:51 UTC by austinborn

## Closes 22412

## Description
 Reorganize `README.md` and add `CONTRIBUTING.md` for info on how to contribute to the repo.

## Changes

- Reorder sections
- Condense Advanced Features subsections
- Simplify table of contents
- Minor grammar and word fixes
- Change code block text types in some places
- Move certain sections to `CONTRIBUTE.md` with its own table of contents

## Steps to Test

(No tests required)

## Quality Assurance

- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

2021-11-29 11:32 UTC, boxhock requested changes
Looks good besides the broken link here! Thanks for doing this :grinning:

2021-11-29 11:32 UTC, boxhock commented on CONTRIBUTING.md
> +For example, take a look at the [synth-index] (./packages/composites/synth-index/test/integration/adapter.test.ts) test to see it in usage. When the `RECORD` environment variable is truthy, nock will
```suggestion
For example, take a look at the [synth-index](./packages/composites/synth-index/test/integration/adapter.test.ts) test to see it in usage. When the `RECORD` environment variable is truthy, nock will proxy HTTP requests and generate fixture data that can be used to contruct the integration test.
```

2021-11-29 11:32 UTC, boxhock commented on CONTRIBUTING.md
> +1. Setup nock to record HTTP requests, see the [synth-index] (./packages/composites/synth-index/test/integration/adapter.test.ts) test for a code sample.
```suggestion
1. Setup nock to record HTTP requests, see the [synth-index](./packages/composites/synth-index/test/integration/adapter.test.ts) test for a code sample.
```

2021-12-06 23:53 UTC, justinkaseman submitted a review, later dismissed
LGTM

2022-01-03 15:51 UTC, austinborn commented on CONTRIBUTING.md
> +6. [Soak Testing (Chainlink Team only)](<#Soak-Testing-(Chainlink-Team-only)>)
```suggestion
6. [Soak Testing (Chainlink Labs)](<#Soak-Testing-(Chainlink-Labs)>)
```

2022-01-03 15:51 UTC, austinborn commented on CONTRIBUTING.md
> +## Soak Testing (Chainlink Team only)
```suggestion
## Soak Testing (Chainlink Labs)
```

2022-01-03 15:55 UTC, boxhock approved these changes

2022-01-03 16:04 UTC, merged