finage crypto endpoint, WS support for crypto endpoint
smartcontractkit/external-adapters-js pull request #1277
Opened 2021-12-07 17:57 UTC by karen-stepanyan

## Closes #1269

## Changes

- Added new endpoint for crypto prices.
- Added WS support for crypto endpoint
- Added integration test for crypto endpoint

## Steps to Test

`yarn test packages/sources/finage/test
`
## Quality Assurance

- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

2021-12-07 18:37 UTC, cds95 requested changes
Looks good overall.  Left some minor comments.

2021-12-07 18:37 UTC, cds95 commented on packages/sources/finage/README.md
> +|    ✅     |        `API_KEY`         |                                                      |         |                                   |
Can we add `WS_SOCKET_KEY` to the ReadMe?

2021-12-07 18:37 UTC, cds95 commented on packages/sources/finage/schemas/env.json
> +      "type": "string",
Can we add `WS_SOCKET_KEY` here as well?

2021-12-07 18:48 UTC, austinborn reviewed
LGTM, pending addition of `WS_SOCKET_KEY` env var to readme

2021-12-07 19:21 UTC, cds95 commented on packages/sources/finage/README.md
> +|           |     `WS_SOCKET_KEY`      |                                                      |         |                                   |
Can you add a description for it as well?

2021-12-07 19:54 UTC, cds95 submitted a review, later dismissed

2021-12-09 16:36 UTC, austinborn approved these changes

2021-12-09 18:40 UTC, cds95 approved these changes

2021-12-09 18:40 UTC, merged