Release/v1.7.0
smartcontractkit/external-adapters-js pull request #1419
Opened 2022-01-11 00:12 UTC by justinkaseman

External Adapters v1.7.0

## Changelog Notes

### New Adapters

- N/A

### Features
 
 - Tiingo WS switched to the crypto-synth endpoint for synthetic cryptocurrency data streams

- Add the ability to rate limit WS messages for performance reasons. Limit added to the Tiingo adapter.

- Batching support added to forex adapters (polygon, openexchangerates, 1forge, tradermade, metalsapi, currencylayer, fixer)

- Redis falls back to using local cache on failures

- To allow more granular monitoring status code has been changed to reflect the status of the execution of the External Adapter itself. `providerStatusCode` has been added to show what response the data provider's API returned. In the example where the data provider's API goes down the EA would return statusCode 200 to show that the EA is functioning and providerStatusCode of 500 to show that the provider request failed. The request body will still contain a status of `errored`.

- Source maps removed from builds, giving substantial performance improvements. This may affect stack traces of errors, but with logging and metrics issues should still be easy to debug.

### Bug Fixes

 - Fix NCFX not  allowing most input tickers through

- Security fix to remove an APY-finance adapter's dependency

- Amendment to Agoric's fees decimal places

### Refactors

- Non-BTC Proof of Reserves adapters changed to have a consistent interface and typing

- Many more source adapter TypeScript types added for API response structures

2022-01-11 00:56 UTC, austinborn approved these changes

2022-01-11 11:14 UTC, boxhock submitted a review, later dismissed

2022-01-12 02:29 UTC, austinborn approved these changes

2022-01-12 10:01 UTC, boxhock requested changes
Blocking

2022-01-18 23:52 UTC, austinborn submitted a review, later dismissed

2022-01-19 11:51 UTC, boxhock submitted a review, later dismissed

2022-01-19 14:46 UTC, kevincharm submitted a review, later dismissed

2022-01-19 17:53 UTC, austinborn approved these changes

2022-01-19 17:54 UTC, alejoberardino approved these changes

2022-01-19 17:57 UTC, kevincharm approved these changes

2022-01-19 18:25 UTC, boxhock approved these changes

2022-01-19 19:34 UTC, merged