Release/v1.21.0
smartcontractkit/external-adapters-js pull request #1825
Opened 2022-04-25 17:18 UTC by mjk90

## Changelog

### Breaking Changes
- 

### New Adapters
- 

### Features
- 

### Bug Fixes
- 

### Notable Adapter Updates
|    Adapter    | Version |
| :-----------: | :-----: |
| my-foobar-ea  | v1.2.3  |

2022-04-27 15:01 UTC, boxhock requested changes
This doesn't look right, is #1827 included in this release?

2022-04-27 15:19 UTC, mjk90 commented
> This doesn't look right, is #1827 included in this release?

#1827 is not included, it was created after this PR

2022-04-28 10:14 UTC, boxhock approved these changes

2022-04-28 10:47 UTC, cds95 approved these changes

2022-04-28 10:57 UTC, merged