Fix/bitcoin por list protocol
smartcontractkit/external-adapters-js pull request #1891
Opened 2022-05-23 20:35 UTC by KuphJr

## Changes

- Fixed bug in the `proof-of-reserves` adapter that caused it to not work using the list protocol
- Added integration tests

## Steps to Test

`yarn test proof-of-reserves`

## Quality Assurance

- [x] Ran `yarn changeset` if adapter source code was changed
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

2022-05-23 20:41 UTC, austinborn commented on packages/composites/proof-of-reserves/test/integration/adapter.test.ts
> +  process.env.POR_INDEXER_ADAPTER_URL = 'https://adapters.main.prod.cldev.sh/por-indexer'
Can you change this to a fake url?

2022-05-23 20:42 UTC, austinborn commented on packages/composites/proof-of-reserves/src/utils/protocol.ts
> +  console.log(data)
Remove plz

2022-05-23 20:44 UTC, austinborn commented on packages/composites/proof-of-reserves/src/utils/protocol.ts
> +    })
Nbd but I like to remove the `return` keyword when possible
```suggestion
    const result = (data.addresses as string[]).map((address: string) => (
      { address, network: data.network, chainId: data.chainId }
    ))
```

2022-05-24 03:15 UTC, justinkaseman commented on packages/composites/proof-of-reserves/test/integration/adapter.DISABLEDtest.ts
> +import * as process from 'process'
Based on this file's name is it not intended to run?

2022-05-24 14:01 UTC, boxhock requested changes

2022-05-24 14:11 UTC, KuphJr commented on packages/composites/proof-of-reserves/src/utils/protocol.ts
> +type AddressObject = { address: string; network?: string; chainId?: string }
The problem is, sometimes they ARE optional.  For example, the 'eth-balance' indexer does NOT require chainId or network.

2022-05-24 14:11 UTC, KuphJr commented on packages/composites/proof-of-reserves/src/utils/protocol.ts
> +type AddressObject = { address: string; network?: string; chainId?: string }
The problem is, sometimes they ARE optional.  For example, the 'eth-balance' indexer does NOT require chainId or network.

2022-05-24 14:36 UTC, boxhock requested changes

2022-05-24 14:36 UTC, boxhock commented on packages/composites/proof-of-reserves/src/utils/protocol.ts
> +  data: { addresses: AddressList; chainId?: string; network?: string },
If using the suggested change above, we get:

```suggestion
  data: AddressList,
```

2022-05-25 00:10 UTC, closed without merging

2022-05-25 12:17 UTC, boxhock commented
This change was moved to #1896