Release/v1.27.0
smartcontractkit/external-adapters-js pull request #1939
Opened 2022-06-07 19:13 UTC by alejoberardino

## Changelog

### Breaking Changes
- Renamed Durin EA to CCIP Read

### Features
- Added telemetry data to EA responses in core framework
- Logs will show ISO times when DEBUG=true is set
- Added override to coinid for UST in coinmarketcap EA
- Added calcNetShareValueInAsset endpoint to enzyme adapter
- Added support for metis to layer2-sequencer-health EA

### Bug Fixes
- Fixed Filecoin address validation for actor addresses in POR adapter
- Fixed issue where API endpoint could not be changed via the API_ENDPOINT var for coinpaprika

### Notable Adapter Updates
|    Adapter    | Version | Description |
| :-----------: | :-----: | :---------: |
| ccip-read | v2.0.0 | Renamed, was Durin EA |
| proof-of-reserves | v1.8.0 | Fixed filecoin address validation for actor addresses |
| coinmarketcap | v1.4.0 | Added override to coinid for UST |
| enzyme-adapter | v1.2.0 | Added calcNetShareValueInAsset endpoint |
| layer2-sequencer-health | v1.4.0 | Add support for Metis |
| coinpaprika | v1.8.10 | Fix API_ENDPOINT env var behavior |

2022-06-07 20:57 UTC, boxhock requested changes

2022-06-07 20:57 UTC, boxhock commented on .changeset/tidy-beers-shake.md
> +Updated etherchain gasprice endpoint to use /api/gasnow api. Updated tests to match new endpoint
This branch has been updated automatically and is now ahead of where it should be. You need to revert the latest commit(s)

2022-06-07 21:50 UTC, justinkaseman approved these changes

2022-06-07 22:37 UTC, justinkaseman requested changes
Mono-repo version need le bump

2022-06-08 11:12 UTC, boxhock approved these changes

2022-06-08 16:53 UTC, merged