Fix/42679 - remove ip label
smartcontractkit/external-adapters-js pull request #1943
Opened 2022-06-08 13:44 UTC by mjk90

## Closes #42679

## Description

Removed request_origin label from metrics to reduce metrics cardinality. The IP & hostname are being logged for each request so it's not worth it to keep it as a metrics label if it increases the size of metrics data too much.

## Changes

Removed request_origin label from metrics & tests

## Steps to Test

1. `yarn test:unit`
2. `yarn test:integration`
3. Run an EA locally with metric enabled & check that request_origin label is no longer present in metrics

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [x] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2022-06-08 16:53 UTC, justinkaseman commented
Do we know 100% that this was the part causing the problem? Like do we have a before vs. after benchmark?

2022-06-08 17:14 UTC, justinkaseman commented
It seems to me like request origin should be relatively stable.

2022-06-08 17:41 UTC, boxhock submitted a review, later dismissed

2022-06-08 18:01 UTC, mjk90 commented
> Instead of outright removing it, have you considered just removing the outbound port?
> 
> If that's not a viable option or if the request origin is not needed in metrics, then this PR LGTM

I did consider that but I though the overhead of finding and replacing a string on each request would probably not be worth it

2022-06-08 21:43 UTC, boxhock requested changes
One small comment for the changeset, otherwise LGTM

2022-06-08 21:43 UTC, boxhock commented on .changeset/twelve-queens-sell.md
> +Removed request_origin label from metrics
Should add a comment about the `result` key being removed as welll

2022-06-09 03:01 UTC, justinkaseman commented
Not for this PR, but something I am thinking about is how we can better catch issues like this in the future. Maybe setting up an alert on the cardinality of our metrics with something like https://github.com/thought-machine/prometheus-cardinality-exporter

2022-06-09 12:49 UTC, merged