Add environment secrets to release workflow
smartcontractkit/external-adapters-js pull request #1947
Opened 2022-06-09 02:54 UTC by justinkaseman

## Closes sc-42958

2022-06-13 16:45 UTC, HenryNguyen5 requested changes

2022-06-13 16:45 UTC, HenryNguyen5 commented on .github/workflows/release.yml
> +          role-to-assume: ${{ secrets.AWS_ARN_EA_PUBLIC }}
Any particular reason for rename? The previous one was much more descriptive

2022-06-13 18:03 UTC, chainchad submitted a review, later dismissed
LGTM but I agree with [HenryNugyen5's comment](https://github.com/smartcontractkit/external-adapters-js/pull/1947/files#r895930943) about the name (nit).

2022-06-15 16:06 UTC, HenryNguyen5 submitted a review, later dismissed

2022-06-16 16:18 UTC, HenryNguyen5 commented on .github/workflows/release.yml
> +          aws-role-to-assume: ${{ secrets.AWS_PRIVATE_ECR_ARN }}
I think `AWS_OIDC_IAM_ROLE_ARN` is ideal, @chainchad should we document this std practice we want to adopt? Namely, "AWS_OIDC_IAM_ROLE_ARN is used as a secret per environment, where it contains the role arn containing the relevant permissions for the github environment it lives in"

2022-06-16 16:24 UTC, chainchad commented on .github/workflows/release.yml
> +          aws-role-to-assume: ${{ secrets.AWS_PRIVATE_ECR_ARN }}
Sounds good, just put up a separate PR in another repo and added you as a reviewer for the docs on that @HenryNguyen5.

2022-06-16 16:57 UTC, chainchad commented on .github/workflows/release.yml
> +          aws-role-to-assume: ${{ secrets.AWS_PRIVATE_ECR_ARN }}
```suggestion
          aws-role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN }}
```

2022-06-16 16:57 UTC, chainchad commented on .github/workflows/release.yml
> +          role-to-assume: ${{ secrets.AWS_PUBLIC_ECR_ARN }}
```suggestion
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN }}
```

2022-06-16 19:25 UTC, justinkaseman commented on .github/workflows/release.yml
>            aws-ecr-account-ids: ${{ secrets.AWS_PRIVATE_ECR_SECONDARY_ACCOUNT_ACCESS_IDS }}
@HenryNguyen5 we will need your help with this one

2022-06-16 21:33 UTC, chainchad reviewed
LGTM but I'd wait to merge until the separate role PR gets merged.

2022-06-17 18:25 UTC, chainchad approved these changes
👍

2022-07-19 18:00 UTC, merged