Release/v1.29.0
smartcontractkit/external-adapters-js pull request #1976
Opened 2022-06-20 21:09 UTC by austinborn

## Changelog

### Breaking Changes
- 

### New Adapters
- 

### Features
- 

### Bug Fixes
- 

### Documentation
-

### Notable Adapter Updates
|    Adapter    | Version | Description |
| :-----------: | :-----: | :---------: |
| my-foobar-ea  | v1.2.3  | Description of changes |

2022-06-22 10:51 UTC, mjk90 approved these changes

2022-06-23 00:20 UTC, KuphJr requested changes
There is a bug introduced in this release that must be fixed before it can go out: https://chainlink-core.slack.com/archives/C0206Q70SJX/p1655936668637069

2022-06-23 00:27 UTC, austinborn commented
Also need to investigate a potential issue with `wBTC` before release as well.

2022-07-01 19:32 UTC, boxhock approved these changes

2022-07-01 19:40 UTC, cds95 commented
Dismissed review as bug has been solved

2022-07-01 19:43 UTC, justinkaseman approved these changes

2022-07-01 19:43 UTC, KuphJr approved these changes

2022-07-01 19:44 UTC, merged