Fix/tradingeconomics endpoint
smartcontractkit/external-adapters-js pull request #2061
Opened 2022-07-29 13:04 UTC by austinborn

## Closes [#48659](https://app.shortcut.com/chainlinklabs/story/48659/tradingeconomics-ws-failure)

## Description
Fixes a bug introduced from #2021 

## Changes
- Add `price_ws` as an exported endpoint

## Steps to Test
1. Run Tradingeconomics EA with `WS_ENABLED=true`
2. Query it with one of the following:
```
{
  "id": "1",
  "data": {
     "base": "BNB",
     "quote": "USD",
     "endpoint": "crypto"
  }
}
OR
{
  "id": "1",
  "data": {
     "base": "MYR",
     "quote": "USD",
     "endpoint": "forex"
  }
}
 ```

## Quality Assurance

- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [x] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2022-07-29 13:05 UTC, austinborn commented
So this gets the WS connection going, but locally my EA still isn't responding with proper results. Can someone else test it to ensure the EA is otherwise working properly?

2022-07-29 15:57 UTC, KuphJr approved these changes

2022-07-29 16:16 UTC, KuphJr requested changes
Neither endpoint works when running locally

2022-07-30 02:35 UTC, justinkaseman approved these changes

2022-07-30 13:42 UTC, KuphJr approved these changes

2022-07-30 13:42 UTC, merged