Refactor/remove any types from EA
smartcontractkit/external-adapters-js pull request #2114
Opened 2022-08-17 02:53 UTC by bogos

## Description

Remove any types from EA

## Steps to Test

yarn lint 

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [X] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2022-09-07 10:08 UTC, boxhock requested changes
Only had a quick look for now. Mostly had questions around accepting `any` in WS EAs. Would it not be better to use the unknown WS message type instead of explicitly disabling the `any` check there?

2022-09-07 10:08 UTC, boxhock commented on packages/core/test-helpers/src/helpers.ts
> +export function assertError(statusCode: any, data: any, expectedJobId: any): void {
Are these really necessary? Seems like we should be able to get types for a few of these, right?

2022-09-07 10:08 UTC, boxhock commented on packages/sources/1forge/src/adapter.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Is this one also needed?

2022-09-07 10:08 UTC, boxhock commented on packages/sources/amberdata/src/adapter.ts
>  export const makeWSHandler = (defaultConfig?: DefaultConfig): MakeWSHandler<Message | any> =>
Would it be better to do Message | UnknownWSMessage instead, so we avoid disabling the any check?

2022-09-07 10:08 UTC, boxhock commented on packages/sources/cfbenchmarks/src/adapter.ts
>  export const makeWSHandler = (config?: Config): MakeWSHandler<Message | any> =>
Same as above

2023-04-26 14:50 UTC, alejoberardino commented
Closing this, as the new framework supersedes this work

2023-04-26 14:50 UTC, closed without merging