New Adapter Paxos
smartcontractkit/external-adapters-js pull request #214
Opened 2021-01-08 08:23 UTC by emmick4

Creates a new adapter for checking Paxos asset supply attestations.

2021-01-11 19:35 UTC, justinkaseman requested changes

2021-01-11 19:35 UTC, justinkaseman commented on paxos/src/index.ts
> +const NAME = 'EXAMPLE'
```suggestion
const NAME = 'PAXOS'
```

2021-01-11 19:35 UTC, justinkaseman commented on paxos/src/endpoint/assetAttestations.ts
> +  const params = {}
Could remove this here and the next line unless you are intending to clear out `params`

2021-01-12 23:24 UTC, thodges-gh approved these changes

2021-01-12 23:54 UTC, merged