feat: [sc-42715] Extend k6 automation to cover multiple EAs
smartcontractkit/external-adapters-js pull request #2159
Opened 2022-09-08 21:44 UTC by ad0ll

Story details: https://app.shortcut.com/chainlinklabs/story/42715

2022-09-13 13:42 UTC, boxhock requested changes
Great work on this! Had some minor comments. Not sure why integration tests are failing, could be flaky? Worth trying to re-run and see if result changes

2022-09-13 13:42 UTC, boxhock commented on packages/k6/README.md
> +> **Note** > `[adapter].env` can be omitted if your EA doesn't require environment variables to be tested
```suggestion
> **Note**
> `[adapter].env` can be omitted if your EA doesn't require environment variables to be tested
```

2022-09-13 13:42 UTC, boxhock commented on packages/k6/automate-start-purge.sh
> +done
Adding missing newline

```suggestion
done

```

2022-09-13 13:42 UTC, boxhock commented on packages/k6/src/test-limits.ts
> +  console.log(config)
Should we keep or remove?

2022-09-26 21:52 UTC, alejoberardino approved these changes

2022-09-26 22:27 UTC, alejoberardino approved these changes

2022-09-26 22:42 UTC, merged