Chore/Add DEBUG and NODE_ENV warnings
smartcontractkit/external-adapters-js pull request #2278
Opened 2022-10-26 16:23 UTC by amit-momin

## Closes SC-56137

## Description

Log warning on startup when `DEBUG=true` and/or `NODE_ENV=development`.

## Changes

- Added DEBUG=true warning
- Added NODE_ENV=development warning

## Steps to Test

1. Set DEBUG to true
2. Set NODE_ENV to development
3. Start any adapter
4. Verify the warning logs for these env vars are present

## Quality Assurance

- [X] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [X] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [X] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [X] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [X] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [X] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2022-10-28 12:43 UTC, boxhock requested changes

2022-10-28 12:43 UTC, boxhock commented on packages/core/bootstrap/src/lib/util.ts
> +    logger.warn(`The adapter is running with NODE_ENV set to development.`)
Can we make this clearer?

```suggestion
    logger.warn(`The adapter is running with NODE_ENV set to development. YOU SHOULD NOT BE RUNNING THIS IN PRODUCTION!`)
```

2022-10-31 14:28 UTC, boxhock approved these changes

2022-10-31 14:51 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coingecko succeeded</summary>

```
default   [  96% ] 1 VUs  09m35.4s/10m0s

running (09m37.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.4s/10m0s

running (09m38.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.4s/10m0s

running (09m39.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.4s/10m0s

running (09m40.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.4s/10m0s

running (09m41.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.4s/10m0s

running (09m42.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.4s/10m0s

running (09m43.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.4s/10m0s

running (09m44.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.4s/10m0s

running (09m45.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.4s/10m0s

running (09m46.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.4s/10m0s

running (09m47.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.4s/10m0s

running (09m48.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.4s/10m0s

running (09m49.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.4s/10m0s

running (09m50.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.4s/10m0s

running (09m51.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.4s/10m0s

running (09m52.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.4s/10m0s

running (09m53.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.4s/10m0s

running (09m54.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.4s/10m0s

running (09m55.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.4s/10m0s

running (09m56.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.4s/10m0s

running (09m57.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.4s/10m0s

running (09m58.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.4s/10m0s

running (09m59.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.4s/10m0s

running (10m00.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.4s/10m0s

running (10m01.7s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coingecko-ALCX / USD returned 200
     ✓ Group-coingecko-ANKR / USD returned 200
     ✓ Group-coingecko-ATOM / ETH returned 200
     ✓ Group-coingecko-CBETH / USD returned 200
     ✓ Group-coingecko-CREAM / ETH returned 200
     ✓ Group-coingecko-BUSD / ETH returned 200
     ✓ Group-coingecko-BNT / ETH returned 200
     ✓ Group-coingecko-1INCH / USD returned 200
     ✓ Group-coingecko-AMPL / USD returned 200
     ✓ Group-coingecko-AUDIO / USD returned 200
     ✓ Group-coingecko-BAL / ETH returned 200
     ✓ Group-coingecko-APE / ETH returned 200
     ✓ Group-coingecko-BNB / ETH returned 200
     ✓ Group-coingecko-BNB / USD returned 200
     ✓ Group-coingecko-AXS / ETH returned 200
     ✓ Group-coingecko-AMP / USD returned 200
     ✓ Group-coingecko-ATOM / USD returned 200
     ✓ Group-coingecko-BADGER / ETH returned 200
     ✓ Group-coingecko-AMPL / ETH returned 200
     ✓ Group-coingecko-BAND / ETH returned 200
     ✓ Group-coingecko-ARPA / USD returned 200
     ✓ Group-coingecko-ALCX / ETH returned 200
     ✓ Group-coingecko-ANT / ETH returned 200
     ✓ Group-coingecko-APE / USD returned 200
     ✓ Group-coingecko-BUSD / USD returned 200
     ✓ Group-coingecko-BAT / ETH returned 200
     ✓ Group-coingecko-ALPHA / ETH returned 200
     ✓ Group-coingecko-BAT / USD returned 200
     ✓ Group-coingecko-ALBT / USD returned 200
     ✓ Group-coingecko-C98 / USD returned 200
     ✓ Group-coingecko-BORING / USD returned 200
     ✓ Group-coingecko-AAVE / ETH returned 200
     ✓ Group-coingecko-CELO / ETH returned 200
     ✓ Group-coingecko-BOND / ETH returned 200
     ✓ Group-coingecko-ADX / USD returned 200
     ✓ Group-coingecko-AAVE / USD returned 200
     ✓ Group-coingecko-ALUSD / USD returned 200
     ✓ Group-coingecko-AVAX / USD returned 200
     ✓ Group-coingecko-BNT / USD returned 200
     ✓ Group-coingecko-COMP / ETH returned 200
     ✓ Group-coingecko-1INCH / ETH returned 200
     ✓ Group-coingecko-BTC / USD returned 200
     ✓ Group-coingecko-COMP / USD returned 200
     ✓ Group-coingecko-CAKE / USD returned 200
     ✓ Group-coingecko-CEL / ETH returned 200
     ✓ Group-coingecko-BCH / USD returned 200
     ✓ Group-coingecko-BTC / ETH returned 200
     ✓ Group-coingecko-BADGER / USD returned 200
     ✓ Group-coingecko-ADA / USD returned 200
     ✓ Group-coingecko-BAND / USD returned 200

     checks.........................: 100.00% ✓ 6000     ✗ 0   
     data_received..................: 1.8 MB  3.0 kB/s
     data_sent......................: 817 kB  1.4 kB/s
     errors.........................: 0.00%   ✓ 0        ✗ 6000
     http_req_blocked...............: avg=17.91µs min=107ns   med=186ns   max=105.69ms p(90)=288ns    p(95)=372ns   
     http_req_connecting............: avg=112ns   min=0s      med=0s      max=676.05µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=16.74ms min=5.52ms  med=13.58ms max=737.53ms p(90)=18.52ms  p(95)=21.1ms  
       { expected_response:true }...: avg=16.74ms min=5.52ms  med=13.58ms max=737.53ms p(90)=18.52ms  p(95)=21.1ms  
   ✓ http_req_failed................: 0.00%   ✓ 0        ✗ 6000
     http_req_receiving.............: avg=77.39µs min=10.14µs med=50.56µs max=10.34ms  p(90)=106.51µs p(95)=133.1µs 
     http_req_sending...............: avg=66.18µs min=16.45µs med=47.2µs  max=464.91µs p(90)=123.34µs p(95)=206.55µs
     http_req_tls_handshaking.......: avg=17.48µs min=0s      med=0s      max=104.89ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=16.59ms min=5.45ms  med=13.44ms max=737.15ms p(90)=18.32ms  p(95)=20.87ms 
     http_reqs......................: 6000    9.956673/s
     iteration_duration.............: avg=5s      min=4.99s   med=5s      max=5s       p(90)=5s       p(95)=5s      
     iterations.....................: 120     0.199133/s
     vus............................: 0       min=0      max=1 
     vus_max........................: 1       min=0      max=1 
```
</details>

2022-10-31 14:51 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinmarketcap succeeded</summary>

```
running (09m46.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.4s/10m0s

running (09m47.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.4s/10m0s

running (09m48.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.4s/10m0s

running (09m49.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.4s/10m0s

running (09m50.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.4s/10m0s

running (09m51.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.4s/10m0s

running (09m52.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.4s/10m0s

running (09m53.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.4s/10m0s

running (09m54.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.4s/10m0s

running (09m55.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.4s/10m0s

running (09m56.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.4s/10m0s

running (09m57.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.4s/10m0s

running (09m58.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.4s/10m0s

running (09m59.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.4s/10m0s

running (10m00.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.4s/10m0s

running (10m01.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 0/1 VUs, 117 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.6s), 0/1 VUs, 117 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.8s), 0/1 VUs, 117 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coinmarketcap-COMP / USD returned 200
     ✓ Group-coinmarketcap-BNT / USD returned 200
     ✓ Group-coinmarketcap-ANKR / USD returned 200
     ✗ Group-coinmarketcap-CELO / ETH returned 200
      ↳  99% — ✓ 116 / ✗ 1
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✗ Group-coinmarketcap-ADX / USD returned 200
      ↳  92% — ✓ 108 / ✗ 9
     ✓ Group-coinmarketcap-BUSD / USD returned 200
     ✓ Group-coinmarketcap-ALPHA / ETH returned 200
     ✓ Group-coinmarketcap-BTC / USD returned 200
     ✗ Group-coinmarketcap-APE / ETH returned 200
      ↳  97% — ✓ 114 / ✗ 3
     ✓ Group-coinmarketcap-ALCX / ETH returned 200
     ✓ Group-coinmarketcap-BAND / USD returned 200
     ✓ Group-coinmarketcap-ALUSD / USD returned 200
     ✓ Group-coinmarketcap-AMPL / USD returned 200
     ✓ Group-coinmarketcap-ATOM / ETH returned 200
     ✗ Group-coinmarketcap-1INCH / ETH returned 200
      ↳  97% — ✓ 114 / ✗ 3
     ✓ Group-coinmarketcap-BUSD / ETH returned 200
     ✓ Group-coinmarketcap-BAL / ETH returned 200
     ✓ Group-coinmarketcap-AAVE / USD returned 200
     ✓ Group-coinmarketcap-ALCX / USD returned 200
     ✗ Group-coinmarketcap-BNB / USD returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✓ Group-coinmarketcap-BADGER / USD returned 200
     ✗ Group-coinmarketcap-ADA / USD returned 200
      ↳  93% — ✓ 109 / ✗ 8
     ✗ Group-coinmarketcap-ANT / ETH returned 200
      ↳  93% — ✓ 109 / ✗ 8
     ✗ Group-coinmarketcap-BAND / ETH returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✗ Group-coinmarketcap-BORING / USD returned 200
      ↳  92% — ✓ 108 / ✗ 9
     ✓ Group-coinmarketcap-ALBT / USD returned 200
     ✓ Group-coinmarketcap-BAT / USD returned 200
     ✓ Group-coinmarketcap-APE / USD returned 200
     ✗ Group-coinmarketcap-BTC / ETH returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✗ Group-coinmarketcap-AUDIO / USD returned 200
      ↳  92% — ✓ 108 / ✗ 9
     ✗ Group-coinmarketcap-AAVE / ETH returned 200
      ↳  97% — ✓ 114 / ✗ 3
     ✓ Group-coinmarketcap-1INCH / USD returned 200
     ✓ Group-coinmarketcap-BIT / USD returned 200
     ✓ Group-coinmarketcap-BNB / ETH returned 200
     ✓ Group-coinmarketcap-ARPA / USD returned 200
     ✓ Group-coinmarketcap-BAT / ETH returned 200
     ✗ Group-coinmarketcap-AXS / ETH returned 200
      ↳  92% — ✓ 108 / ✗ 9
     ✗ Group-coinmarketcap-C98 / USD returned 200
      ↳  93% — ✓ 109 / ✗ 8
     ✗ Group-coinmarketcap-AVAX / USD returned 200
      ↳  93% — ✓ 109 / ✗ 8
     ✓ Group-coinmarketcap-ATOM / USD returned 200
     ✗ Group-coinmarketcap-BADGER / ETH returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✗ Group-coinmarketcap-CEL / ETH returned 200
      ↳  93% — ✓ 109 / ✗ 8
     ✗ Group-coinmarketcap-COMP / ETH returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✓ Group-coinmarketcap-BCH / USD returned 200
     ✗ Group-coinmarketcap-AMP / USD returned 200
      ↳  92% — ✓ 108 / ✗ 9
     ✗ Group-coinmarketcap-AMPL / ETH returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✗ Group-coinmarketcap-BNT / ETH returned 200
      ↳  96% — ✓ 113 / ✗ 4
     ✗ Group-coinmarketcap-BOND / ETH returned 200
      ↳  92% — ✓ 108 / ✗ 9
     ✓ Group-coinmarketcap-CAKE / USD returned 200

     checks.........................: 97.67% ✓ 5714     ✗ 136 
     data_received..................: 1.7 MB 2.9 kB/s
     data_sent......................: 794 kB 1.3 kB/s
     errors.........................: 2.32%  ✓ 136      ✗ 5714
     http_req_blocked...............: avg=24.76µs min=109ns   med=189ns   max=142.85ms p(90)=286ns    p(95)=358ns   
     http_req_connecting............: avg=166ns   min=0s      med=0s      max=973.13µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=67.97ms min=2.64ms  med=13.17ms max=3.12s    p(90)=18.19ms  p(95)=20.74ms 
       { expected_response:true }...: avg=19.88ms min=3.5ms   med=13.12ms max=3.12s    p(90)=17.59ms  p(95)=19.44ms 
   ✓ http_req_failed................: 2.32%  ✓ 136      ✗ 5714
     http_req_receiving.............: avg=58.56µs min=10.79µs med=45.25µs max=5.59ms   p(90)=95.04µs  p(95)=116.07µs
     http_req_sending...............: avg=65.26µs min=20.61µs med=47.08µs max=561.09µs p(90)=121.72µs p(95)=201.48µs
     http_req_tls_handshaking.......: avg=22.98µs min=0s      med=0s      max=134.46ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=67.84ms min=2.53ms  med=13.03ms max=3.12s    p(90)=18.06ms  p(95)=20.58ms 
     http_reqs......................: 5850   9.688641/s
     iteration_duration.............: avg=5.13s   min=4.99s   med=5s      max=10.1s    p(90)=5s       p(95)=5.08s   
     iterations.....................: 117    0.193773/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

2022-10-31 14:51 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for tiingo succeeded</summary>

```
running (09m37.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.4s/10m0s

running (09m38.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.4s/10m0s

running (09m39.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.4s/10m0s

running (09m40.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.4s/10m0s

running (09m41.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.4s/10m0s

running (09m42.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.4s/10m0s

running (09m43.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.4s/10m0s

running (09m44.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.4s/10m0s

running (09m45.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.4s/10m0s

running (09m46.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.4s/10m0s

running (09m47.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.4s/10m0s

running (09m48.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.4s/10m0s

running (09m49.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.4s/10m0s

running (09m50.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.4s/10m0s

running (09m51.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.4s/10m0s

running (09m52.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.4s/10m0s

running (09m53.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.4s/10m0s

running (09m54.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.4s/10m0s

running (09m55.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.4s/10m0s

running (09m56.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.4s/10m0s

running (09m57.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.4s/10m0s

running (09m58.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.4s/10m0s

running (09m59.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.4s/10m0s

running (10m00.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.4s/10m0s

running (10m01.7s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-tiingo-DODO / USD returned 200
     ✓ Group-tiingo-ENS / USD returned 200
     ✓ Group-tiingo-AXS / ETH returned 200
     ✓ Group-tiingo-ETH / USD returned 200
     ✓ Group-tiingo-1INCH / USD returned 200
     ✓ Group-tiingo-DIA / USD returned 200
     ✓ Group-tiingo-C98 / USD returned 200
     ✓ Group-tiingo-DYDX / USD returned 200
     ✓ Group-tiingo-BADGER / USD returned 200
     ✓ Group-tiingo-CTSI / ETH returned 200
     ✓ Group-tiingo-CAKE / USD returned 200
     ✓ Group-tiingo-BIT / USD returned 200
     ✓ Group-tiingo-CELO / ETH returned 200
     ✓ Group-tiingo-FARM / ETH returned 200
     ✓ Group-tiingo-CSPR / USD returned 200
     ✓ Group-tiingo-EURT / USD returned 200
     ✓ Group-tiingo-ALPHA / ETH returned 200
     ✓ Group-tiingo-DAI / ETH returned 200
     ✓ Group-tiingo-APE / USD returned 200
     ✓ Group-tiingo-BAND / ETH returned 200
     ✗ Group-tiingo-CVX / ETH returned 200
      ↳  99% — ✓ 119 / ✗ 1
     ✓ Group-tiingo-BAL / USD returned 200
     ✗ Group-tiingo-ETH / BTC returned 200
      ↳  99% — ✓ 119 / ✗ 1
     ✓ Group-tiingo-ALCX / ETH returned 200
     ✓ Group-tiingo-AMPL / USD returned 200
     ✓ Group-tiingo-ARPA / USD returned 200
     ✓ Group-tiingo-BOND / ETH returned 200
     ✓ Group-tiingo-CBETH / USD returned 200
     ✓ Group-tiingo-ERN / USD returned 200
     ✓ Group-tiingo-ALBT / USD returned 200
     ✓ Group-tiingo-DOGE / USD returned 200
     ✓ Group-tiingo-AVAX / USD returned 200
     ✓ Group-tiingo-ENJ / USD returned 200
     ✓ Group-tiingo-AMPL / ETH returned 200
     ✓ Group-tiingo-ALUSD / USD returned 200
     ✓ Group-tiingo-DOT / USD returned 200
     ✓ Group-tiingo-CREAM / ETH returned 200
     ✓ Group-tiingo-1INCH / ETH returned 200
     ✓ Group-tiingo-CVX / USD returned 200
     ✓ Group-tiingo-DAI / USD returned 200
     ✓ Group-tiingo-BNT / USD returned 200
     ✓ Group-tiingo-CTX / USD returned 200
     ✓ Group-tiingo-ALCX / USD returned 200
     ✓ Group-tiingo-BTC / USD returned 200
     ✓ Group-tiingo-BNT / ETH returned 200
     ✓ Group-tiingo-ATOM / ETH returned 200
     ✓ Group-tiingo-BORING / USD returned 200
     ✓ Group-tiingo-ATOM / USD returned 200
     ✓ Group-tiingo-AUDIO / USD returned 200
     ✓ Group-tiingo-APE / ETH returned 200

     checks.........................: 99.96% ✓ 5998     ✗ 2   
     data_received..................: 1.8 MB 3.0 kB/s
     data_sent......................: 883 kB 1.5 kB/s
     errors.........................: 0.03%  ✓ 2        ✗ 5998
     http_req_blocked...............: avg=32.87µs min=100ns   med=180ns   max=195.14ms p(90)=273ns    p(95)=339ns   
     http_req_connecting............: avg=216ns   min=0s      med=0s      max=1.29ms   p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=13.52ms min=2.78ms  med=11.18ms max=674.03ms p(90)=15.16ms  p(95)=17.22ms 
       { expected_response:true }...: avg=13.52ms min=5.05ms  med=11.18ms max=674.03ms p(90)=15.16ms  p(95)=17.22ms 
   ✓ http_req_failed................: 0.03%  ✓ 2        ✗ 5998
     http_req_receiving.............: avg=59.83µs min=10.75µs med=44.18µs max=3.99ms   p(90)=98.97µs  p(95)=122.39µs
     http_req_sending...............: avg=62.49µs min=23.83µs med=42.7µs  max=511.48µs p(90)=121.82µs p(95)=210.13µs
     http_req_tls_handshaking.......: avg=31.35µs min=0s      med=0s      max=188.15ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=13.4ms  min=2.69ms  med=11.07ms max=673.94ms p(90)=15.01ms  p(95)=17.08ms 
     http_reqs......................: 6000   9.956809/s
     iteration_duration.............: avg=5s      min=4.99s   med=5s      max=5s       p(90)=5s       p(95)=5s      
     iterations.....................: 120    0.199136/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

2022-10-31 14:51 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  97% ] 1 VUs  09m41.5s/10m0s

running (09m43.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.5s/10m0s

running (09m44.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.5s/10m0s

running (09m45.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.5s/10m0s

running (09m46.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.5s/10m0s

running (09m47.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.5s/10m0s

running (09m48.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.5s/10m0s

running (09m49.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.5s/10m0s

running (09m50.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.5s/10m0s

running (09m51.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.5s/10m0s

running (09m52.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.5s/10m0s

running (09m53.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.5s/10m0s

running (09m54.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.5s/10m0s

running (09m55.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.5s/10m0s

running (09m56.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.5s/10m0s

running (09m57.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.5s/10m0s

running (09m58.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.5s/10m0s

running (09m59.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.5s/10m0s

running (10m00.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.5s/10m0s

running (10m01.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m05.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m06.8s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m07.2s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coinpaprika-BADGER / USD returned 200
     ✓ Group-coinpaprika-CRO / ETH returned 200
     ✓ Group-coinpaprika-BAL / ETH returned 200
     ✓ Group-coinpaprika-BUSD / ETH returned 200
     ✓ Group-coinpaprika-ARPA / USD returned 200
     ✓ Group-coinpaprika-AMPL / ETH returned 200
     ✓ Group-coinpaprika-APE / USD returned 200
     ✓ Group-coinpaprika-CREAM / ETH returned 200
     ✓ Group-coinpaprika-AUDIO / USD returned 200
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 119 / ✗ 1
     ✓ Group-coinpaprika-CRO / USD returned 200
     ✓ Group-coinpaprika-CEL / ETH returned 200
     ✓ Group-coinpaprika-1INCH / USD returned 200
     ✓ Group-coinpaprika-ALCX / ETH returned 200
     ✓ Group-coinpaprika-C98 / USD returned 200
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✓ Group-coinpaprika-AAVE / ETH returned 200
     ✓ Group-coinpaprika-ADA / USD returned 200
     ✓ Group-coinpaprika-BAT / USD returned 200
     ✓ Group-coinpaprika-BNT / USD returned 200
     ✓ Group-coinpaprika-BUSD / USD returned 200
     ✓ Group-coinpaprika-AXS / ETH returned 200
     ✓ Group-coinpaprika-BAND / USD returned 200
     ✓ Group-coinpaprika-BAND / ETH returned 200
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 119 / ✗ 1
     ✓ Group-coinpaprika-ALPHA / ETH returned 200
     ✓ Group-coinpaprika-ANT / ETH returned 200
     ✓ Group-coinpaprika-ALCX / USD returned 200
     ✓ Group-coinpaprika-ATOM / ETH returned 200
     ✓ Group-coinpaprika-BNT / ETH returned 200
     ✓ Group-coinpaprika-1INCH / ETH returned 200
     ✓ Group-coinpaprika-CELO / ETH returned 200
     ✓ Group-coinpaprika-COMP / ETH returned 200
     ✓ Group-coinpaprika-CRV / ETH returned 200
     ✓ Group-coinpaprika-AMPL / USD returned 200
     ✓ Group-coinpaprika-BNB / ETH returned 200
     ✓ Group-coinpaprika-BTC / ETH returned 200
     ✓ Group-coinpaprika-ALBT / USD returned 200
     ✓ Group-coinpaprika-AVAX / USD returned 200
     ✓ Group-coinpaprika-BNB / USD returned 200
     ✓ Group-coinpaprika-AMP / USD returned 200
     ✓ Group-coinpaprika-BCH / USD returned 200
     ✓ Group-coinpaprika-ADX / USD returned 200
     ✓ Group-coinpaprika-BAT / ETH returned 200
     ✓ Group-coinpaprika-ATOM / USD returned 200
     ✓ Group-coinpaprika-CAKE / USD returned 200
     ✓ Group-coinpaprika-COMP / USD returned 200
     ✓ Group-coinpaprika-ANKR / USD returned 200
     ✓ Group-coinpaprika-BIT / USD returned 200
     ✓ Group-coinpaprika-AAVE / USD returned 200

     checks.........................: 97.96% ✓ 5878     ✗ 122 
     data_received..................: 1.8 MB 3.0 kB/s
     data_sent......................: 802 kB 1.3 kB/s
     errors.........................: 2.03%  ✓ 122      ✗ 5878
     http_req_blocked...............: avg=33.06µs min=94ns    med=190ns   max=196.94ms p(90)=285ns    p(95)=328ns   
     http_req_connecting............: avg=111ns   min=0s      med=0s      max=666.59µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=73.32ms min=4.81ms  med=12.76ms max=4.17s    p(90)=19.24ms  p(95)=22.91ms 
       { expected_response:true }...: avg=22.55ms min=4.86ms  med=12.69ms max=2.31s    p(90)=18.5ms   p(95)=21.13ms 
   ✓ http_req_failed................: 2.03%  ✓ 122      ✗ 5878
     http_req_receiving.............: avg=75.28µs min=10.29µs med=48.97µs max=8.57ms   p(90)=110.45µs p(95)=138.09µs
     http_req_sending...............: avg=63.53µs min=22.85µs med=48.29µs max=502.74µs p(90)=113.14µs p(95)=167.1µs 
     http_req_tls_handshaking.......: avg=31.87µs min=0s      med=0s      max=191.22ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=73.18ms min=4.7ms   med=12.64ms max=4.17s    p(90)=19.09ms  p(95)=22.73ms 
     http_reqs......................: 6000   9.881316/s
     iteration_duration.............: avg=5.03s   min=4.99s   med=5s      max=9.55s    p(90)=5s       p(95)=5s      
     iterations.....................: 120    0.197626/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

2022-11-01 16:37 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coingecko succeeded</summary>

```
default   [  96% ] 1 VUs  09m36.3s/10m0s

running (09m38.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.3s/10m0s

running (09m39.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.3s/10m0s

running (09m40.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.3s/10m0s

running (09m41.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.3s/10m0s

running (09m42.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.3s/10m0s

running (09m43.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.3s/10m0s

running (09m44.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.3s/10m0s

running (09m45.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.3s/10m0s

running (09m46.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.3s/10m0s

running (09m47.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.3s/10m0s

running (09m48.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.3s/10m0s

running (09m49.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.3s/10m0s

running (09m50.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.3s/10m0s

running (09m51.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.3s/10m0s

running (09m52.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.3s/10m0s

running (09m53.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.3s/10m0s

running (09m54.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.3s/10m0s

running (09m55.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.3s/10m0s

running (09m56.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.3s/10m0s

running (09m57.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.3s/10m0s

running (09m58.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.3s/10m0s

running (09m59.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.3s/10m0s

running (10m00.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.3s/10m0s

running (10m01.7s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coingecko-AXS / ETH returned 200
     ✓ Group-coingecko-1INCH / USD returned 200
     ✓ Group-coingecko-AMPL / ETH returned 200
     ✓ Group-coingecko-ALBT / USD returned 200
     ✓ Group-coingecko-BCH / USD returned 200
     ✓ Group-coingecko-BAL / ETH returned 200
     ✓ Group-coingecko-ALPHA / ETH returned 200
     ✓ Group-coingecko-1INCH / ETH returned 200
     ✓ Group-coingecko-ADA / USD returned 200
     ✗ Group-coingecko-BTC / ETH returned 200
      ↳  99% — ✓ 119 / ✗ 1
     ✗ Group-coingecko-ALUSD / USD returned 200
      ↳  99% — ✓ 119 / ✗ 1
     ✓ Group-coingecko-ALCX / ETH returned 200
     ✓ Group-coingecko-CELO / ETH returned 200
     ✓ Group-coingecko-BOND / ETH returned 200
     ✓ Group-coingecko-BUSD / USD returned 200
     ✓ Group-coingecko-BAT / USD returned 200
     ✓ Group-coingecko-BNT / USD returned 200
     ✓ Group-coingecko-AMPL / USD returned 200
     ✓ Group-coingecko-BADGER / USD returned 200
     ✓ Group-coingecko-APE / ETH returned 200
     ✓ Group-coingecko-ADX / USD returned 200
     ✓ Group-coingecko-ATOM / ETH returned 200
     ✓ Group-coingecko-COMP / USD returned 200
     ✓ Group-coingecko-AAVE / USD returned 200
     ✓ Group-coingecko-BUSD / ETH returned 200
     ✓ Group-coingecko-BAND / USD returned 200
     ✓ Group-coingecko-BNT / ETH returned 200
     ✓ Group-coingecko-APE / USD returned 200
     ✓ Group-coingecko-COMP / ETH returned 200
     ✓ Group-coingecko-BAT / ETH returned 200
     ✓ Group-coingecko-CEL / ETH returned 200
     ✓ Group-coingecko-BNB / USD returned 200
     ✓ Group-coingecko-BADGER / ETH returned 200
     ✓ Group-coingecko-BNB / ETH returned 200
     ✓ Group-coingecko-ANKR / USD returned 200
     ✓ Group-coingecko-ALCX / USD returned 200
     ✓ Group-coingecko-ATOM / USD returned 200
     ✓ Group-coingecko-AVAX / USD returned 200
     ✓ Group-coingecko-AUDIO / USD returned 200
     ✓ Group-coingecko-ARPA / USD returned 200
     ✓ Group-coingecko-BAND / ETH returned 200
     ✗ Group-coingecko-C98 / USD returned 200
      ↳  98% — ✓ 118 / ✗ 2
     ✓ Group-coingecko-CREAM / ETH returned 200
     ✓ Group-coingecko-CBETH / USD returned 200
     ✓ Group-coingecko-CAKE / USD returned 200
     ✓ Group-coingecko-AAVE / ETH returned 200
     ✓ Group-coingecko-BORING / USD returned 200
     ✓ Group-coingecko-BTC / USD returned 200
     ✓ Group-coingecko-AMP / USD returned 200
     ✓ Group-coingecko-ANT / ETH returned 200

     checks.........................: 99.93% ✓ 5996     ✗ 4   
     data_received..................: 1.8 MB 3.0 kB/s
     data_sent......................: 817 kB 1.4 kB/s
     errors.........................: 0.06%  ✓ 4        ✗ 5996
     http_req_blocked...............: avg=28.53µs min=103ns    med=174ns   max=169.23ms p(90)=266ns    p(95)=360ns   
     http_req_connecting............: avg=137ns   min=0s       med=0s      max=823.64µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=15.76ms min=827.56µs med=13ms    max=720.33ms p(90)=17.7ms   p(95)=19.96ms 
       { expected_response:true }...: avg=15.76ms min=3.21ms   med=13.01ms max=720.33ms p(90)=17.7ms   p(95)=19.96ms 
   ✓ http_req_failed................: 0.06%  ✓ 4        ✗ 5996
     http_req_receiving.............: avg=56.44µs min=9.05µs   med=40.89µs max=3.95ms   p(90)=91.39µs  p(95)=111.98µs
     http_req_sending...............: avg=60.39µs min=13.14µs  med=42.96µs max=819.25µs p(90)=107.85µs p(95)=192.37µs
     http_req_tls_handshaking.......: avg=28.06µs min=0s       med=0s      max=168.36ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=15.64ms min=761.79µs med=12.88ms max=720.21ms p(90)=17.59ms  p(95)=19.86ms 
     http_reqs......................: 6000   9.955354/s
     iteration_duration.............: avg=5s      min=4.99s    med=5s      max=5s       p(90)=5s       p(95)=5s      
     iterations.....................: 120    0.199107/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

2022-11-01 16:37 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  97% ] 1 VUs  09m41.3s/10m0s

running (09m43.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.3s/10m0s

running (09m44.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.3s/10m0s

running (09m45.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.3s/10m0s

running (09m46.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.3s/10m0s

running (09m47.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.3s/10m0s

running (09m48.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.3s/10m0s

running (09m49.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.3s/10m0s

running (09m50.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.3s/10m0s

running (09m51.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.3s/10m0s

running (09m52.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.3s/10m0s

running (09m53.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.3s/10m0s

running (09m54.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.3s/10m0s

running (09m55.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.3s/10m0s

running (09m56.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.3s/10m0s

running (09m57.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.3s/10m0s

running (09m58.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.3s/10m0s

running (09m59.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.3s/10m0s

running (10m00.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.3s/10m0s

running (10m01.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 0/1 VUs, 119 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.5s), 0/1 VUs, 119 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-BUSD / USD returned 200
     ✓ Group-coinpaprika-1INCH / USD returned 200
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-CAKE / USD returned 200
     ✓ Group-coinpaprika-BUSD / ETH returned 200
     ✓ Group-coinpaprika-BORING / USD returned 200
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 117 / ✗ 2
     ✓ Group-coinpaprika-CRO / ETH returned 200
     ✓ Group-coinpaprika-ADX / USD returned 200
     ✓ Group-coinpaprika-ANT / ETH returned 200
     ✓ Group-coinpaprika-BNT / ETH returned 200
     ✓ Group-coinpaprika-CREAM / ETH returned 200
     ✓ Group-coinpaprika-AAVE / USD returned 200
     ✓ Group-coinpaprika-BAT / ETH returned 200
     ✓ Group-coinpaprika-ADA / USD returned 200
     ✓ Group-coinpaprika-CEL / ETH returned 200
     ✓ Group-coinpaprika-AXS / ETH returned 200
     ✓ Group-coinpaprika-AMPL / USD returned 200
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-BCH / USD returned 200
     ✓ Group-coinpaprika-BNT / USD returned 200
     ✓ Group-coinpaprika-BNB / USD returned 200
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 117 / ✗ 2
     ✓ Group-coinpaprika-AUDIO / USD returned 200
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-ALPHA / ETH returned 200
     ✓ Group-coinpaprika-ALCX / USD returned 200
     ✓ Group-coinpaprika-BTC / ETH returned 200
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-BAND / USD returned 200
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-ARPA / USD returned 200
     ✓ Group-coinpaprika-BIT / USD returned 200
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 117 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 117 / ✗ 2
     ✓ Group-coinpaprika-BAT / USD returned 200
     ✓ Group-coinpaprika-AMP / USD returned 200
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-ALBT / USD returned 200
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-1INCH / ETH returned 200
     ✓ Group-coinpaprika-CRV / ETH returned 200
     ✓ Group-coinpaprika-AAVE / ETH returned 200
     ✓ Group-coinpaprika-ATOM / USD returned 200
     ✓ Group-coinpaprika-ANKR / USD returned 200
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 118 / ✗ 1
     ✓ Group-coinpaprika-C98 / USD returned 200

     checks.........................: 99.68% ✓ 5931     ✗ 19  
     data_received..................: 1.8 MB 2.9 kB/s
     data_sent......................: 796 kB 1.3 kB/s
     errors.........................: 0.31%  ✓ 19       ✗ 5931
     http_req_blocked...............: avg=17.8µs  min=91ns    med=180ns   max=103.58ms p(90)=280ns    p(95)=376ns   
     http_req_connecting............: avg=37ns    min=0s      med=0s      max=220.88µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=25.84ms min=2.78ms  med=13.47ms max=4.94s    p(90)=19.46ms  p(95)=24.23ms 
       { expected_response:true }...: avg=25.84ms min=3.67ms  med=13.47ms max=4.94s    p(90)=19.4ms   p(95)=23.99ms 
   ✓ http_req_failed................: 0.31%  ✓ 19       ✗ 5931
     http_req_receiving.............: avg=70.5µs  min=12.33µs med=47.23µs max=17.32ms  p(90)=101.77µs p(95)=123.07µs
     http_req_sending...............: avg=62.94µs min=15.48µs med=46.35µs max=355.79µs p(90)=111.91µs p(95)=184.87µs
     http_req_tls_handshaking.......: avg=16.55µs min=0s      med=0s      max=98.52ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=25.71ms min=2.71ms  med=13.36ms max=4.94s    p(90)=19.31ms  p(95)=24.14ms 
     http_reqs......................: 5950   9.859177/s
     iteration_duration.............: avg=5.04s   min=4.99s   med=5s      max=10.84s   p(90)=5s       p(95)=5s      
     iterations.....................: 119    0.197184/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

2022-11-01 16:37 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinmarketcap succeeded</summary>

```
default   [  98% ] 1 VUs  09m49.2s/10m0s

running (09m51.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.2s/10m0s

running (09m52.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.2s/10m0s

running (09m53.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.2s/10m0s

running (09m54.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.2s/10m0s

running (09m55.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.2s/10m0s

running (09m56.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.2s/10m0s

running (09m57.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.2s/10m0s

running (09m58.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.2s/10m0s

running (09m59.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.2s/10m0s

running (10m00.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.2s/10m0s

running (10m01.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m05.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m06.6s), 0/1 VUs, 116 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m07.0s), 0/1 VUs, 116 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinmarketcap-1INCH / ETH returned 200
      ↳  99% — ✓ 115 / ✗ 1
     ✗ Group-coinmarketcap-CAKE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✗ Group-coinmarketcap-AAVE / ETH returned 200
      ↳  95% — ✓ 111 / ✗ 5
     ✓ Group-coinmarketcap-BAT / USD returned 200
     ✓ Group-coinmarketcap-BNB / USD returned 200
     ✓ Group-coinmarketcap-ADX / USD returned 200
     ✓ Group-coinmarketcap-BAND / ETH returned 200
     ✓ Group-coinmarketcap-BNB / ETH returned 200
     ✓ Group-coinmarketcap-ATOM / USD returned 200
     ✗ Group-coinmarketcap-BIT / USD returned 200
      ↳  99% — ✓ 115 / ✗ 1
     ✗ Group-coinmarketcap-AMPL / ETH returned 200
      ↳  93% — ✓ 109 / ✗ 7
     ✗ Group-coinmarketcap-AMPL / USD returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✗ Group-coinmarketcap-BUSD / USD returned 200
      ↳  97% — ✓ 113 / ✗ 3
     ✓ Group-coinmarketcap-ALPHA / ETH returned 200
     ✓ Group-coinmarketcap-AXS / ETH returned 200
     ✗ Group-coinmarketcap-BNT / ETH returned 200
      ↳  97% — ✓ 113 / ✗ 3
     ✗ Group-coinmarketcap-APE / ETH returned 200
      ↳  97% — ✓ 113 / ✗ 3
     ✗ Group-coinmarketcap-BADGER / USD returned 200
      ↳  96% — ✓ 112 / ✗ 4
     ✓ Group-coinmarketcap-ANKR / USD returned 200
     ✓ Group-coinmarketcap-ADA / USD returned 200
     ✓ Group-coinmarketcap-AUDIO / USD returned 200
     ✗ Group-coinmarketcap-BAND / USD returned 200
      ↳  97% — ✓ 113 / ✗ 3
     ✗ Group-coinmarketcap-COMP / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✓ Group-coinmarketcap-AAVE / USD returned 200
     ✓ Group-coinmarketcap-APE / USD returned 200
     ✗ Group-coinmarketcap-AVAX / USD returned 200
      ↳  93% — ✓ 109 / ✗ 7
     ✗ Group-coinmarketcap-BTC / USD returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✗ Group-coinmarketcap-ALCX / USD returned 200
      ↳  96% — ✓ 112 / ✗ 4
     ✗ Group-coinmarketcap-1INCH / USD returned 200
      ↳  97% — ✓ 113 / ✗ 3
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  97% — ✓ 113 / ✗ 3
     ✓ Group-coinmarketcap-BUSD / ETH returned 200
     ✓ Group-coinmarketcap-ARPA / USD returned 200
     ✗ Group-coinmarketcap-BOND / ETH returned 200
      ↳  99% — ✓ 115 / ✗ 1
     ✓ Group-coinmarketcap-ALUSD / USD returned 200
     ✓ Group-coinmarketcap-BORING / USD returned 200
     ✗ Group-coinmarketcap-C98 / USD returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✗ Group-coinmarketcap-ANT / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✗ Group-coinmarketcap-ALBT / USD returned 200
      ↳  93% — ✓ 109 / ✗ 7
     ✓ Group-coinmarketcap-ALCX / ETH returned 200
     ✓ Group-coinmarketcap-BAL / ETH returned 200
     ✓ Group-coinmarketcap-CEL / ETH returned 200
     ✓ Group-coinmarketcap-BNT / USD returned 200
     ✗ Group-coinmarketcap-COMP / USD returned 200
      ↳  93% — ✓ 108 / ✗ 8
     ✗ Group-coinmarketcap-CELO / ETH returned 200
      ↳  93% — ✓ 109 / ✗ 7
     ✗ Group-coinmarketcap-BTC / ETH returned 200
      ↳  93% — ✓ 109 / ✗ 7
     ✗ Group-coinmarketcap-BADGER / ETH returned 200
      ↳  99% — ✓ 115 / ✗ 1
     ✓ Group-coinmarketcap-AMP / USD returned 200
     ✗ Group-coinmarketcap-BAT / ETH returned 200
      ↳  99% — ✓ 115 / ✗ 1
     ✓ Group-coinmarketcap-ATOM / ETH returned 200
     ✗ Group-coinmarketcap-BCH / USD returned 200
      ↳  93% — ✓ 108 / ✗ 8

     checks.........................: 97.67% ✓ 5665     ✗ 135 
     data_received..................: 1.7 MB 2.9 kB/s
     data_sent......................: 788 kB 1.3 kB/s
     errors.........................: 2.32%  ✓ 135      ✗ 5665
     http_req_blocked...............: avg=17.64µs  min=95ns    med=167ns   max=100.93ms p(90)=247ns    p(95)=308ns   
     http_req_connecting............: avg=127ns    min=0s      med=0s      max=738.38µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=65.75ms  min=1.1ms   med=12.25ms max=5.15s    p(90)=16.69ms  p(95)=19.75ms 
       { expected_response:true }...: avg=21.19ms  min=2.91ms  med=12.21ms max=5.15s    p(90)=16.16ms  p(95)=18.54ms 
   ✓ http_req_failed................: 2.32%  ✓ 135      ✗ 5665
     http_req_receiving.............: avg=61.8µs   min=10.4µs  med=41.51µs max=38.37ms  p(90)=90.92µs  p(95)=110.38µs
     http_req_sending...............: avg=117.28µs min=10.67µs med=42.77µs max=83.37ms  p(90)=104.94µs p(95)=186.48µs
     http_req_tls_handshaking.......: avg=16.28µs  min=0s      med=0s      max=94.43ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=65.57ms  min=1.03ms  med=12.12ms max=5.15s    p(90)=16.54ms  p(95)=19.59ms 
     http_reqs......................: 5800   9.555229/s
     iteration_duration.............: avg=5.2s     min=4.99s   med=5s      max=10.09s   p(90)=5s       p(95)=7.53s   
     iterations.....................: 116    0.191105/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

2022-11-01 16:45 UTC, merged