fix: [sc-54728] Change bank-frick PRIVATE_KEY envvar from raw string to base64
smartcontractkit/external-adapters-js pull request #2280
Opened 2022-10-26 21:29 UTC by ad0ll

Story details: https://app.shortcut.com/chainlinklabs/story/54728

2022-10-27 13:04 UTC, boxhock requested changes
One small thing, otherwise LGTM

2022-10-27 13:04 UTC, boxhock commented on .changeset/olive-mugs-sort.md
> +'@chainlink/bank-frick-adapter': patch
Should be a `minor` update, since if a node op starts using a B64 encoded private key, they can't downgrade past that version.

2022-10-28 14:57 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.4s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 165 kB  275 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.15ms  min=147ns   med=268ns    max=5.09s    p(90)=477ns    p(95)=1.05µs  
     http_req_connecting........: avg=653ns    min=0s      med=0s       max=235.4µs  p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=4.62ms   min=1.78ms  med=4.24ms   max=30.31ms  p(90)=5.95ms   p(95)=6.96ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=53.94µs  min=20.51µs med=47.49µs  max=613.56µs p(90)=81.29µs  p(95)=96.26µs 
     http_req_sending...........: avg=116.79µs min=53.35µs med=109.67µs max=219.9µs  p(90)=165.52µs p(95)=176.61µs
     http_req_tls_handshaking...: avg=239.92µs min=0s      med=0s       max=86.37ms  p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=4.45ms   min=1.57ms  med=4.07ms   max=30.2ms   p(90)=5.81ms   p(95)=6.73ms  
     http_reqs..................: 360     0.599603/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.12s    p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199868/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-10-28 18:14 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.4s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 165 kB  275 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.21ms  min=119ns   med=266ns    max=5.11s    p(90)=464ns   p(95)=704ns   
     http_req_connecting........: avg=831ns    min=0s      med=0s       max=299.17µs p(90)=0s      p(95)=0s      
   ✓ http_req_duration..........: avg=5.9ms    min=3.37ms  med=5.69ms   max=19.76ms  p(90)=7.07ms  p(95)=8.05ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=53.37µs  min=18.09µs med=47.26µs  max=322.51µs p(90)=81.83µs p(95)=103.87µs
     http_req_sending...........: avg=126.49µs min=36.56µs med=120.67µs max=262.25µs p(90)=178.1µs p(95)=193.85µs
     http_req_tls_handshaking...: avg=300.83µs min=0s      med=0s       max=108.29ms p(90)=0s      p(95)=0s      
     http_req_waiting...........: avg=5.72ms   min=3.24ms  med=5.5ms    max=19.53ms  p(90)=6.91ms  p(95)=7.85ms  
     http_reqs..................: 360     0.599607/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.13s    p(90)=5s      p(95)=5s      
     iterations.................: 120     0.199869/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-10-28 19:01 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.4s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 166 kB  277 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.21ms  min=150ns   med=257ns    max=5.11s    p(90)=471ns    p(95)=1.21µs  
     http_req_connecting........: avg=1.81µs   min=0s      med=0s       max=654.71µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=4.45ms   min=2.39ms  med=4.25ms   max=17.85ms  p(90)=5.27ms   p(95)=5.9ms   
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=50.55µs  min=16.82µs med=44.34µs  max=612.4µs  p(90)=72.33µs  p(95)=87.26µs 
     http_req_sending...........: avg=117.68µs min=41.23µs med=106.83µs max=413.45µs p(90)=166.73µs p(95)=181.59µs
     http_req_tls_handshaking...: avg=301.31µs min=0s      med=0s       max=108.47ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=4.28ms   min=2.18ms  med=4.1ms    max=17.75ms  p(90)=5.04ms   p(95)=5.69ms  
     http_reqs..................: 360     0.599603/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.13s    p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199868/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-10-28 19:20 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.4s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 166 kB  277 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.16ms  min=146ns   med=267ns    max=5.09s    p(90)=493ns    p(95)=969ns   
     http_req_connecting........: avg=1.17µs   min=0s      med=0s       max=423.59µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=5.66ms   min=2.55ms  med=5.11ms   max=26.49ms  p(90)=7.5ms    p(95)=9.21ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=55.76µs  min=18.69µs med=42.86µs  max=1.9ms    p(90)=73.84µs  p(95)=96.2µs  
     http_req_sending...........: avg=161.96µs min=33.16µs med=113.73µs max=5.41ms   p(90)=169.21µs p(95)=185.11µs
     http_req_tls_handshaking...: avg=250.01µs min=0s      med=0s       max=90ms     p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=5.44ms   min=2.36ms  med=4.91ms   max=26.28ms  p(90)=7.18ms   p(95)=8.57ms  
     http_reqs..................: 360     0.599605/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.11s    p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199868/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-01 16:04 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.3s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 164 kB  273 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.08ms  min=161ns   med=271ns    max=5.06s    p(90)=465ns    p(95)=694ns   
     http_req_connecting........: avg=3µs      min=0s      med=0s       max=1.08ms   p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=5.11ms   min=1.59ms  med=4.69ms   max=20.01ms  p(90)=7.05ms   p(95)=7.85ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=49.88µs  min=19.85µs med=43.53µs  max=392.41µs p(90)=74.62µs  p(95)=91.11µs 
     http_req_sending...........: avg=129.24µs min=27.84µs med=124.34µs max=445.66µs p(90)=183.08µs p(95)=199.11µs
     http_req_tls_handshaking...: avg=168.78µs min=0s      med=0s       max=60.76ms  p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=4.93ms   min=1.46ms  med=4.51ms   max=19.86ms  p(90)=6.84ms   p(95)=7.7ms   
     http_reqs..................: 360     0.599699/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.09s    p(90)=5s       p(95)=5s      
     iterations.................: 120     0.1999/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-01 18:09 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.4s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 165 kB  275 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.26ms  min=152ns   med=270ns    max=5.13s    p(90)=503ns    p(95)=1.05µs  
     http_req_connecting........: avg=1.98µs   min=0s      med=0s       max=716.14µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=6.44ms   min=1.54ms  med=5.18ms   max=128.75ms p(90)=6.59ms   p(95)=7.85ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=49.86µs  min=12.89µs med=41.91µs  max=664.93µs p(90)=80.25µs  p(95)=96.75µs 
     http_req_sending...........: avg=117.14µs min=57.08µs med=107.81µs max=232.39µs p(90)=167.43µs p(95)=182.26µs
     http_req_tls_handshaking...: avg=348.84µs min=0s      med=0s       max=125.58ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=6.28ms   min=1.34ms  med=5.02ms   max=128.59ms p(90)=6.39ms   p(95)=7.62ms  
     http_reqs..................: 360     0.599607/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.15s    p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199869/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-01 19:41 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.2s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 164 kB  273 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=392.55µs min=148ns   med=254ns    max=141.19ms p(90)=493ns    p(95)=913ns   
     http_req_connecting........: avg=1.32µs   min=0s      med=0s       max=477.21µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=5.57ms   min=1.61ms  med=5.12ms   max=18.61ms  p(90)=7.45ms   p(95)=9.66ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=59.31µs  min=19.54µs med=43.48µs  max=3.17ms   p(90)=81.58µs  p(95)=87.83µs 
     http_req_sending...........: avg=119.87µs min=27.84µs med=104.97µs max=527.88µs p(90)=170.81µs p(95)=183.54µs
     http_req_tls_handshaking...: avg=372.52µs min=0s      med=0s       max=134.1ms  p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=5.39ms   min=1.41ms  med=4.94ms   max=18.56ms  p(90)=7.27ms   p(95)=9.13ms  
     http_reqs..................: 360     0.59981/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5s       p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199937/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-01 20:54 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.7s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.7s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.7s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.7s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.7s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.7s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.7s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.7s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.7s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.7s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.7s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.7s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.7s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.7s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.7s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.7s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.7s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.7s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.7s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.7s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.7s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.7s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.7s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.7s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.7s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.7s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.7s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.7s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.7s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.7s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.7s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.7s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.5s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 164 kB  273 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.24ms  min=140ns   med=271ns   max=5.12s    p(90)=511ns   p(95)=948ns   
     http_req_connecting........: avg=2.09µs   min=0s      med=0s      max=752.46µs p(90)=0s      p(95)=0s      
   ✓ http_req_duration..........: avg=4.35ms   min=1.2ms   med=4.19ms  max=19.52ms  p(90)=5.77ms  p(95)=6.57ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=52.14µs  min=11.66µs med=44.12µs max=835.41µs p(90)=76.85µs p(95)=92.29µs 
     http_req_sending...........: avg=128.73µs min=52.15µs med=120.8µs max=443.07µs p(90)=182.2µs p(95)=194.08µs
     http_req_tls_handshaking...: avg=329.01µs min=0s      med=0s      max=118.44ms p(90)=0s      p(95)=0s      
     http_req_waiting...........: avg=4.17ms   min=1ms     med=4.02ms  max=19.29ms  p(90)=5.61ms  p(95)=6.34ms  
     http_reqs..................: 360     0.599505/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s      max=5.13s    p(90)=5s      p(95)=5s      
     iterations.................: 120     0.199835/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-01 21:18 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.6s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 164 kB  271 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.16ms  min=144ns   med=315ns    max=5.09s    p(90)=457ns    p(95)=726ns   
     http_req_connecting........: avg=1.77µs   min=0s      med=0s       max=638.38µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=82.36ms  min=2.17ms  med=5.46ms   max=9.2s     p(90)=7.1ms    p(95)=7.79ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=58.23µs  min=14.18µs med=43µs     max=2.22ms   p(90)=79.28µs  p(95)=98.08µs 
     http_req_sending...........: avg=114.77µs min=44.1µs  med=103.47µs max=333.92µs p(90)=169.59µs p(95)=183.23µs
     http_req_tls_handshaking...: avg=257µs    min=0s      med=0s       max=92.52ms  p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=82.19ms  min=2ms     med=5.32ms   max=9.2s     p(90)=6.91ms   p(95)=7.7ms   
     http_reqs..................: 360     0.595442/s
     iteration_duration.........: avg=5.03s    min=4.99s   med=5s       max=9.2s     p(90)=5s       p(95)=5s      
     iterations.................: 120     0.198481/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-02 12:44 UTC, boxhock requested changes

2022-11-02 12:44 UTC, boxhock commented on packages/sources/bank-frick/src/config/index.ts
> +  let privateKey = util.getRequiredEnv('PRIVATE_KEY')
Not a huge deal, but we should probably still include the prefix here.

```suggestion
  let privateKey = util.getRequiredEnv('PRIVATE_KEY', prefix)
```

2022-11-02 16:37 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.4s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 166 kB  276 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=14.14ms  min=155ns   med=369ns    max=5.09s    p(90)=479ns    p(95)=899ns   
     http_req_connecting........: avg=2.37µs   min=0s      med=0s       max=854.48µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=5.29ms   min=2.25ms  med=4.94ms   max=27.63ms  p(90)=6.24ms   p(95)=6.77ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=45.75µs  min=11.87µs med=41.29µs  max=149.03µs p(90)=67.28µs  p(95)=81.43µs 
     http_req_sending...........: avg=124.86µs min=43.43µs med=118.36µs max=279.22µs p(90)=183.27µs p(95)=194.81µs
     http_req_tls_handshaking...: avg=233.59µs min=0s      med=0s       max=84.09ms  p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=5.12ms   min=2.13ms  med=4.78ms   max=27.5ms   p(90)=6.05ms   p(95)=6.62ms  
     http_reqs..................: 360     0.599602/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5.12s    p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199867/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-02 22:03 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for bank-frick failed :warning:</summary>

```
default   [  93% ] 1 VUs  09m19.8s/10m0s

running (09m20.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.2s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-bank-frick-test-payload returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-GBPT PoR returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✗ Group-bank-frick-integration-test returned 200
      ↳  0% — ✓ 0 / ✗ 120

     checks.....................: 0.00%   ✓ 0        ✗ 360
     data_received..............: 164 kB  274 B/s
     data_sent..................: 70 kB   117 B/s
     errors.....................: 100.00% ✓ 360      ✗ 0  
     http_req_blocked...........: avg=529.99µs min=190ns   med=372ns    max=190.62ms p(90)=837ns    p(95)=1.42µs  
     http_req_connecting........: avg=1.78µs   min=0s      med=0s       max=642.61µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=5.47ms   min=2.69ms  med=5.16ms   max=25.65ms  p(90)=7.05ms   p(95)=7.85ms  
   ✗ http_req_failed............: 100.00% ✓ 360      ✗ 0  
     http_req_receiving.........: avg=52.39µs  min=20.26µs med=44.41µs  max=996.66µs p(90)=75.2µs   p(95)=85.28µs 
     http_req_sending...........: avg=120.15µs min=53.86µs med=113.17µs max=228.79µs p(90)=168.06µs p(95)=180.54µs
     http_req_tls_handshaking...: avg=510.16µs min=0s      med=0s       max=183.66ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=5.3ms    min=2.58ms  med=5ms      max=25.46ms  p(90)=6.8ms    p(95)=7.59ms  
     http_reqs..................: 360     0.599796/s
     iteration_duration.........: avg=5s       min=4.99s   med=5s       max=5s       p(90)=5s       p(95)=5s      
     iterations.................: 120     0.199932/s
     vus........................: 1       min=1      max=1
     vus_max....................: 1       min=1      max=1
```
</details>

2022-11-03 19:28 UTC, boxhock approved these changes

2022-11-03 19:35 UTC, merged