New NovaPoshta Adapter 1.0.0
smartcontractkit/external-adapters-js pull request #2294
Opened 2022-11-04 00:08 UTC by alexbakers

## Description

NovaPoshta Adapter for tracking parcels.

## Steps to Test

```bash
$ yarn test packages/sources/novaposhta/test/unit/tracking.test.ts 
 PASS  packages/sources/novaposhta/test/unit/tracking.test.ts

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.672 s
```

```bash
$ yarn test packages/sources/novaposhta/test/integration/tracking.test.ts 
 PASS  packages/sources/novaposhta/test/integration/tracking.test.ts
{"level":"warn","time":1667520302342,"pid":88822,"hostname":"Alex-Baker","msg":"Could not load payload: [{\"instancePath\":\"\",\"schemaPath\":\"#/type\",\"keyword\":\"type\",\"params\":{\"type\":\"object\"},\"message\":\"must be object\"}]"}
{"level":"warn","time":1667520302342,"pid":88822,"hostname":"Alex-Baker","msg":"Falling back to default empty payload"}
{"level":"info","time":1667520302351,"pid":88822,"hostname":"Alex-Baker","msg":"Server listening on http://0.0.0.0:51933!"}

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        2.355 s, estimated 3 s
```

## Quality Assurance

- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [x] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2022-11-07 14:06 UTC, boxhock requested changes
Thanks for opening this PR! Referring to #2293 for the changeset issues

2022-11-07 14:06 UTC, boxhock commented on packages/sources/novaposhta/src/adapter.ts
> +import * as endpoints from './endpoint' // The endpoints must be exported as shown in endpoint/index.ts for README generation.
```suggestion
import * as endpoints from './endpoint'
```

2022-11-07 14:06 UTC, boxhock commented on packages/sources/novaposhta/src/config/index.ts
> +export const NAME = 'NOVAPOSHTA' // This should be filled in with a name corresponding to the data provider using UPPERCASE and _underscores_.
```suggestion
export const NAME = 'NOVAPOSHTA'
```

2022-11-07 14:06 UTC, boxhock commented on packages/sources/novaposhta/src/config/limits.json
> +      "rateLimit1s": 100
This seems quite high. Do you have a link to documentation of these limits?

2022-11-07 14:06 UTC, boxhock commented on packages/sources/novaposhta/src/endpoint/tracking.ts
> +    '}'
We should build this as an object, then turn it into JSON with `JSON.stringify()`

2022-11-07 14:06 UTC, boxhock commented on packages/sources/novaposhta/test-payload.json
> +
```suggestion

```

2022-11-07 14:06 UTC, boxhock commented on packages/sources/novaposhta/test/e2e/README.md
> +Tests that run the adapter and send an end to end request using live API endpoints.
You can remove this file

2022-11-22 00:45 UTC, alexbakers reviewed
@boxhock thank you very much, you showed in great detail what needs to be fixed.
I will take all the changes.
Please, if I merge branches incorrectly, let me know.

2024-08-28 17:22 UTC, mxiao-cll commented
Please re-open if still relevant

2024-08-28 17:22 UTC, closed without merging