add kaiko-test v3 ea
smartcontractkit/external-adapters-js pull request #2331
Opened 2022-11-15 15:48 UTC by karen-stepanyan

2022-11-16 02:53 UTC, alejoberardino requested changes
There's a few requested changes we can tackle, but since we don't support non-batch endpoints right now we won't push this through until we resolve that

2022-11-16 02:53 UTC, alejoberardino commented on packages/sources/kaiko-test/src/config/index.ts
> +export const DEFAULT_API_ENDPOINT = 'https://us.market-api.kaiko.io/v2/data/trades.v1'
Let's not use a separate var for this, it shouldn't be used outside of the adapter index so better to hardcode the value in the adapter obj

2022-11-16 02:53 UTC, alejoberardino commented on packages/sources/kaiko-test/src/endpoint/trades.ts
> +    const sort = data.sort || DEFAULT_SORT
the input parameters have a default value, they should never be undefined so there's no reason to use the defaults here too

2022-11-16 02:53 UTC, alejoberardino commented on packages/sources/kaiko-test/src/config/index.ts
> +export const DEFAULT_API_ENDPOINT = 'https://us.market-api.kaiko.io/v2/data/trades.v1'
Same thing goes for the others actually, they shouldn't be used other places

2022-11-16 02:53 UTC, alejoberardino commented on packages/sources/kaiko-test/src/endpoint/trades.ts
> +  sort?: string
These will always have a value because of the defaults

2022-11-16 02:53 UTC, alejoberardino commented on packages/sources/kaiko-test/src/endpoint/trades.ts
> +const restEndpointTransport = new RestTransport<EndpointTypes>({
Rest transport is going away so we'll block this one until we can either move to a batch endpoint (there seem to be a few options for kaiko) or have support for the more inefficient single requests

2022-11-16 02:53 UTC, alejoberardino commented on packages/sources/kaiko-test/src/endpoint/trades.ts
> +    }
inverses are already calculated by the price constructs, this should not not needed

2023-01-06 18:22 UTC, amit-momin commented on packages/sources/kaiko-test/src/config/index.ts
> +  },
```suggestion
  API_KEY: {
    description: 'API KEY for  KAIKO',
    type: 'string',
    required: true,
    sensitive: true,
  },
```

2023-01-06 18:36 UTC, amit-momin commented on packages/sources/kaiko-test/src/index.ts
> +    API_TIMEOUT: 10000,
Based on Kaiko v2 I think we should set this to 30000
```suggestion
    API_TIMEOUT: 30000,
```

2023-01-12 13:06 UTC, boxhock approved these changes

2023-01-12 13:06 UTC, boxhock commented on packages/sources/kaiko-test/package.json
> +    "@chainlink/external-adapter-framework": "0.15.1",
This EA looks good to me, but let's wait until we have the metrics fix in the EA framework

2023-01-17 18:07 UTC, amit-momin approved these changes

2023-01-17 22:18 UTC, merged