Upgrade cfbenchmarks to v3 framework
smartcontractkit/external-adapters-js pull request #2630
Opened 2023-04-14 17:14 UTC by amit-momin

## Closes [PDI-1954](https://smartcontract-it.atlassian.net/browse/PDI-1954)

## Description

Update `cfbenchmarks` to v3 framework

## Changes

- Swapped v2 version of `cfbenchmarks` with v3
- Updated `token-allocation` adapter list to mark `cfbenchmarks` as v3

## Steps to Test

1. yarn test packages/sources/cfbenchmarks/test

## Quality Assurance

- [X] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [X] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [X] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `adapter-secrets` configuration file or update the [soak testing blacklist](/packages/scripts/src/get-changed-adapters/soakTestBlacklist.ts).
- [X] If a new adapter was made, or a new endpoint was added, update the `test-payload.json` file with relevant requests.
- [X] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [X] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [X] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [X] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2023-04-14 19:36 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for cfbenchmarks failed :warning:</summary>

```
running (09m23.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.6s/10m0s

running (09m24.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.6s/10m0s

running (09m25.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.6s/10m0s

running (09m26.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.6s/10m0s

running (09m27.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.6s/10m0s

running (09m28.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.6s/10m0s

running (09m29.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.6s/10m0s

running (09m30.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.6s/10m0s

running (09m31.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.6s/10m0s

running (09m32.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.6s/10m0s

running (09m33.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.6s/10m0s

running (09m34.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.6s/10m0s

running (09m35.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.6s/10m0s

running (09m36.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.6s/10m0s

running (09m37.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.6s/10m0s

running (09m38.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.6s/10m0s

running (09m39.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.6s/10m0s

running (09m40.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.6s/10m0s

running (09m41.6s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.6s/10m0s

running (09m42.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.6s/10m0s

running (09m43.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.6s/10m0s

running (09m44.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.6s/10m0s

running (09m45.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.6s/10m0s

running (09m46.6s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.6s/10m0s

running (09m47.6s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.6s/10m0s

running (09m48.6s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.6s/10m0s

running (09m49.6s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.6s/10m0s

running (09m50.6s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.6s/10m0s

running (09m51.6s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.6s/10m0s

running (09m52.6s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.6s/10m0s

running (09m53.6s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.6s/10m0s

running (09m54.6s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.6s/10m0s

running (09m55.6s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.6s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.6s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

     ✓ Group-cfbenchmarks-YFI / USD returned 200
     ✓ Group-cfbenchmarks-OXT / USD returned 200
     ✓ Group-cfbenchmarks-EOS / USD returned 200
     ✓ Group-cfbenchmarks-USDT / USD returned 200
     ✗ Group-cfbenchmarks-test-payload-0 returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✓ Group-cfbenchmarks-BAT / USD returned 200
     ✓ Group-cfbenchmarks-BCH / USD returned 200
     ✓ Group-cfbenchmarks-BTC / USD returned 200
     ✓ Group-cfbenchmarks-ETH / USD returned 200

     checks.........................: 88.88% ✓ 960      ✗ 120
     data_received..................: 478 kB 793 B/s
     data_sent......................: 213 kB 354 B/s
     errors.........................: 11.11% ✓ 120      ✗ 960
     http_req_blocked...............: avg=4.63ms   min=116ns   med=257ns    max=5.01s    p(90)=376ns    p(95)=559ns   
     http_req_connecting............: avg=650ns    min=0s      med=0s       max=702.22µs p(90)=0s       p(95)=0s      
   ✗ http_req_duration..............: avg=257.32ms min=3.04ms  med=5.67ms   max=2.23s    p(90)=2.2s     p(95)=2.21s   
       { expected_response:true }...: avg=12.9ms   min=3.04ms  med=5.54ms   max=1.01s    p(90)=7.18ms   p(95)=8.26ms  
   ✗ http_req_failed................: 11.11% ✓ 120      ✗ 960
     http_req_receiving.............: avg=92.73µs  min=11.65µs med=70.71µs  max=4.08ms   p(90)=156.18µs p(95)=195.07µs
     http_req_sending...............: avg=129.7µs  min=25.59µs med=114.48µs max=429.33µs p(90)=241.25µs p(95)=255.91µs
     http_req_tls_handshaking.......: avg=2.77µs   min=0s      med=0s       max=2.99ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=257.1ms  min=2.94ms  med=5.43ms   max=2.23s    p(90)=2.2s     p(95)=2.21s   
     http_reqs......................: 1080   1.793062/s
     iteration_duration.............: avg=5.01s    min=4.99s   med=5s       max=7.24s    p(90)=5s       p(95)=5s      
     iterations.....................: 120    0.199229/s
     vus............................: 1      min=1      max=1
     vus_max........................: 1      min=1      max=1


running (10m02.3s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"crypto","from":"OXT","overrides":{"coingecko":{"OXT":"orchid-protocol"}},"to":"USD"}} response: {"result":0.0903,"data":{"result":0.0903},"timestamps":{"providerDataStreamEstablishedUnixMs":1681500402015,"providerDataReceivedUnixMs":1681500883082,"providerIndicatedTimeUnixMs":1681500883000},"statusCode":200,"meta":{"metrics":{"feedId":"{\"index\":\"oxtusd_rti\"}"}}}
request: {"data":{"endpoint":"crypto","from":"YFI","overrides":{"coingecko":{"YFI":"yearn-finance"},"coinpaprika":{"YFI":"yfi-yearnfinance"}},"to":"USD"}} response: {"result":9217.78,"data":{"result":9217.78},"timestamps":{"providerDataStreamEstablishedUnixMs":1681500402015,"providerDataReceivedUnixMs":1681500883065,"providerIndicatedTimeUnixMs":1681500883000},"statusCode":200,"meta":{"metrics":{"feedId":"{\"index\":\"yfiusd_rti\"}"}}}
request: {"data":{"endpoint":"crypto","from":"YFI","overrides":{"coingecko":{"YFI":"yearn-finance"},"coinpaprika":{"YFI":"yfi-yearnfinance"}},"to":"USD"}} response: {"result":9217.69,"data":{"result":9217.69},"timestamp [...]

2023-04-14 19:36 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for coinmarketcap failed :warning:</summary>

```

running (09m52.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.6s/10m0s

running (09m53.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.6s/10m0s

running (09m54.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.6s/10m0s

running (09m55.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 29 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.1s), 0/1 VUs, 30 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinmarketcap-AMPL / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AAVE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BADGER / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AAVE / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-CREAM / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BNT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BTC / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-COMP / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ATOM / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BNB / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BAND / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ATOM / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-APE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ADA / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-1INCH / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BAND / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BNB / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BORING / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ALBT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BNT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-CELO / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ALCX / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-CEL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ALCX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ALPHA / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-C98 / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ARPA / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BUSD / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AVAX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BAT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-APE / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BAL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AXS / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-1INCH / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-CAKE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BIT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ALUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AMP / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AUDIO / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-AMPL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ANT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BOND / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BTC / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-BADGER / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-COMP / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ADX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-ANKR / USD returned 200
      ↳  0% — ✓ 0 / ✗ 30
     ✗ Group-coinmarketcap-CRO / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 30

     checks.....................: 0.00%   ✓ 0        ✗ 1500
     data_received..............: 646 kB  1.1 kB/s
     data_sent..................: 208 kB  346 B/s
     errors.....................: 100.00% ✓ 1500     ✗ 0   
     http_req_blocked...........: avg=62.98µs min=94ns    med=235ns   max=93.91ms  p(90)=318ns    p(95)=378ns   
     http_req_connecting........: avg=425ns   min=0s      med=0s      max=638.12µs p(90)=0s       p(95)=0s      
   ✗ http_req_duration..........: avg=2.22s   min=2.21s   med=2.22s   max=2.25s    p(90)=2.22s    p(95)=2.22s   
   ✗ http_req_failed............: 100.00% ✓ 1500     ✗ 0   
     http_req_receiving.........: avg=70.06µs min=13.67µs med=53.98µs max=1.14ms   p(90)=123.91µs p(95)=164.13µs
     http_req_sending...........: avg=58.6µs  min=9.37µs  med=47µs    max=270.82µs p(90)=95.82µs  p(95)=147.63µs
     http_req_tls_handshaking...: avg=2.01µs  min=0s      med=0s      max=3.02ms   p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=2.22s   min=2.21s   med=2.22s   max=2.25s    p(90)=2.22s    p(95)=2.22s   
     http_reqs..................: 1500    2.499615/s
     iteration_duration.........: avg=20s     min=19.98s  med=19.99s  max=20.12s   p(90)=20s      p(95)=20.02s  
     iterations.................: 30      0.049992/s
     vus........................: 1       min=0      max=1 
     vus_max....................: 1       min=0      max=1 


running (10m00.1s), 0/1 VUs, 30 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ATOM","to":"ETH"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the relevant channels."}}
request: {"data":{"from":"BAL","to":"USD"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the relevant channels."}}
request: {"data":{"from":"AAVE","to":"ETH"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the relevant channels."}}
request: {"data":{"from":"CREAM","overrides":{"coinpaprika":{"CREAM":"cream-cream"}},"to":"ETH"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the re [...]

2023-04-14 19:36 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  96% ] 1 VUs  09m37.7s/10m0s

running (09m38.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.7s/10m0s

running (09m39.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.7s/10m0s

running (09m40.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.7s/10m0s

running (09m41.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.7s/10m0s

running (09m42.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.7s/10m0s

running (09m43.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.7s/10m0s

running (09m44.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.7s/10m0s

running (09m45.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.7s/10m0s

running (09m46.7s), 1/1 VUs, 120 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.7s/10m0s

running (09m47.7s), 1/1 VUs, 120 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.7s/10m0s

running (09m48.7s), 1/1 VUs, 120 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.7s/10m0s

running (09m49.7s), 1/1 VUs, 120 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.7s/10m0s

running (09m50.7s), 1/1 VUs, 120 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.7s/10m0s

running (09m51.7s), 1/1 VUs, 121 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.7s), 1/1 VUs, 121 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 121 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 121 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 121 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 122 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 122 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 122 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 122 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 122 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.0s), 0/1 VUs, 123 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coinpaprika-BNT / USD returned 200
     ✓ Group-coinpaprika-ADX / USD returned 200
     ✓ Group-coinpaprika-ALCX / USD returned 200
     ✓ Group-coinpaprika-BAT / USD returned 200
     ✓ Group-coinpaprika-BIT / USD returned 200
     ✓ Group-coinpaprika-ATOM / USD returned 200
     ✓ Group-coinpaprika-C98 / USD returned 200
     ✓ Group-coinpaprika-BNB / USD returned 200
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  99% — ✓ 120 / ✗ 1
     ✓ Group-coinpaprika-BADGER / USD returned 200
     ✓ Group-coinpaprika-BAND / USD returned 200
     ✓ Group-coinpaprika-CRO / USD returned 200
     ✓ Group-coinpaprika-BCH / USD returned 200
     ✓ Group-coinpaprika-COMP / USD returned 200
     ✓ Group-coinpaprika-AAVE / USD returned 200
     ✓ Group-coinpaprika-AMPL / ETH returned 200
     ✓ Group-coinpaprika-CEL / ETH returned 200
     ✓ Group-coinpaprika-ARPA / USD returned 200
     ✓ Group-coinpaprika-BAND / ETH returned 200
     ✓ Group-coinpaprika-CRV / ETH returned 200
     ✓ Group-coinpaprika-ANT / ETH returned 200
     ✓ Group-coinpaprika-BAT / ETH returned 200
     ✓ Group-coinpaprika-AUDIO / USD returned 200
     ✓ Group-coinpaprika-BUSD / USD returned 200
     ✓ Group-coinpaprika-CRO / ETH returned 200
     ✓ Group-coinpaprika-BAL / USD returned 200
     ✓ Group-coinpaprika-ADA / USD returned 200
     ✓ Group-coinpaprika-AXS / ETH returned 200
     ✓ Group-coinpaprika-ATOM / ETH returned 200
     ✓ Group-coinpaprika-COMP / ETH returned 200
     ✓ Group-coinpaprika-BNT / ETH returned 200
     ✓ Group-coinpaprika-AVAX / USD returned 200
     ✓ Group-coinpaprika-ALBT / USD returned 200
     ✓ Group-coinpaprika-ANKR / USD returned 200
     ✓ Group-coinpaprika-ALCX / ETH returned 200
     ✓ Group-coinpaprika-BTC / ETH returned 200
     ✓ Group-coinpaprika-1INCH / ETH returned 200
     ✓ Group-coinpaprika-AMP / USD returned 200
     ✓ Group-coinpaprika-BAL / ETH returned 200
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 122 / ✗ 1
     ✓ Group-coinpaprika-CELO / ETH returned 200
     ✓ Group-coinpaprika-BUSD / ETH returned 200
     ✓ Group-coinpaprika-1INCH / USD returned 200
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  99% — ✓ 120 / ✗ 1
     ✓ Group-coinpaprika-BNB / ETH returned 200
     ✓ Group-coinpaprika-BORING / USD returned 200
     ✓ Group-coinpaprika-AAVE / ETH returned 200
     ✓ Group-coinpaprika-CREAM / ETH returned 200
     ✓ Group-coinpaprika-APE / USD returned 200
     ✓ Group-coinpaprika-ALUSD / USD returned 200

     checks.........................: 99.95% ✓ 6055      ✗ 3   
     data_received..................: 1.8 MB 3.0 kB/s
     data_sent......................: 851 kB 1.4 kB/s
     errors.........................: 0.00%  ✓ 0         ✗ 6055
     http_req_blocked...............: avg=1.59µs  min=98ns     med=229ns   max=7.57ms   p(90)=297ns    p(95)=363ns   
     http_req_connecting............: avg=104ns   min=0s       med=0s      max=640.71µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=17.34ms min=2.17ms   med=15.08ms max=348.61ms p(90)=22.61ms  p(95)=27.02ms 
       { expected_response:true }...: avg=17.33ms min=5.66ms   med=15.08ms max=348.61ms p(90)=22.6ms   p(95)=27.01ms 
   ✓ http_req_failed................: 0.04%  ✓ 3         ✗ 6147
     http_req_receiving.............: avg=91.07µs min=9.63µs   med=59.27µs max=66.13ms  p(90)=149.53µs p(95)=231.12µs
     http_req_sending...............: avg=62.03µs min=17.92µs  med=42.3µs  max=685.56µs p(90)=118.38µs p(95)=200.98µs
     http_req_tls_handshaking.......: avg=465ns   min=0s       med=0s      max=2.86ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=17.19ms min=2.09ms   med=14.96ms max=348.47ms p(90)=22.42ms  p(95)=26.83ms 
     http_reqs......................: 6150   10.233027/s
     iteration_duration.............: avg=4.88s   min=156.32ms med=5s      max=5s       p(90)=5s       p(95)=5s      
     iterations.....................: 123    0.204661/s
     vus............................: 1      min=0       max=1 
     vus_max........................: 1      min=0       max=1 


running (10m01.0s), 0/1 VUs, 123 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ALCX","to":"USD"}} response: {"result":20.479241824329826,"maxAge":90000,"statusCode":200,"data":{"result":20.479241824329826,"statusCode":200},"metricsMeta":{"feedId":"ALCX/USD"}}
request: {"data":{"from":"BAT","to":"ETH"}} response: {"result":0.00013656907996145896,"maxAge":90000,"statusCode":200,"data":{"result":0.00013656907996145896,"statusCode":200},"metricsMeta":{"feedId":"BAT/ETH"}}
request: {"data":{"from":"CELO","overrides":{"coinpaprika":{"CELO":"celo-celo"}},"to":"ETH"}} response: {"result":0.0003353923441151532,"maxAge":90000,"statusCode":200,"data":{"result":0.0003353923441151532,"statusCode":200},"metricsMeta":{ [...]

2023-04-14 19:36 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for coingecko failed :warning:</summary>

```
running (10m02.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m05.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m06.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m07.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m08.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m09.7s), 1/1 VUs, 28 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m09.9s), 0/1 VUs, 29 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coingecko-AMPL / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-BOND / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-AAVE / ETH returned 200
      ↳  71% — ✓ 20 / ✗ 8
     ✗ Group-coingecko-BNT / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-ATOM / USD returned 200
      ↳  53% — ✓ 15 / ✗ 13
     ✗ Group-coingecko-CBETH / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-1INCH / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-ANT / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-C98 / USD returned 200
      ↳  53% — ✓ 15 / ✗ 13
     ✗ Group-coingecko-AXS / ETH returned 200
      ↳  57% — ✓ 16 / ✗ 12
     ✗ Group-coingecko-BNB / USD returned 200
      ↳  57% — ✓ 16 / ✗ 12
     ✗ Group-coingecko-ALBT / USD returned 200
      ↳  57% — ✓ 16 / ✗ 12
     ✗ Group-coingecko-AAVE / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-AVAX / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-ANKR / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-BAT / ETH returned 200
      ↳  65% — ✓ 19 / ✗ 10
     ✗ Group-coingecko-COMP / ETH returned 200
      ↳  67% — ✓ 19 / ✗ 9
     ✗ Group-coingecko-BADGER / ETH returned 200
      ↳  60% — ✓ 17 / ✗ 11
     ✗ Group-coingecko-BTC / USD returned 200
      ↳  60% — ✓ 17 / ✗ 11
     ✗ Group-coingecko-BAND / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-CBETH / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-AMP / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-BAL / ETH returned 200
      ↳  68% — ✓ 20 / ✗ 9
     ✗ Group-coingecko-ALUSD / USD returned 200
      ↳  55% — ✓ 16 / ✗ 13
     ✗ Group-coingecko-BNB / ETH returned 200
      ↳  53% — ✓ 15 / ✗ 13
     ✗ Group-coingecko-ALCX / USD returned 200
      ↳  55% — ✓ 16 / ✗ 13
     ✗ Group-coingecko-BADGER / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-APE / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-ADA / USD returned 200
      ↳  64% — ✓ 18 / ✗ 10
     ✗ Group-coingecko-ALCX / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-ATOM / ETH returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-ADX / USD returned 200
      ↳  60% — ✓ 17 / ✗ 11
     ✗ Group-coingecko-COMP / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-BCH / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-BORING / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-BAT / USD returned 200
      ↳  57% — ✓ 16 / ✗ 12
     ✗ Group-coingecko-BTC / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-1INCH / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-BAND / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-BUSD / ETH returned 200
      ↳  53% — ✓ 15 / ✗ 13
     ✗ Group-coingecko-CELO / ETH returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-ARPA / USD returned 200
      ↳  55% — ✓ 16 / ✗ 13
     ✗ Group-coingecko-BUSD / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-AMPL / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-ALPHA / ETH returned 200
      ↳  55% — ✓ 16 / ✗ 13
     ✗ Group-coingecko-APE / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-CAKE / USD returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-CEL / ETH returned 200
      ↳  58% — ✓ 17 / ✗ 12
     ✗ Group-coingecko-AUDIO / USD returned 200
      ↳  62% — ✓ 18 / ✗ 11
     ✗ Group-coingecko-BNT / ETH returned 200
      ↳  55% — ✓ 16 / ✗ 13

     checks.........................: 59.40% ✓ 853      ✗ 583
     data_received..................: 558 kB 914 B/s
     data_sent......................: 207 kB 340 B/s
     errors.........................: 40.55% ✓ 582      ✗ 853
     http_req_blocked...............: avg=10.7µs   min=99ns    med=261ns   max=15.12ms  p(90)=343ns    p(95)=380ns   
     http_req_connecting............: avg=162ns    min=0s      med=0s      max=234.9µs  p(90)=0s       p(95)=0s      
   ✗ http_req_duration..............: avg=2.36s    min=2.1ms   med=2.58s   max=3.15s    p(90)=2.67s    p(95)=2.7s    
       { expected_response:true }...: avg=2.31s    min=5.49ms  med=2.64s   max=3.15s    p(90)=2.69s    p(95)=2.84s   
   ✗ http_req_failed................: 40.48% ✓ 587      ✗ 863
     http_req_receiving.............: avg=116.42µs min=15.54µs med=63.45µs max=16.05ms  p(90)=251.43µs p(95)=268.25µs
     http_req_sending...............: avg=67.18µs  min=12.39µs med=53.44µs max=603.41µs p(90)=95.9µs   p(95)=162.9µs 
     http_req_tls_handshaking.......: avg=2.37µs   min=0s      med=0s      max=3.44ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=2.36s    min=1.97ms  med=2.58s   max=3.15s    p(90)=2.67s    p(95)=2.7s    
     http_reqs......................: 1450   2.377423/s
     iteration_duration.............: avg=21.03s   min=5s      med=21.19s  max=24.1s    p(90)=23.36s   p(95)=23.57s  
     iterations.....................: 29     0.047548/s
     vus............................: 1      min=0      max=1
     vus_max........................: 1      min=0      max=1


running (10m09.9s), 0/1 VUs, 29 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 3, applied: 3</summary>

```
Applied:
Assertion applied: {"request":{"data":{"from":"BADGER","to":"ETH"}},"expectedResponse":{"result":{"minPrecision":12}}}
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}
Assertion applied: {"request":{},"expectedResponse":{"result":{"minPrecision":10}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ALUSD","overrides":{"coinpaprika":{"ALUSD":"alusd-alchemixusd"}},"to":"USD"}} response: {"jobRunID":"1","status":"errored","statusCode":200,"providerStatusCode":401,"error":{"name":"AdapterError","message":"Request failed with status code 401","url":"https:/pro-api.coingecko.com/api/v3/simple/price","feedID":"ALUSD/USD"}}
request: {"data":{"from":"APE","to":"USD"}} response: {"jobRunID":"1","status":"errored","statusCode":200,"providerStatusCode":401,"error":{"name":"AdapterError","message":"Request failed with status code 401","url":"https:/pro-api.coingecko.com/api/v3/simple/price","feedID":"APE/USD"}}
request: {"data":{"from":"ALCX","to":"USD"}} response: {"jobRunID":"1","status":"errored","statusCode":200,"providerStatusCode":401,"error":{"name":"AdapterError","message":"Request failed with status code 401","url":"https:/pro-api.coingecko.com/api/v3/simple/price","feedID":"ALCX/USD"}}
request: {"data":{"from":"AUDIO","to":"USD"}} response: {"jobRunID":"1","status":"errored","statusCode":200,"providerStatusCode":401,"error":{"name":"AdapterError","message":"Request f [...]

2023-04-14 19:36 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for tiingo succeeded</summary>

```
default   [  97% ] 1 VUs  09m42.7s/10m0s

running (09m43.7s), 1/1 VUs, 134 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.7s/10m0s

running (09m44.7s), 1/1 VUs, 134 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.7s/10m0s

running (09m45.7s), 1/1 VUs, 134 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.7s/10m0s

running (09m46.7s), 1/1 VUs, 134 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.7s/10m0s

running (09m47.7s), 1/1 VUs, 135 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.7s/10m0s

running (09m48.7s), 1/1 VUs, 135 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.7s/10m0s

running (09m49.7s), 1/1 VUs, 135 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.7s/10m0s

running (09m50.7s), 1/1 VUs, 135 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.7s/10m0s

running (09m51.7s), 1/1 VUs, 135 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.7s), 1/1 VUs, 136 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 136 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 136 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 136 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 136 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 137 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 137 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 137 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 137 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 137 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.1s), 0/1 VUs, 138 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-tiingo-BORING / USD returned 200
      ↳  99% — ✓ 127 / ✗ 1
     ✓ Group-tiingo-ATOM / ETH returned 200
     ✓ Group-tiingo-1INCH / ETH returned 200
     ✗ Group-tiingo-AXS / ETH returned 200
      ↳  99% — ✓ 131 / ✗ 1
     ✓ Group-tiingo-ERN / USD returned 200
     ✓ Group-tiingo-CAKE / USD returned 200
     ✗ Group-tiingo-DYDX / USD returned 200
      ↳  99% — ✓ 128 / ✗ 1
     ✓ Group-tiingo-DOT / USD returned 200
     ✗ Group-tiingo-BNT / USD returned 200
      ↳  99% — ✓ 128 / ✗ 1
     ✓ Group-tiingo-ALCX / USD returned 200
     ✓ Group-tiingo-CBETH / ETH returned 200
     ✗ Group-tiingo-BTC / USD returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✓ Group-tiingo-DODO / USD returned 200
     ✓ Group-tiingo-AUDIO / USD returned 200
     ✓ Group-tiingo-DOGE / USD returned 200
     ✓ Group-tiingo-CVX / USD returned 200
     ✓ Group-tiingo-CTX / USD returned 200
     ✓ Group-tiingo-CELO / ETH returned 200
     ✗ Group-tiingo-BNT / ETH returned 200
      ↳  99% — ✓ 131 / ✗ 1
     ✓ Group-tiingo-BAT / USD returned 200
     ✗ Group-tiingo-ATOM / USD returned 200
      ↳  99% — ✓ 129 / ✗ 1
     ✓ Group-tiingo-CVX / ETH returned 200
     ✗ Group-tiingo-ALPHA / ETH returned 200
      ↳  98% — ✓ 131 / ✗ 2
     ✗ Group-tiingo-BAL / USD returned 200
      ↳  98% — ✓ 131 / ✗ 2
     ✓ Group-tiingo-EOS / USD returned 200
     ✗ Group-tiingo-DAI / ETH returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✓ Group-tiingo-AVAX / USD returned 200
     ✓ Group-tiingo-ALBT / USD returned 200
     ✓ Group-tiingo-ALUSD / USD returned 200
     ✓ Group-tiingo-CREAM / ETH returned 200
     ✓ Group-tiingo-C98 / USD returned 200
     ✗ Group-tiingo-CBETH / USD returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✗ Group-tiingo-CTSI / ETH returned 200
      ↳  99% — ✓ 130 / ✗ 1
     ✓ Group-tiingo-APE / USD returned 200
     ✓ Group-tiingo-ETH / BTC returned 200
     ✓ Group-tiingo-ARPA / USD returned 200
     ✗ Group-tiingo-ALCX / ETH returned 200
      ↳  98% — ✓ 126 / ✗ 2
     ✓ Group-tiingo-BAND / ETH returned 200
     ✓ Group-tiingo-DAI / USD returned 200
     ✗ Group-tiingo-APE / ETH returned 200
      ↳  99% — ✓ 130 / ✗ 1
     ✓ Group-tiingo-AMPL / USD returned 200
     ✓ Group-tiingo-BADGER / USD returned 200
     ✓ Group-tiingo-ENS / USD returned 200
     ✓ Group-tiingo-AMPL / ETH returned 200
     ✗ Group-tiingo-CSPR / USD returned 200
      ↳  99% — ✓ 126 / ✗ 1
     ✓ Group-tiingo-ENJ / USD returned 200
     ✓ Group-tiingo-BOND / ETH returned 200
     ✓ Group-tiingo-1INCH / USD returned 200
     ✓ Group-tiingo-BCH / USD returned 200
     ✓ Group-tiingo-BIT / USD returned 200

     checks.........................: 99.72% ✓ 6490      ✗ 18  
     data_received..................: 2.1 MB 3.5 kB/s
     data_sent......................: 1.1 MB 1.7 kB/s
     errors.........................: 0.00%  ✓ 0         ✗ 6490
     http_req_blocked...............: avg=13.25µs  min=98ns    med=216ns   max=89.26ms  p(90)=296ns    p(95)=347ns   
     http_req_connecting............: avg=135ns    min=0s      med=0s      max=934.02µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=12.07ms  min=1.85ms  med=11.39ms max=70.7ms   p(90)=15.55ms  p(95)=17.44ms 
       { expected_response:true }...: avg=12.1ms   min=4.37ms  med=11.4ms  max=70.7ms   p(90)=15.56ms  p(95)=17.46ms 
   ✓ http_req_failed................: 0.42%  ✓ 29        ✗ 6871
     http_req_receiving.............: avg=110.54µs min=11.81µs med=49.92µs max=50.95ms  p(90)=110.97µs p(95)=146.78µs
     http_req_sending...............: avg=59.86µs  min=22.93µs med=40.95µs max=493.31µs p(90)=112.74µs p(95)=198.07µs
     http_req_tls_handshaking.......: avg=12.1µs   min=0s      med=0s      max=83.53ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=11.9ms   min=1.78ms  med=11.27ms max=57.35ms  p(90)=15.33ms  p(95)=17.3ms  
     http_reqs......................: 6900   11.460184/s
     iteration_duration.............: avg=4.36s    min=95.96ms med=5s      max=5s       p(90)=5s       p(95)=5s      
     iterations.....................: 138    0.229204/s
     vus............................: 1      min=0       max=1 
     vus_max........................: 1      min=0       max=1 


running (10m02.1s), 0/1 VUs, 138 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ATOM","to":"USD"}} response: {"result":12.348108333001635,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":12.348108333001635},"metricsMeta":{"feedId":"ATOM/USD"}}
request: {"data":{"from":"CBETH","overrides":{"coingecko":{"CBETH":"coinbase-wrapped-staked-eth"}},"to":"USD"}} response: {"result":2136.0489928521506,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":2136.0489928521506},"metricsMeta":{"feedId":"CBETH/USD"}}
request: {"data":{"from":"BOND","includes":["WETH"],"to":"ETH"}} response: {"result":0.002118022767234375,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":0.002118022767234375},"metricsMeta":{"feedId":"BOND/ETH"}}
request: {"data":{"from":"CTX","overrides":{"coingecko":{"CTX":"cryptex-finance"},"coinpaprika":{"CTX":"ctx-cryptex"},"nomics":{"CTX":"CTX2"}},"to":"USD"}} response: {"result":1.8892722354370166,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":1.8892722354370166},"metricsMeta":{"feedId": [...]

2023-04-16 19:34 UTC, alejoberardino requested changes

2023-04-16 19:34 UTC, alejoberardino commented on packages/sources/cfbenchmarks/test/unit/adapter.test.ts
> -})
We should keep these tests

2023-04-17 15:09 UTC, alejoberardino approved these changes

2023-04-17 15:23 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for cfbenchmarks failed :warning:</summary>

```
running (09m25.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.7s/10m0s

running (09m26.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.7s/10m0s

running (09m27.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.7s/10m0s

running (09m28.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.7s/10m0s

running (09m29.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.7s/10m0s

running (09m30.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.7s/10m0s

running (09m31.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.7s/10m0s

running (09m32.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.7s/10m0s

running (09m33.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.7s/10m0s

running (09m34.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.7s/10m0s

running (09m35.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.7s/10m0s

running (09m36.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.7s/10m0s

running (09m37.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.7s/10m0s

running (09m38.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.7s/10m0s

running (09m39.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.7s/10m0s

running (09m40.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.7s/10m0s

running (09m41.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.7s/10m0s

running (09m42.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.7s/10m0s

running (09m43.7s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.7s/10m0s

running (09m44.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.7s/10m0s

running (09m45.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.7s/10m0s

running (09m46.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.7s/10m0s

running (09m47.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.7s/10m0s

running (09m48.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.7s/10m0s

running (09m49.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.7s/10m0s

running (09m50.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.7s/10m0s

running (09m51.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

     ✓ Group-cfbenchmarks-BCH / USD returned 200
     ✓ Group-cfbenchmarks-OXT / USD returned 200
     ✓ Group-cfbenchmarks-EOS / USD returned 200
     ✗ Group-cfbenchmarks-test-payload-0 returned 200
      ↳  0% — ✓ 0 / ✗ 120
     ✓ Group-cfbenchmarks-BAT / USD returned 200
     ✓ Group-cfbenchmarks-USDT / USD returned 200
     ✓ Group-cfbenchmarks-BTC / USD returned 200
     ✓ Group-cfbenchmarks-ETH / USD returned 200
     ✓ Group-cfbenchmarks-YFI / USD returned 200

     checks.........................: 88.88% ✓ 960      ✗ 120
     data_received..................: 478 kB 791 B/s
     data_sent......................: 213 kB 353 B/s
     errors.........................: 11.11% ✓ 120      ✗ 960
     http_req_blocked...............: avg=4.63ms   min=102ns   med=248ns    max=5.01s    p(90)=379ns    p(95)=670ns   
     http_req_connecting............: avg=358ns    min=0s      med=0s       max=386.87µs p(90)=0s       p(95)=0s      
   ✗ http_req_duration..............: avg=260.42ms min=2.13ms  med=4.9ms    max=2.22s    p(90)=2.21s    p(95)=2.21s   
       { expected_response:true }...: avg=15.81ms  min=2.13ms  med=4.74ms   max=1.42s    p(90)=6.57ms   p(95)=7.72ms  
   ✗ http_req_failed................: 11.11% ✓ 120      ✗ 960
     http_req_receiving.............: avg=84.57µs  min=13.96µs med=63.53µs  max=1.36ms   p(90)=152.14µs p(95)=243.64µs
     http_req_sending...............: avg=121.23µs min=24.06µs med=104.54µs max=606.89µs p(90)=226.87µs p(95)=247.03µs
     http_req_tls_handshaking.......: avg=3.17µs   min=0s      med=0s       max=3.42ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=260.22ms min=2.06ms  med=4.68ms   max=2.22s    p(90)=2.21s    p(95)=2.21s   
     http_reqs......................: 1080   1.788589/s
     iteration_duration.............: avg=5.03s    min=4.99s   med=5s       max=8.75s    p(90)=5s       p(95)=5s      
     iterations.....................: 120    0.198732/s
     vus............................: 1      min=1      max=1
     vus_max........................: 1      min=1      max=1


running (10m03.8s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"crypto","from":"BAT","overrides":{"coingecko":{"BAT":"basic-attention-token"},"coinpaprika":{"BAT":"bat-basic-attention-token"}},"to":"USD"}} response: {"result":0.2824,"data":{"result":0.2824},"timestamps":{"providerDataStreamEstablishedUnixMs":1681744427026,"providerDataReceivedUnixMs":1681744909083,"providerIndicatedTimeUnixMs":1681744909000},"statusCode":200,"meta":{"metrics":{"feedId":"{\"index\":\"batusd_rti\"}"}}}
request: {"data":{"endpoint":"crypto","from":"BCH","overrides":{"coingecko":{"BCH":"bitcoin-cash"},"coinpaprika":{"BCH":"bch-bitcoin-cash"}},"to":"USD"}} response: {"result":131.49,"data":{"result":131.49},"timestamps":{"providerDataStreamEstablishedUnixMs":1681744427026,"providerDataReceivedUnixMs":1681744909083,"providerIndicatedTimeUnixMs":1681744909000},"statusCode":200,"meta":{"metrics":{"feedId":"{\"index\":\"bchusd_rti\"}"}}}
request: {"data":{"endpoint":"crypto","from":"BTC","overrides":{"coingecko":{"BTC":"bitcoin"}},"to":"USD"}} response: {"result":29422.65,"data":{"result":29422.65},"timestamps":{"provi [...]

2023-04-17 15:23 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for coingecko failed :warning:</summary>

```

running (09m57.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 117 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.9s), 0/1 VUs, 118 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coingecko-BAT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BCH / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ALUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BAL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ADX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ADA / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ALCX / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ALCX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BNB / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-APE / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-APE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-1INCH / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BUSD / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AVAX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-CAKE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BAND / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AMPL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BADGER / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BNT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-1INCH / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AMP / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-CBETH / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BAT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AUDIO / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AXS / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AAVE / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AMPL / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BNB / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BADGER / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BTC / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BORING / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BAND / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-AAVE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ALBT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-COMP / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-CEL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-COMP / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ANT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BTC / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BOND / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-CBETH / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ATOM / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ANKR / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ATOM / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ALPHA / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-C98 / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-BNT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-ARPA / USD returned 200
      ↳  0% — ✓ 0 / ✗ 118
     ✗ Group-coingecko-CELO / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 118

     checks.....................: 0.00%   ✓ 0        ✗ 5900
     data_received..............: 2.5 MB  4.2 kB/s
     data_sent..................: 834 kB  1.4 kB/s
     errors.....................: 100.00% ✓ 5900     ✗ 0   
     http_req_blocked...........: avg=17.27µs min=91ns    med=180ns   max=100.26ms p(90)=263ns    p(95)=314ns   
     http_req_connecting........: avg=48ns    min=0s      med=0s      max=284.77µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..........: avg=22.85ms min=2.08ms  med=4.01ms  max=2.23s    p(90)=5.9ms    p(95)=7.12ms  
   ✗ http_req_failed............: 100.00% ✓ 5900     ✗ 0   
     http_req_receiving.........: avg=86.91µs min=10.54µs med=50.95µs max=68.87ms  p(90)=121.93µs p(95)=152.83µs
     http_req_sending...........: avg=52.57µs min=10.75µs med=35.24µs max=527.04µs p(90)=98.16µs  p(95)=182.4µs 
     http_req_tls_handshaking...: avg=14.91µs min=0s      med=0s      max=87.98ms  p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=22.71ms min=2.01ms  med=3.89ms  max=2.23s    p(90)=5.75ms   p(95)=6.95ms  
     http_reqs..................: 5900    9.753458/s
     iteration_duration.........: avg=5.12s   min=4.99s   med=5s      max=19.84s   p(90)=5s       p(95)=5s      
     iterations.................: 118     0.195069/s
     vus........................: 1       min=0      max=1 
     vus_max....................: 1       min=0      max=1 


running (10m04.9s), 0/1 VUs, 118 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 3, applied: 3</summary>

```
Applied:
Assertion applied: {"request":{"data":{"from":"BADGER","to":"ETH"}},"expectedResponse":{"result":{"minPrecision":12}}}
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}
Assertion applied: {"request":{},"expectedResponse":{"result":{"minPrecision":10}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"AXS","overrides":{"nomics":{"AXS":"axs2"}},"to":"ETH"}} response: {"errorMessage":"Provider request failed with status undefined: \"[object Object]\"","statusCode":502,"timestamps":{"providerDataRequestedUnixMs":1681745007129,"providerDataReceivedUnixMs":1681745007377},"meta":{"metrics":{"feedId":"{\"base\":\"axie-infinity\",\"quote\":\"eth\"}"}}}
request: {"data":{"from":"1INCH","to":"ETH"}} response: {"errorMessage":"Provider request failed with status undefined: \"[object Object]\"","statusCode":502,"timestamps":{"providerDataRequestedUnixMs":1681745007129,"providerDataReceivedUnixMs":1681745007377},"meta":{"metrics":{"feedId":"{\"base\":\"1inch\",\"quote\":\"eth\"}"}}}
request: {"data":{"from":"BAL","to":"ETH"}} response: {"errorMessage":"Provider request failed with status undefined: \"[object Object]\"","statusCode":502,"timestamps":{"providerDataRequestedUnixMs":1681745007129,"providerDataReceivedUnixMs":1681745007377},"meta":{"metrics":{"feedId":"{\"base\":\"balancer\",\"quote\":\"eth\"}"}}}
request: {"data":{"from":"ALCX","to":"ETH"}} response: {"errorMessage":"Provider request failed with status undefined: \"[object Object]\"","statusCode":502,"timestamps":{"providerDataRequestedUnixMs":1681745007129,"providerDataReceivedUnixMs":1681745007377} [...]

2023-04-17 15:23 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for coinpaprika failed :warning:</summary>

```
running (09m54.5s), 1/1 VUs, 570 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.5s/10m0s

running (09m55.5s), 1/1 VUs, 570 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.5s/10m0s

running (09m56.5s), 1/1 VUs, 572 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.5s/10m0s

running (09m57.5s), 1/1 VUs, 572 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.5s/10m0s

running (09m58.5s), 1/1 VUs, 572 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.5s/10m0s

running (09m59.5s), 1/1 VUs, 572 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.5s/10m0s

running (10m00.5s), 1/1 VUs, 572 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.5s), 0/1 VUs, 573 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m01.5s), 0/1 VUs, 573 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  93% — ✓ 123 / ✗ 8
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  94% — ✓ 124 / ✗ 7
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  92% — ✓ 123 / ✗ 10
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  92% — ✓ 123 / ✗ 10
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  93% — ✓ 122 / ✗ 9
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  94% — ✓ 124 / ✗ 7
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  94% — ✓ 119 / ✗ 7
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  89% — ✓ 122 / ✗ 15
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  97% — ✓ 123 / ✗ 3
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  93% — ✓ 123 / ✗ 9
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  93% — ✓ 123 / ✗ 9
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  93% — ✓ 122 / ✗ 8
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  90% — ✓ 123 / ✗ 13
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  93% — ✓ 124 / ✗ 9
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  92% — ✓ 120 / ✗ 10
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  92% — ✓ 123 / ✗ 10
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  96% — ✓ 123 / ✗ 5
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  93% — ✓ 122 / ✗ 9
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  96% — ✓ 120 / ✗ 5
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  91% — ✓ 123 / ✗ 12
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  92% — ✓ 120 / ✗ 10
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  94% — ✓ 126 / ✗ 7
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  90% — ✓ 120 / ✗ 13
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  95% — ✓ 122 / ✗ 6
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  89% — ✓ 125 / ✗ 15
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  96% — ✓ 122 / ✗ 4
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  89% — ✓ 124 / ✗ 15
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  94% — ✓ 120 / ✗ 7
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  93% — ✓ 121 / ✗ 8
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  90% — ✓ 121 / ✗ 13
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  93% — ✓ 123 / ✗ 8
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  90% — ✓ 121 / ✗ 13
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  88% — ✓ 119 / ✗ 15
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  94% — ✓ 120 / ✗ 7
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  93% — ✓ 122 / ✗ 9
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  91% — ✓ 124 / ✗ 12
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  93% — ✓ 125 / ✗ 8
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  91% — ✓ 123 / ✗ 12
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  93% — ✓ 122 / ✗ 9
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  96% — ✓ 122 / ✗ 5
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  92% — ✓ 119 / ✗ 10
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  92% — ✓ 120 / ✗ 10
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  93% — ✓ 126 / ✗ 9
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  97% — ✓ 119 / ✗ 3
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  91% — ✓ 124 / ✗ 12
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  95% — ✓ 124 / ✗ 6
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 125 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  91% — ✓ 124 / ✗ 11
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  90% — ✓ 122 / ✗ 13
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  91% — ✓ 122 / ✗ 12

     checks.........................: 93.01% ✓ 6116      ✗ 459 
     data_received..................: 9.0 MB 15 kB/s
     data_sent......................: 4.0 MB 6.6 kB/s
     errors.........................: 0.00%  ✓ 0         ✗ 6116
     http_req_blocked...............: avg=4.06µs   min=91ns     med=182ns   max=96.26ms  p(90)=260ns    p(95)=303ns   
     http_req_connecting............: avg=70ns     min=0s       med=0s      max=899.83µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=10.35ms  min=562.69µs med=2.19ms  max=1.88s    p(90)=17.26ms  p(95)=42.02ms 
       { expected_response:true }...: avg=25.32ms  min=5.75ms   med=14.69ms max=1.88s    p(90)=20.35ms  p(95)=24.15ms 
   ✗ http_req_failed................: 76.83% ✓ 22014     ✗ 6636
     http_req_receiving.............: avg=302.75µs min=8.41µs   med=50.69µs max=88.27ms  p(90)=138.69µs p(95)=175.88µs
     http_req_sending...............: avg=89.87µs  min=0s       med=34.37µs max=85.52ms  p(90)=85.65µs  p(95)=134µs   
     http_req_tls_handshaking.......: avg=290ns    min=0s       med=0s      max=3.21ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=9.95ms   min=0s       med=2.08ms  max=1.88s    p(90)=16.91ms  p(95)=27.18ms 
     http_reqs......................: 28650  47.634036/s
     iteration_duration.............: avg=1.04s    min=13.63ms  med=80.29ms max=10.09s   p(90)=5s       p(95)=5s      
     iterations.....................: 573    0.952681/s
     vus............................: 1      min=0       max=1 
     vus_max........................: 1      min=0       max=1 


running (10m01.5s), 0/1 VUs, 573 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"CEL","to":"ETH"}} response: {"result":0.00016790302905172403,"maxAge":90000,"statusCode":200,"data":{"result":0.00016790302905172403,"statusCode":200},"metricsMeta":{"feedId":"CEL/ETH"}}
request: {"data":{"from":"ANT","overrides":{"coingecko":{"ANT":"aragon"}},"to":"ETH"}} response: {"result":0.001706637970278949,"maxAge":90000,"statusCode":200,"data":{"result":0.001706637970278949,"statusCode":200},"metricsMeta":{"feedId":"ANT/ETH"}}
request: {"data":{"from":"AUDIO","to":"USD"}} response: {"result":0.3817022575882369,"maxAge":90000,"statusCode":200,"data":{"result":0.3817022575882369,"statusCode":200},"metricsMeta":{"feedId":"AUDIO/USD"}}
request: {"data":{"from":"BAT","to":"ETH"}} response: {"result":0.00013602687023075034,"maxAge":90000,"statusCode":200,"data":{"result":0.00013602687023075034,"statusCode":200},"metricsMeta":{"feedId":"BAT/ETH"}}
request: {"data":{"from":"BIT","overrides":{"coinpaprika":{"BIT":"bit-bitdao"},"nomics":{"BIT":"BIT2"},"tiingo":{"BIT":"BITDAO"}},"to":"USD"}} response: {"result":0.5394478800656536,"maxAge":90000,"statusCode":200,"data":{ [...]

2023-04-17 15:23 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for tiingo succeeded</summary>

```
running (09m44.6s), 1/1 VUs, 137 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.6s/10m0s

running (09m45.6s), 1/1 VUs, 137 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.6s/10m0s

running (09m46.6s), 1/1 VUs, 137 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.6s/10m0s

running (09m47.6s), 1/1 VUs, 139 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.6s/10m0s

running (09m48.6s), 1/1 VUs, 139 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.6s/10m0s

running (09m49.6s), 1/1 VUs, 139 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.6s/10m0s

running (09m50.6s), 1/1 VUs, 139 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.6s/10m0s

running (09m51.6s), 1/1 VUs, 139 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.6s/10m0s

running (09m52.6s), 1/1 VUs, 140 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.6s/10m0s

running (09m53.6s), 1/1 VUs, 140 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.6s/10m0s

running (09m54.6s), 1/1 VUs, 140 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.6s/10m0s

running (09m55.6s), 1/1 VUs, 140 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 140 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 141 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 141 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 141 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.6s), 1/1 VUs, 141 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.6s), 1/1 VUs, 141 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.5s), 0/1 VUs, 142 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m02.5s), 0/1 VUs, 142 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-tiingo-1INCH / USD returned 200
      ↳  98% — ✓ 128 / ✗ 2
     ✓ Group-tiingo-CTX / USD returned 200
     ✓ Group-tiingo-DOT / USD returned 200
     ✓ Group-tiingo-ARPA / USD returned 200
     ✓ Group-tiingo-DODO / USD returned 200
     ✓ Group-tiingo-AUDIO / USD returned 200
     ✓ Group-tiingo-BCH / USD returned 200
     ✓ Group-tiingo-CBETH / ETH returned 200
     ✗ Group-tiingo-DAI / USD returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✗ Group-tiingo-ATOM / ETH returned 200
      ↳  98% — ✓ 129 / ✗ 2
     ✗ Group-tiingo-AMPL / ETH returned 200
      ↳  98% — ✓ 129 / ✗ 2
     ✓ Group-tiingo-BOND / ETH returned 200
     ✓ Group-tiingo-CAKE / USD returned 200
     ✓ Group-tiingo-AVAX / USD returned 200
     ✓ Group-tiingo-DOGE / USD returned 200
     ✓ Group-tiingo-ATOM / USD returned 200
     ✗ Group-tiingo-DAI / ETH returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✗ Group-tiingo-ALPHA / ETH returned 200
      ↳  99% — ✓ 137 / ✗ 1
     ✓ Group-tiingo-1INCH / ETH returned 200
     ✓ Group-tiingo-CVX / ETH returned 200
     ✓ Group-tiingo-AXS / ETH returned 200
     ✓ Group-tiingo-BIT / USD returned 200
     ✓ Group-tiingo-ALBT / USD returned 200
     ✓ Group-tiingo-CVX / USD returned 200
     ✓ Group-tiingo-CELO / ETH returned 200
     ✓ Group-tiingo-BADGER / USD returned 200
     ✗ Group-tiingo-BNT / ETH returned 200
      ↳  97% — ✓ 130 / ✗ 3
     ✗ Group-tiingo-CSPR / USD returned 200
      ↳  99% — ✓ 133 / ✗ 1
     ✓ Group-tiingo-BTC / USD returned 200
     ✓ Group-tiingo-AMPL / USD returned 200
     ✓ Group-tiingo-BNT / USD returned 200
     ✗ Group-tiingo-BORING / USD returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✗ Group-tiingo-C98 / USD returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✓ Group-tiingo-APE / USD returned 200
     ✗ Group-tiingo-BAT / USD returned 200
      ↳  99% — ✓ 128 / ✗ 1
     ✗ Group-tiingo-DYDX / USD returned 200
      ↳  99% — ✓ 131 / ✗ 1
     ✓ Group-tiingo-ENJ / USD returned 200
     ✓ Group-tiingo-EOS / USD returned 200
     ✗ Group-tiingo-ENS / USD returned 200
      ↳  99% — ✓ 134 / ✗ 1
     ✗ Group-tiingo-ETH / BTC returned 200
      ↳  99% — ✓ 136 / ✗ 1
     ✗ Group-tiingo-BAL / USD returned 200
      ↳  99% — ✓ 130 / ✗ 1
     ✓ Group-tiingo-ALCX / USD returned 200
     ✓ Group-tiingo-CREAM / ETH returned 200
     ✗ Group-tiingo-APE / ETH returned 200
      ↳  99% — ✓ 132 / ✗ 1
     ✓ Group-tiingo-BAND / ETH returned 200
     ✓ Group-tiingo-CTSI / ETH returned 200
     ✓ Group-tiingo-ERN / USD returned 200
     ✓ Group-tiingo-CBETH / USD returned 200
     ✓ Group-tiingo-ALCX / ETH returned 200
     ✗ Group-tiingo-ALUSD / USD returned 200
      ↳  99% — ✓ 136 / ✗ 1

     checks.........................: 99.66% ✓ 6635      ✗ 22  
     data_received..................: 2.2 MB 3.6 kB/s
     data_sent......................: 1.1 MB 1.8 kB/s
     errors.........................: 0.00%  ✓ 0         ✗ 6635
     http_req_blocked...............: avg=1.19µs  min=105ns   med=184ns   max=6.77ms   p(90)=270ns    p(95)=323ns   
     http_req_connecting............: avg=52ns    min=0s      med=0s      max=372.5µs  p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=13.21ms min=1.21ms  med=11.11ms max=305.17ms p(90)=14.93ms  p(95)=17.44ms 
       { expected_response:true }...: avg=13.25ms min=4.01ms  med=11.12ms max=305.17ms p(90)=14.94ms  p(95)=17.48ms 
   ✓ http_req_failed................: 0.39%  ✓ 28        ✗ 7072
     http_req_receiving.............: avg=79.51µs min=10.26µs med=53.66µs max=47ms     p(90)=109.96µs p(95)=144.75µs
     http_req_sending...............: avg=67.2µs  min=15.47µs med=38.43µs max=88.34ms  p(90)=99.19µs  p(95)=171.96µs
     http_req_tls_handshaking.......: avg=425ns   min=0s      med=0s      max=3.01ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=13.07ms min=1.15ms  med=10.98ms max=287.95ms p(90)=14.78ms  p(95)=17.28ms 
     http_reqs......................: 7100   11.783937/s
     iteration_duration.............: avg=4.24s   min=94.61ms med=5s      max=5s       p(90)=5s       p(95)=5s      
     iterations.....................: 142    0.235679/s
     vus............................: 1      min=0       max=1 
     vus_max........................: 1      min=0       max=1 


running (10m02.5s), 0/1 VUs, 142 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"crypto","from":"EOS","overrides":{"coingecko":{"EOS":"eos"},"coinpaprika":{"EOS":"eos-eos"}},"to":"USD"}} response: {"result":1.207966965830058,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":1.207966965830058},"metricsMeta":{"feedId":"EOS/USD"}}
request: {"data":{"from":"BADGER","to":"USD"}} response: {"result":3.0203680332844214,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":3.0203680332844214},"metricsMeta":{"feedId":"BADGER/USD"}}
request: {"data":{"endpoint":"crypto","from":"BTC","overrides":{"coingecko":{"BTC":"bitcoin"}},"to":"USD"}} response: {"result":29421.583201405432,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":29421.583201405432},"metricsMeta":{"feedId":"BTC/USD"}}
request: {"data":{"from":"CSPR","to":"USD"}} response: {"result":0.055730753237687156,"providerStatusCode":200,"maxAge":90000,"statusCode":200,"data":{"result":0.055730753237687156},"metricsMeta":{"feedId":"CSPR/USD"}}
request: {"data":{"from":"BAND","overr [...]

2023-04-17 15:23 UTC, cl-ea-js-service commented
<details><summary>:warning: Soak test for coinmarketcap failed :warning:</summary>

```
running (10m02.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m05.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m06.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m07.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m08.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m09.7s), 1/1 VUs, 30 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m10.0s), 0/1 VUs, 31 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinmarketcap-BAND / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AAVE / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AVAX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BAL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-COMP / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ALCX / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ALBT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BNT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-CELO / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ATOM / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ANT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ADA / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BAT / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ANKR / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BIT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AUDIO / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BORING / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-COMP / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-C98 / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-CEL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AXS / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BNB / ETH returned 200
      ↳  16% — ✓ 5 / ✗ 26
     ✗ Group-coinmarketcap-BTC / USD returned 200
      ↳  16% — ✓ 5 / ✗ 26
     ✗ Group-coinmarketcap-AAVE / USD returned 200
      ↳  16% — ✓ 5 / ✗ 26
     ✗ Group-coinmarketcap-BOND / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-1INCH / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BADGER / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BNT / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-CRO / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ALCX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ALUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BNB / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BADGER / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BTC / ETH returned 200
      ↳  16% — ✓ 5 / ✗ 26
     ✗ Group-coinmarketcap-BUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-APE / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BAND / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AMPL / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-CAKE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-1INCH / ETH returned 200
      ↳  19% — ✓ 6 / ✗ 25
     ✗ Group-coinmarketcap-ADX / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AMP / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ATOM / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-CREAM / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ALPHA / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-AMPL / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-BUSD / ETH returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-APE / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31
     ✗ Group-coinmarketcap-ARPA / USD returned 200
      ↳  0% — ✓ 0 / ✗ 31

     checks.........................: 1.67%  ✓ 26       ✗ 1524
     data_received..................: 667 kB 1.1 kB/s
     data_sent......................: 214 kB 351 B/s
     errors.........................: 98.32% ✓ 1524     ✗ 26  
     http_req_blocked...............: avg=61.57µs  min=97ns    med=223ns   max=94.99ms  p(90)=312ns    p(95)=374ns   
     http_req_connecting............: avg=424ns    min=0s      med=0s      max=657.36µs p(90)=0s       p(95)=0s      
   ✗ http_req_duration..............: avg=2.18s    min=3.16ms  med=2.22s   max=2.23s    p(90)=2.22s    p(95)=2.22s   
       { expected_response:true }...: avg=163.45ms min=3.16ms  med=5.06ms  max=827.2ms  p(90)=826.72ms p(95)=827ms   
   ✗ http_req_failed................: 98.32% ✓ 1524     ✗ 26  
     http_req_receiving.............: avg=72.73µs  min=12.81µs med=55.27µs max=1.58ms   p(90)=129.2µs  p(95)=156.57µs
     http_req_sending...............: avg=56.35µs  min=10.24µs med=45.7µs  max=370.98µs p(90)=91.98µs  p(95)=142.92µs
     http_req_tls_handshaking.......: avg=54.87µs  min=0s      med=0s      max=85.05ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=2.18s    min=3.06ms  med=2.22s   max=2.23s    p(90)=2.22s    p(95)=2.22s   
     http_reqs......................: 1550   2.540994/s
     iteration_duration.............: avg=19.67s   min=17.78s  med=20s     max=20.04s   p(90)=20.01s   p(95)=20.01s  
     iterations.....................: 31     0.05082/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m10.0s), 0/1 VUs, 31 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"CELO","overrides":{"coinpaprika":{"CELO":"celo-celo"}},"to":"ETH"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the relevant channels."}}
request: {"data":{"from":"AMPL","to":"ETH"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the relevant channels."}}
request: {"data":{"from":"AUDIO","to":"USD"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provider for the requested data yet. Retry after a short delay, and if the problem persists raise this issue in the relevant channels."}}
request: {"data":{"from":"BAL","to":"USD"}} response: {"status":"errored","statusCode":504,"error":{"name":"AdapterError","message":"The EA has not received any values from the Data Provi [...]

2023-04-24 16:10 UTC, closed without merging