Add rate limits to autogenerated readmes
smartcontractkit/external-adapters-js pull request #2884
Opened 2023-07-20 14:26 UTC by karen-stepanyan

## Closes [PDI-2235](https://smartcontract-it.atlassian.net/browse/PDI-2235)

## Description
This PR adds rate limits section to autogenerated readmes. For v2 adapters it will only add http limits (v3 has only http limits anyways). This is something that maybe needs to be changed but ws limits for v2 are somewhat inconsistent, different adapters have different properties. Also there are just 9 v2 adapters that have ws limits.

2023-07-20 15:35 UTC, amit-momin commented on packages/scripts/src/generate-readme/generator.ts
> +      this.rateLimits = rateLimits
This is just me nitpicking but could we do this in a single line?
```suggestion
      this.rateLimits = adapter.rateLimiting?.tiers || {}
```

2023-07-20 16:01 UTC, karen-stepanyan commented on .changeset/rich-apricots-change.md
Hey @amit-momin . I had a [PR](https://github.com/smartcontractkit/external-adapters-js/pull/2875) that updates all packages and applies the changes, but i see that some adapters already have the newest version. Also pipeline fails maybe because of yarn. Should i close that PR also ?

2023-07-20 16:06 UTC, amit-momin commented on .changeset/rich-apricots-change.md
Ah I see. It might be worth getting that one merged since any update to v3 adapters would get blocked with the fw version check you had added otherwise. So no need to bump it here

2023-07-20 20:05 UTC, amit-momin submitted a review, later dismissed

2023-07-25 20:39 UTC, alejoberardino requested changes
Super minor nit

2023-07-25 20:39 UTC, alejoberardino commented on packages/scripts/src/generate-readme/tableAssets.ts
> +  'Limit for 1 hour',
Let's change it to "Requests/credits per second" etc

2023-07-28 19:44 UTC, amit-momin approved these changes

2023-08-01 20:05 UTC, merged