add script to generate v3 ea
smartcontractkit/external-adapters-js pull request #2898
Opened 2023-08-03 06:04 UTC by karen-stepanyan

## Description

EA framework now provides interactive tool to generate new v3 adapters. This PR adds  a functionality to use that tool in monorepo. 

## Changes

- two new devDeps in main package.json, `@chainlink/external-adapter-framework` and `yo`
- new `generate-v3-adapter` in scripts/src folder. This takes care of updating tsconfgs
- new script in package.json to execute the logic in `generate-v3-adapter` folder which itself calls the generator from framework

## Steps to Test
To create test adapter run 

`yarn generate-v3-adapter` 

optionally you can specify also the type (source is the default)

`yarn generate-v3-adapter composite`

2023-08-03 18:58 UTC, alejoberardino requested changes
Only change would be to directly remove the previous generation script and keep this as the only one. If preferred, this PR could just change the reference and we could open a separate PR to remove the old v2 generation

2023-08-03 19:38 UTC, karen-stepanyan commented
hey @alejoberardino . Yeah, i think it  makes sense to replace it here so that we don't have a new script. 
I also deleted examples folder and updated the contributing file

2023-08-04 16:37 UTC, alejoberardino approved these changes
Approved, left one comment that can be ignored if it's not relevant

2023-08-04 16:43 UTC, jacksnipe24 commented on CONTRIBUTING.md
>  You can open a PR with the [New EA PR Template](./.github/PULL_REQUEST_TEMPLATE/new_ea_pr_template.md) by replacing `<branch>` in this URL: [https://github.com/smartcontractkit/external-adapters-js/c
I think not only CONTRIBUTING.md but also other doc files need to be reviewed and updated. At least the PR opening checklist is not up to date at this point and also `gnu-sed` seems is not installed on my machine and it's not a problem at all.  Not sure if this is a right PR for them tho.

2023-08-04 16:46 UTC, karen-stepanyan commented on CONTRIBUTING.md
>  You can open a PR with the [New EA PR Template](./.github/PULL_REQUEST_TEMPLATE/new_ea_pr_template.md) by replacing `<branch>` in this URL: [https://github.com/smartcontractkit/external-adapters-js/c
I think not only CONTRIBUTING.md but also other doc files need to be reviewed and updated. At least the PR opening checklist is not up to date at this point and also gnu-sed seems is not installed on my machine and it's not a problem at all. Not sure if this is a right PR for them tho.

2023-08-07 16:22 UTC, merged