Upgrade gramchain to v3 framework
smartcontractkit/external-adapters-js pull request #2920
Opened 2023-08-10 09:02 UTC by karen-stepanyan

## Description
Upgraded `gramchain` to the v3 framework

## Steps to Test

yarn test packages/sources/gramchain

2023-08-10 09:18 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for gramchain succeeded</summary>

```
default   [  93% ] 1 VUs  09m20.8s/10m0s

running (09m21.8s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.8s/10m0s

running (09m22.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.8s/10m0s

running (09m23.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.8s/10m0s

running (09m24.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.8s/10m0s

running (09m25.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.8s/10m0s

running (09m26.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.8s/10m0s

running (09m27.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.8s/10m0s

running (09m28.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.8s/10m0s

running (09m29.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.8s/10m0s

running (09m30.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.8s/10m0s

running (09m31.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.8s/10m0s

running (09m32.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.8s/10m0s

running (09m33.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.8s/10m0s

running (09m34.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.8s/10m0s

running (09m35.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.8s/10m0s

running (09m36.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.8s/10m0s

running (09m37.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.8s/10m0s

running (09m38.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.8s/10m0s

running (09m39.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.8s/10m0s

running (09m40.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.8s/10m0s

running (09m41.8s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.8s/10m0s

running (09m42.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.8s/10m0s

running (09m43.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.8s/10m0s

running (09m44.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.8s/10m0s

running (09m45.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.8s/10m0s

running (09m46.8s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.8s/10m0s

running (09m47.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.8s/10m0s

running (09m48.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.8s/10m0s

running (09m49.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.8s/10m0s

running (09m50.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.8s/10m0s

running (09m51.8s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.8s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.8s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

     ✓ Group-gramchain-CacheGold PoR USD returned 200
     ✓ Group-gramchain-test-payload-0 returned 200

     checks.........................: 100.00% ✓ 240      ✗ 0  
     data_received..................: 118 kB  197 B/s
     data_sent......................: 28 kB   46 B/s
     errors.........................: 0.00%   ✓ 0        ✗ 240
     http_req_blocked...............: avg=20.88ms  min=190ns   med=393ns   max=5.01s    p(90)=597ns    p(95)=659ns   
     http_req_connecting............: avg=3.76µs   min=0s      med=0s      max=904.63µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=20.58ms  min=3.78ms  med=5.25ms  max=1.82s    p(90)=6.73ms   p(95)=7.22ms  
       { expected_response:true }...: avg=20.58ms  min=3.78ms  med=5.25ms  max=1.82s    p(90)=6.73ms   p(95)=7.22ms  
   ✓ http_req_failed................: 0.00%   ✓ 0        ✗ 240
     http_req_receiving.............: avg=64.33µs  min=27.45µs med=60.89µs max=323.7µs  p(90)=88.13µs  p(95)=97.75µs 
     http_req_sending...............: avg=112.23µs min=30.03µs med=107.2µs max=214.68µs p(90)=146.46µs p(95)=162.76µs
     http_req_tls_handshaking.......: avg=25.21µs  min=0s      med=0s      max=6.05ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=20.4ms   min=3.62ms  med=5.08ms  max=1.82s    p(90)=6.55ms   p(95)=7.04ms  
     http_reqs......................: 240     0.398729/s
     iteration_duration.............: avg=5.01s    min=4.99s   med=5s      max=6.83s    p(90)=5s       p(95)=5s      
     iterations.....................: 120     0.199365/s
     vus............................: 1       min=1      max=1
     vus_max........................: 1       min=1      max=1


running (10m01.9s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"getgrambalances"}} response: {"result":28297.17,"data":{"result":28297.17},"timestamps":{"providerDataRequestedUnixMs":1691658623694,"providerDataReceivedUnixMs":1691658623908},"statusCode":200,"meta":{"adapterName":"GRAMCHAIN","metrics":{"feedId":"{\"custodianID\":\"cache\",\"metalCode\":\"au\",\"utilizationLockCode\":\"locked\"}"}}}
request: {"data":{}} response: {"result":28297.17,"data":{"result":28297.17},"timestamps":{"providerDataRequestedUnixMs":1691658623694,"providerDataReceivedUnixMs":1691658623908},"statusCode":200,"meta":{"adapterName":"GRAMCHAIN","metrics":{"feedId":"{\"custodianID\":\"cache\",\"metalCode\":\"au\",\"utilizationLockCode\":\"locked\"}"}}}
request: {"data":{"endpoint":"getgrambalances"}} response: {"result":28297.17,"data":{"result":28297.17},"timestamps":{"providerDataRequestedUnixMs":1691658628615,"providerDataReceivedUnixMs":1691658628832},"statusCode":200,"meta":{"adapterName":"GRAMCHAIN","metrics":{"feedId":"{\"custodianID\":\"cache\",\"metalCode\":\"au\",\"utilizationLockCode\":\"locked\"}"}}}
request: {"data":{}} response: {"result":28297.17,"data":{"result":28297.17},"timestamp [...]

2023-08-11 06:59 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for gramchain succeeded</summary>

```
default   [  93% ] 1 VUs  09m19.9s/10m0s

running (09m20.9s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  93% ] 1 VUs  09m20.9s/10m0s

running (09m21.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m21.9s/10m0s

running (09m22.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m22.9s/10m0s

running (09m23.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m23.9s/10m0s

running (09m24.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m24.9s/10m0s

running (09m25.9s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m25.9s/10m0s

running (09m26.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  94% ] 1 VUs  09m26.9s/10m0s

running (09m27.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m27.9s/10m0s

running (09m28.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m28.9s/10m0s

running (09m29.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m29.9s/10m0s

running (09m30.9s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m30.9s/10m0s

running (09m31.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m31.9s/10m0s

running (09m32.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  95% ] 1 VUs  09m32.9s/10m0s

running (09m33.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m33.9s/10m0s

running (09m34.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m34.9s/10m0s

running (09m35.9s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m35.9s/10m0s

running (09m36.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m36.9s/10m0s

running (09m37.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m37.9s/10m0s

running (09m38.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  96% ] 1 VUs  09m38.9s/10m0s

running (09m39.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m39.9s/10m0s

running (09m40.9s), 1/1 VUs, 115 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m40.9s/10m0s

running (09m41.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m41.9s/10m0s

running (09m42.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m42.9s/10m0s

running (09m43.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m43.9s/10m0s

running (09m44.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.9s/10m0s

running (09m45.9s), 1/1 VUs, 116 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.9s/10m0s

running (09m46.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.9s/10m0s

running (09m47.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.9s/10m0s

running (09m48.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.9s/10m0s

running (09m49.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.9s/10m0s

running (09m50.9s), 1/1 VUs, 117 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.9s/10m0s

running (09m51.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.9s/10m0s

running (09m52.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.9s/10m0s

running (09m53.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.9s/10m0s

running (09m54.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.9s/10m0s

running (09m55.9s), 1/1 VUs, 118 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.9s/10m0s

running (09m56.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.9s/10m0s

running (09m57.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.9s/10m0s

running (09m58.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.9s/10m0s

running (09m59.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.9s/10m0s

running (10m00.9s), 1/1 VUs, 119 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

     ✓ Group-gramchain-CacheGold PoR USD returned 200
     ✓ Group-gramchain-test-payload-0 returned 200

     checks.........................: 100.00% ✓ 240      ✗ 0  
     data_received..................: 118 kB  197 B/s
     data_sent......................: 28 kB   46 B/s
     errors.........................: 0.00%   ✓ 0        ✗ 240
     http_req_blocked...............: avg=20.89ms  min=166ns   med=301ns    max=5.01s    p(90)=486ns    p(95)=773ns   
     http_req_connecting............: avg=3.18µs   min=0s      med=0s       max=765.19µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=19.38ms  min=4.58ms  med=5.7ms    max=1.62s    p(90)=6.89ms   p(95)=7.55ms  
       { expected_response:true }...: avg=19.38ms  min=4.58ms  med=5.7ms    max=1.62s    p(90)=6.89ms   p(95)=7.55ms  
   ✓ http_req_failed................: 0.00%   ✓ 0        ✗ 240
     http_req_receiving.............: avg=112.23µs min=18.13µs med=71.06µs  max=2.42ms   p(90)=261.43µs p(95)=279.15µs
     http_req_sending...............: avg=105.01µs min=56.87µs med=100.89µs max=222.09µs p(90)=137.63µs p(95)=144.97µs
     http_req_tls_handshaking.......: avg=23.12µs  min=0s      med=0s       max=5.55ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=19.16ms  min=4.45ms  med=5.46ms   max=1.62s    p(90)=6.65ms   p(95)=7.34ms  
     http_reqs......................: 240     0.398866/s
     iteration_duration.............: avg=5.01s    min=4.99s   med=5s       max=6.63s    p(90)=5s       p(95)=5s      
     iterations.....................: 120     0.199433/s
     vus............................: 1       min=1      max=1
     vus_max........................: 1       min=1      max=1


running (10m01.7s), 0/1 VUs, 120 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"getgrambalances"}} response: {"result":28297.17,"data":{"result":28297.17},"timestamps":{"providerDataRequestedUnixMs":1691736674904,"providerDataReceivedUnixMs":1691736675123},"statusCode":200,"meta":{"adapterName":"GRAMCHAIN","metrics":{"feedId":"{\"custodianID\":\"cache\",\"metalCode\":\"au\",\"utilizationLockCode\":\"locked\"}"}}}
request: {"data":{}} response: {"result":28297.17,"data":{"result":28297.17},"timestamps":{"providerDataRequestedUnixMs":1691736674904,"providerDataReceivedUnixMs":1691736675123},"statusCode":200,"meta":{"adapterName":"GRAMCHAIN","metrics":{"feedId":"{\"custodianID\":\"cache\",\"metalCode\":\"au\",\"utilizationLockCode\":\"locked\"}"}}}
request: {"data":{"endpoint":"getgrambalances"}} response: {"result":28297.17,"data":{"result":28297.17},"timestamps":{"providerDataRequestedUnixMs":1691736679901,"providerDataReceivedUnixMs":1691736680128},"statusCode":200,"meta":{"adapterName":"GRAMCHAIN","metrics":{"feedId":"{\"custodianID\":\"cache\",\"metalCode\":\"au\",\"utilizationLockCode\":\"locked\"}"}}}
request: {"data":{}} response: {"result":28297.17,"data":{"result":28 [...]

2023-08-16 20:15 UTC, amit-momin requested changes

2023-08-16 20:15 UTC, amit-momin commented on packages/sources/gramchain/src/transport/getgrambalances.ts
> +      )
Seems like v2 didn't have it but just for safety could you add some validation on `item.PureGrams` to make sure it exists and if it's a number before we use it here?

2023-08-16 20:15 UTC, amit-momin commented on packages/sources/gramchain/src/transport/getgrambalances.ts
> +      }
I think we can use AsOfUTC for the provider indicated timestamp here

2023-08-17 14:39 UTC, amit-momin approved these changes

2023-08-17 14:39 UTC, merged