Coinpaprika EA - change default_API_endpoint
smartcontractkit/external-adapters-js pull request #2969
Opened 2023-09-04 17:25 UTC by Subarna-Singh

## Closes #DF-19036

## Description

change DEFAULT_API_ENDPOINT  
from:'[https://api.coinpaprika.com'](https://api.coinpaprika.com%27/)
to: '[https://api-pro.coinpaprika.com'](https://api-pro.coinpaprika.com%27/)

## Changes

- removed DEFAULT_API_ENDPOINT and PRO_API_ENDPOINT variables, and added default value to API_ENDPOINT
- removed getApiEndpoint and getApiHeaders methods from config/index.ts.
- subsequent replacement in transport files with default values in place of getApiEndpoint and getApiHeaders

## Steps to Test

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `adapter-secrets` configuration file or update the [soak testing blacklist](/packages/scripts/src/get-changed-adapters/soakTestBlacklist.ts).
- [ ] If a new adapter was made, or a new endpoint was added, update the `test-payload.json` file with relevant requests.
- [ x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [ x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ x] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

2023-09-04 17:42 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinpaprika-BAND / USD returned 200
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-AUDIO / USD returned 200
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-BNB / USD returned 200
     ✓ Group-coinpaprika-BADGER / USD returned 200
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✓ Group-coinpaprika-CRO / USD returned 200
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5

     checks.........................: 97.75% ✓ 5621     ✗ 129 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.24%  ✓ 129      ✗ 5621
     http_req_blocked...............: avg=16.19µs min=112ns   med=171ns   max=91.73ms  p(90)=273ns    p(95)=326ns   
     http_req_connecting............: avg=117ns   min=0s      med=0s      max=677.91µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=56.19ms min=1.78ms  med=3.15ms  max=2.32s    p(90)=5.78ms   p(95)=8.83ms  
       { expected_response:true }...: avg=6.34ms  min=1.78ms  med=3.13ms  max=1.22s    p(90)=5.48ms   p(95)=6.86ms  
   ✓ http_req_failed................: 2.24%  ✓ 129      ✗ 5621
     http_req_receiving.............: avg=96.15µs min=10.3µs  med=65.7µs  max=29.09ms  p(90)=156.14µs p(95)=243.14µs
     http_req_sending...............: avg=59.33µs min=19.04µs med=38.16µs max=602.5µs  p(90)=120.25µs p(95)=210.01µs
     http_req_tls_handshaking.......: avg=14.57µs min=0s      med=0s      max=83.77ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=56.03ms min=1.71ms  med=3.02ms  max=2.32s    p(90)=5.55ms   p(95)=8.57ms  
     http_reqs......................: 5750   9.539787/s
     iteration_duration.............: avg=5.24s   min=4.99s   med=5s      max=19.15s   p(90)=5s       p(95)=5s      
     iterations.....................: 115    0.190796/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m02.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ALBT","to":"USD"}} response: {"result":0.0012023984498074928,"data":{"result":0.0012023984498074928},"timestamps":{"providerDataRequestedUnixMs":1693849298472,"providerDataReceivedUnixMs":1693849298768},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"albt-allianceblock\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BORING","to":"USD"}} response: {"result":0.0021002118438087514,"data":{"result":0.0021002118438087514},"timestamps":{"providerDataRequestedUnixMs":1693849298472,"providerDataReceivedUnixMs":1693849298768},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"boring-boringdao\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CRO","to":"ETH"}} response: {"result":0.00003104071674705135,"data":{"result":0.00003104071674705135},"timestamps":{"providerDataRequestedUnixMs":1693849277736,"providerDataReceivedUnixMs":1693849278148},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cro-cryptocom-chain\",\"quote\":\"eth\",\"resultPath\":\" [...]

2023-09-04 19:28 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m51.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m00.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinpaprika-ALUSD / USD returned 200
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  94% — ✓ 109 / ✗ 6
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  94% — ✓ 109 / ✗ 6
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  94% — ✓ 109 / ✗ 6
     ✓ Group-coinpaprika-ALCX / USD returned 200
     ✓ Group-coinpaprika-APE / USD returned 200
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinpaprika-ALBT / USD returned 200
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✓ Group-coinpaprika-ADA / USD returned 200
     ✓ Group-coinpaprika-ANKR / USD returned 200
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2

     checks.........................: 97.60% ✓ 5612     ✗ 138 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.40%  ✓ 138      ✗ 5612
     http_req_blocked...............: avg=17.48µs min=105ns   med=173ns   max=99.16ms  p(90)=266ns    p(95)=332ns   
     http_req_connecting............: avg=172ns   min=0s      med=0s      max=994.03µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=59.21ms min=1.32ms  med=3.13ms  max=2.3s     p(90)=5.58ms   p(95)=8.04ms  
       { expected_response:true }...: avg=6.12ms  min=1.32ms  med=3.09ms  max=1.61s    p(90)=5.23ms   p(95)=6.4ms   
   ✓ http_req_failed................: 2.40%  ✓ 138      ✗ 5612
     http_req_receiving.............: avg=77.89µs min=9.89µs  med=61.56µs max=4.48ms   p(90)=140.22µs p(95)=165µs   
     http_req_sending...............: avg=55.98µs min=19.64µs med=36.73µs max=548.46µs p(90)=116.54µs p(95)=193.41µs
     http_req_tls_handshaking.......: avg=836ns   min=0s      med=0s      max=4.81ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=59.07ms min=1.13ms  med=3ms     max=2.3s     p(90)=5.4ms    p(95)=7.85ms  
     http_reqs......................: 5750   9.569958/s
     iteration_duration.............: avg=5.22s   min=4.99s   med=5s      max=19.06s   p(90)=5s       p(95)=5s      
     iterations.....................: 115    0.191399/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m00.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ARPA","to":"USD"}} response: {"result":0.042366450769113634,"data":{"result":0.042366450769113634},"timestamps":{"providerDataRequestedUnixMs":1693855646912,"providerDataReceivedUnixMs":1693855647185},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"arpa-arpa-chain\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"1INCH","to":"ETH"}} response: {"result":0.0001451236821601699,"data":{"result":0.0001451236821601699},"timestamps":{"providerDataRequestedUnixMs":1693855636543,"providerDataReceivedUnixMs":1693855636805},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"1inch-1inch\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CELO","overrides":{"coinpaprika":{"CELO":"celo-celo"}},"to":"ETH"}} response: {"result":0.000260639678244111,"data":{"result":0.000260639678244111},"timestamps":{"providerDataRequestedUnixMs":1693855636543,"providerDataReceivedUnixMs":1693855636805},"statusCode":200,"meta":{"adapterName":"COINPA [...]

2023-09-04 20:54 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.7s), 1/1 VUs, 110 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 110 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 110 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.3s), 0/1 VUs, 112 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  97% — ✓ 109 / ✗ 3
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  97% — ✓ 109 / ✗ 3
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  92% — ✓ 104 / ✗ 8
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  99% — ✓ 111 / ✗ 1
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  99% — ✓ 111 / ✗ 1
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  92% — ✓ 104 / ✗ 8
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  97% — ✓ 109 / ✗ 3
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  93% — ✓ 105 / ✗ 7
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  93% — ✓ 105 / ✗ 7
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  92% — ✓ 104 / ✗ 8
     ✓ Group-coinpaprika-ALCX / ETH returned 200
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  97% — ✓ 109 / ✗ 3
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  94% — ✓ 106 / ✗ 6
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  92% — ✓ 104 / ✗ 8
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  99% — ✓ 111 / ✗ 1
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  92% — ✓ 104 / ✗ 8
     ✓ Group-coinpaprika-BNT / ETH returned 200
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 110 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  92% — ✓ 104 / ✗ 8
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  99% — ✓ 111 / ✗ 1
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  99% — ✓ 111 / ✗ 1
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  94% — ✓ 106 / ✗ 6
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  95% — ✓ 107 / ✗ 5

     checks.........................: 96.91% ✓ 5427     ✗ 173 
     data_received..................: 2.6 MB 4.3 kB/s
     data_sent......................: 793 kB 1.3 kB/s
     errors.........................: 3.08%  ✓ 173      ✗ 5427
     http_req_blocked...............: avg=895.75µs min=109ns   med=167ns   max=5.01s    p(90)=252ns    p(95)=309ns   
     http_req_connecting............: avg=189ns    min=0s      med=0s      max=1.06ms   p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=74.13ms  min=1.21ms  med=3.23ms  max=2.28s    p(90)=5.96ms   p(95)=10.01ms 
       { expected_response:true }...: avg=5.94ms   min=1.21ms  med=3.19ms  max=1.48s    p(90)=5.37ms   p(95)=6.77ms  
   ✓ http_req_failed................: 3.08%  ✓ 173      ✗ 5427
     http_req_receiving.............: avg=85.93µs  min=9.99µs  med=59.17µs max=50.93ms  p(90)=117.54µs p(95)=150.24µs
     http_req_sending...............: avg=54.24µs  min=20.28µs med=34.77µs max=589.41µs p(90)=110.21µs p(95)=194.5µs 
     http_req_tls_handshaking.......: avg=838ns    min=0s      med=0s      max=4.69ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=73.99ms  min=1.13ms  med=3.12ms  max=2.28s    p(90)=5.77ms   p(95)=9.59ms  
     http_reqs......................: 5600   9.328104/s
     iteration_duration.............: avg=5.36s    min=4.99s   med=5s      max=23.64s   p(90)=5s       p(95)=5.11s   
     iterations.....................: 112    0.186562/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m00.3s), 0/1 VUs, 112 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"AMP","to":"USD"}} response: {"result":0.0018380096419399936,"data":{"result":0.0018380096419399936},"timestamps":{"providerDataRequestedUnixMs":1693860815641,"providerDataReceivedUnixMs":1693860815880},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"amp-amp\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALPHA","overrides":{"coingecko":{"ALPHA":"alpha-finance"},"coinpaprika":{"ALPHA":"alpha-alpha-finance"},"nomics":{"ALPHA":"ALPHA7"}},"to":"ETH"}} response: {"result":0.00004610048708195982,"data":{"result":0.00004610048708195982},"timestamps":{"providerDataRequestedUnixMs":1693860826010,"providerDataReceivedUnixMs":1693860826269},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alpha-alpha-finance\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BORING","to":"USD"}} response: {"result":0.0020981439956763727,"data":{"result":0.0020981439956763727},"timestamps":{"providerDataRequestedUnixMs":1693860815641,"providerDataReceivedUnixMs":1693860815880},"statusCode":200,"me [...]

2023-09-05 09:22 UTC, alecgard approved these changes
Looks good! 🚀

2023-09-05 09:53 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```

running (09m56.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.9s), 0/1 VUs, 113 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✓ Group-coinpaprika-ALCX / ETH returned 200
     ✓ Group-coinpaprika-CRO / ETH returned 200
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✓ Group-coinpaprika-BAT / ETH returned 200
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✓ Group-coinpaprika-1INCH / ETH returned 200
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  95% — ✓ 108 / ✗ 5
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2

     checks.........................: 97.30% ✓ 5498     ✗ 152 
     data_received..................: 2.6 MB 4.3 kB/s
     data_sent......................: 801 kB 1.3 kB/s
     errors.........................: 2.69%  ✓ 152      ✗ 5498
     http_req_blocked...............: avg=902.13µs min=121ns   med=182ns   max=5.09s    p(90)=282ns    p(95)=353ns   
     http_req_connecting............: avg=143ns    min=0s      med=0s      max=811.73µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=65.35ms  min=1.65ms  med=3.05ms  max=2.32s    p(90)=5.5ms    p(95)=8.3ms   
       { expected_response:true }...: avg=5.77ms   min=1.65ms  med=3.01ms  max=1.61s    p(90)=5.14ms   p(95)=6.16ms  
   ✓ http_req_failed................: 2.69%  ✓ 152      ✗ 5498
     http_req_receiving.............: avg=100.3µs  min=10.93µs med=53.41µs max=67.82ms  p(90)=135.06µs p(95)=187µs   
     http_req_sending...............: avg=148.89µs min=21.04µs med=35.47µs max=86.9ms   p(90)=122.33µs p(95)=211.53µs
     http_req_tls_handshaking.......: avg=1.03µs   min=0s      med=0s      max=5.87ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=65.1ms   min=1.6ms   med=2.93ms  max=2.24s    p(90)=5.26ms   p(95)=7.97ms  
     http_reqs......................: 5650   9.340235/s
     iteration_duration.............: avg=5.35s    min=4.99s   med=5s      max=23.79s   p(90)=5s       p(95)=5.66s   
     iterations.....................: 113    0.186805/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m04.9s), 0/1 VUs, 113 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ATOM","to":"ETH"}} response: {"result":0.004132375563464776,"data":{"result":0.004132375563464776},"timestamps":{"providerDataRequestedUnixMs":1693907564989,"providerDataReceivedUnixMs":1693907565248},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"atom-cosmos\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"APE","to":"USD"}} response: {"result":1.3419912790587787,"data":{"result":1.3419912790587787},"timestamps":{"providerDataRequestedUnixMs":1693907554620,"providerDataReceivedUnixMs":1693907554873},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"ape-apecoin\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BNT","to":"USD"}} response: {"result":0.42415444940157104,"data":{"result":0.42415444940157104},"timestamps":{"providerDataRequestedUnixMs":1693907554620,"providerDataReceivedUnixMs":1693907554873},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bnt-bancor\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BIT","overrides":{"coi [...]

2023-09-05 16:28 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✓ Group-coinpaprika-BNT / USD returned 200
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✓ Group-coinpaprika-BAT / USD returned 200
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-CRO / USD returned 200
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2

     checks.........................: 97.03% ✓ 5531     ✗ 169 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.96%  ✓ 169      ✗ 5531
     http_req_blocked...............: avg=3.12µs   min=100ns   med=187ns   max=16.37ms  p(90)=282ns    p(95)=350ns   
     http_req_connecting............: avg=125ns    min=0s      med=0s      max=714.16µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=71.62ms  min=1.6ms   med=3.17ms  max=2.25s    p(90)=5.74ms   p(95)=8.92ms  
       { expected_response:true }...: avg=6.09ms   min=1.6ms   med=3.14ms  max=1.65s    p(90)=5.28ms   p(95)=6.26ms  
   ✓ http_req_failed................: 2.96%  ✓ 169      ✗ 5531
     http_req_receiving.............: avg=106.18µs min=9.98µs  med=63.65µs max=66.25ms  p(90)=154.18µs p(95)=252.35µs
     http_req_sending...............: avg=57.9µs   min=20.67µs med=38.66µs max=603.39µs p(90)=108.76µs p(95)=195.64µs
     http_req_tls_handshaking.......: avg=1µs      min=0s      med=0s      max=5.75ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=71.46ms  min=1.46ms  med=3.04ms  max=2.25s    p(90)=5.52ms   p(95)=8.61ms  
     http_reqs......................: 5700   9.425753/s
     iteration_duration.............: avg=5.3s     min=4.99s   med=5s      max=18.8s    p(90)=5s       p(95)=5.57s   
     iterations.....................: 114    0.188515/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m04.7s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"AUDIO","to":"USD"}} response: {"result":0.15369183901802178,"data":{"result":0.15369183901802178},"timestamps":{"providerDataRequestedUnixMs":1693931263959,"providerDataReceivedUnixMs":1693931264241},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"audio-audius\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALCX","to":"ETH"}} response: {"result":0.006905587972149743,"data":{"result":0.006905587972149743},"timestamps":{"providerDataRequestedUnixMs":1693931253591,"providerDataReceivedUnixMs":1693931253854},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alcx-alchemix\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALPHA","overrides":{"coingecko":{"ALPHA":"alpha-finance"},"coinpaprika":{"ALPHA":"alpha-alpha-finance"},"nomics":{"ALPHA":"ALPHA7"}},"to":"ETH"}} response: {"result":0.00004776590379100074,"data":{"result":0.00004776590379100074},"timestamps":{"providerDataRequestedUnixMs":1693931253591,"providerDataReceivedUnixMs":1693931253854},"statusCode":200,"meta":{"ad [...]

2023-09-11 18:18 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m52.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.3s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✓ Group-coinpaprika-BTC / ETH returned 200
     ✓ Group-coinpaprika-CRO / ETH returned 200
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-CRV / ETH returned 200
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-AMPL / ETH returned 200
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinpaprika-BNT / ETH returned 200
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-CELO / ETH returned 200
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2

     checks.........................: 97.80% ✓ 5624     ✗ 126 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.19%  ✓ 126      ✗ 5624
     http_req_blocked...............: avg=2.48µs  min=102ns   med=168ns   max=12.73ms  p(90)=278ns    p(95)=327ns   
     http_req_connecting............: avg=107ns   min=0s      med=0s      max=617.48µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=54.75ms min=1.59ms  med=3.03ms  max=2.26s    p(90)=4.92ms   p(95)=5.95ms  
       { expected_response:true }...: avg=6.38ms  min=1.59ms  med=3.01ms  max=2s       p(90)=4.7ms    p(95)=5.34ms  
   ✓ http_req_failed................: 2.19%  ✓ 126      ✗ 5624
     http_req_receiving.............: avg=87.26µs min=9.72µs  med=57.91µs max=31.78ms  p(90)=161.26µs p(95)=267.97µs
     http_req_sending...............: avg=54.28µs min=11.51µs med=37.01µs max=428.03µs p(90)=97.2µs   p(95)=179.4µs 
     http_req_tls_handshaking.......: avg=880ns   min=0s      med=0s      max=5.06ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=54.61ms min=1.5ms   med=2.9ms   max=2.26s    p(90)=4.73ms   p(95)=5.74ms  
     http_reqs......................: 5750   9.547134/s
     iteration_duration.............: avg=5.23s   min=4.99s   med=5s      max=18.99s   p(90)=5s       p(95)=5s      
     iterations.....................: 115    0.190943/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m02.3s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ANT","overrides":{"coingecko":{"ANT":"aragon"}},"to":"ETH"}} response: {"result":0.0026874262890612326,"data":{"result":0.0026874262890612326},"timestamps":{"providerDataRequestedUnixMs":1694456249504,"providerDataReceivedUnixMs":1694456249771},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"ant-aragon\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALPHA","overrides":{"coingecko":{"ALPHA":"alpha-finance"},"coinpaprika":{"ALPHA":"alpha-alpha-finance"},"nomics":{"ALPHA":"ALPHA7"}},"to":"ETH"}} response: {"result":0.00004797261208882323,"data":{"result":0.00004797261208882323},"timestamps":{"providerDataRequestedUnixMs":1694456249504,"providerDataReceivedUnixMs":1694456249771},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alpha-alpha-finance\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"endpoint":"crypto","from":"BCH","overrides":{"coingecko":{"BCH":"bitcoin-cash"},"coinpaprika":{"BCH":"bch-bitcoin-cash"}},"to":"USD"}} re [...]

2023-09-11 18:35 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m51.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.7s/10m0s

running (09m52.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.7s/10m0s

running (09m53.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.3s), 0/1 VUs, 113 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✓ Group-coinpaprika-BAL / ETH returned 200
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✓ Group-coinpaprika-ATOM / ETH returned 200
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  93% — ✓ 106 / ✗ 7
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  95% — ✓ 108 / ✗ 5
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✓ Group-coinpaprika-AXS / ETH returned 200
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  92% — ✓ 105 / ✗ 8

     checks.........................: 97.11% ✓ 5487     ✗ 163 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 801 kB 1.3 kB/s
     errors.........................: 2.88%  ✓ 163      ✗ 5487
     http_req_blocked...............: avg=2.57µs   min=107ns   med=195ns   max=12.95ms  p(90)=282ns   p(95)=331ns   
     http_req_connecting............: avg=96ns     min=0s      med=0s      max=542.53µs p(90)=0s      p(95)=0s      
   ✓ http_req_duration..............: avg=70.93ms  min=1.71ms  med=3.51ms  max=2.34s    p(90)=5.63ms  p(95)=6.75ms  
       { expected_response:true }...: avg=6.91ms   min=1.71ms  med=3.48ms  max=2.13s    p(90)=5.29ms  p(95)=5.97ms  
   ✓ http_req_failed................: 2.88%  ✓ 163      ✗ 5487
     http_req_receiving.............: avg=123.72µs min=9.74µs  med=54.19µs max=37.31ms  p(90)=164µs   p(95)=272.65µs
     http_req_sending...............: avg=79.76µs  min=15.75µs med=41µs    max=93.66ms  p(90)=96.55µs p(95)=173.85µs
     http_req_tls_handshaking.......: avg=771ns    min=0s      med=0s      max=4.35ms   p(90)=0s      p(95)=0s      
     http_req_waiting...............: avg=70.72ms  min=1.58ms  med=3.38ms  max=2.34s    p(90)=5.41ms  p(95)=6.44ms  
     http_reqs......................: 5650   9.412588/s
     iteration_duration.............: avg=5.31s    min=4.99s   med=5s      max=19.22s   p(90)=5s      p(95)=5.67s   
     iterations.....................: 113    0.188252/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m00.3s), 0/1 VUs, 113 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"crypto","from":"BAT","overrides":{"coingecko":{"BAT":"basic-attention-token"},"coinpaprika":{"BAT":"bat-basic-attention-token"}},"to":"USD"}} response: {"result":0.16110684833319233,"data":{"result":0.16110684833319233},"timestamps":{"providerDataRequestedUnixMs":1694457311385,"providerDataReceivedUnixMs":1694457311667},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bat-basic-attention-token\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ARPA","to":"USD"}} response: {"result":0.04422125378348411,"data":{"result":0.04422125378348411},"timestamps":{"providerDataRequestedUnixMs":1694457311385,"providerDataReceivedUnixMs":1694457311667},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"arpa-arpa-chain\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALBT","to":"USD"}} response: {"result":0.0013355643812491807,"data":{"result":0.0013355643812491807},"timestamps":{"providerDataRequestedUnixMs":1694457311385,"providerDataReceivedUnixM [...]

2023-09-11 19:28 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.9s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-BAL / USD returned 200
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinpaprika-ALUSD / USD returned 200
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2

     checks.........................: 97.42% ✓ 5602     ✗ 148 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.57%  ✓ 148      ✗ 5602
     http_req_blocked...............: avg=17.69µs min=103ns   med=204ns   max=100.1ms  p(90)=309ns    p(95)=348ns   
     http_req_connecting............: avg=160ns   min=0s      med=0s      max=924.24µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=63.93ms min=1.55ms  med=3.11ms  max=2.31s    p(90)=5.28ms   p(95)=6.79ms  
       { expected_response:true }...: avg=6.92ms  min=1.55ms  med=3.08ms  max=2.11s    p(90)=4.99ms   p(95)=5.76ms  
   ✓ http_req_failed................: 2.57%  ✓ 148      ✗ 5602
     http_req_receiving.............: avg=87.03µs min=9.63µs  med=62.65µs max=4.18ms   p(90)=150.44µs p(95)=201.04µs
     http_req_sending...............: avg=59.71µs min=14.49µs med=43.21µs max=1.67ms   p(90)=98.6µs   p(95)=175.41µs
     http_req_tls_handshaking.......: avg=783ns   min=0s      med=0s      max=4.5ms    p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=63.78ms min=1.46ms  med=2.98ms  max=2.31s    p(90)=5.07ms   p(95)=6.57ms  
     http_reqs......................: 5750   9.552618/s
     iteration_duration.............: avg=5.23s   min=4.99s   med=5s      max=18.52s   p(90)=5s       p(95)=5.46s   
     iterations.....................: 115    0.191052/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m01.9s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"BAL","to":"ETH"}} response: {"result":0.0020356954948146924,"data":{"result":0.0020356954948146924},"timestamps":{"providerDataRequestedUnixMs":1694460442303,"providerDataReceivedUnixMs":1694460442591},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bal-balancer\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BUSD","to":"USD"}} response: {"result":1.0000129789540113,"data":{"result":1.0000129789540113},"timestamps":{"providerDataRequestedUnixMs":1694460463040,"providerDataReceivedUnixMs":1694460463315},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"busd-binance-usd\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BORING","to":"USD"}} response: {"result":0.0019610551301624643,"data":{"result":0.0019610551301624643},"timestamps":{"providerDataRequestedUnixMs":1694460463040,"providerDataReceivedUnixMs":1694460463315},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"boring-boringdao\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"A [...]

2023-09-15 22:08 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m55.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.4s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.4s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-COMP / USD returned 200
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✓ Group-coinpaprika-BORING / USD returned 200
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-AUDIO / USD returned 200
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3

     checks.........................: 97.12% ✓ 5536     ✗ 164 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.87%  ✓ 164      ✗ 5536
     http_req_blocked...............: avg=2.71µs  min=109ns   med=158ns   max=14.03ms  p(90)=243ns    p(95)=309ns   
     http_req_connecting............: avg=147ns   min=0s      med=0s      max=841.01µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=69.46ms min=1.66ms  med=3.29ms  max=2.3s     p(90)=6.11ms   p(95)=9.83ms  
       { expected_response:true }...: avg=5.67ms  min=1.66ms  med=3.25ms  max=1.42s    p(90)=5.59ms   p(95)=6.93ms  
   ✓ http_req_failed................: 2.87%  ✓ 164      ✗ 5536
     http_req_receiving.............: avg=81.13µs min=10.83µs med=65.95µs max=6.58ms   p(90)=138.19µs p(95)=155.12µs
     http_req_sending...............: avg=54.66µs min=15.84µs med=34.78µs max=653.26µs p(90)=109.91µs p(95)=193.99µs
     http_req_tls_handshaking.......: avg=1.01µs  min=0s      med=0s      max=5.78ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=69.32ms min=1.6ms   med=3.17ms  max=2.3s     p(90)=5.93ms   p(95)=9.68ms  
     http_reqs......................: 5700   9.446352/s
     iteration_duration.............: avg=5.29s   min=4.99s   med=5s      max=18.91s   p(90)=5s       p(95)=5.07s   
     iterations.....................: 114    0.188927/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m03.4s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"CEL","to":"ETH"}} response: {"result":0.00008775813274410395,"data":{"result":0.00008775813274410395},"timestamps":{"providerDataRequestedUnixMs":1694815680003,"providerDataReceivedUnixMs":1694815680286},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cel-celsius\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BNT","to":"ETH"}} response: {"result":0.0002683830101968658,"data":{"result":0.0002683830101968658},"timestamps":{"providerDataRequestedUnixMs":1694815680003,"providerDataReceivedUnixMs":1694815680286},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bnt-bancor\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BNB","to":"USD"}} response: {"result":213.02894746481653,"data":{"result":213.02894746481653},"timestamps":{"providerDataRequestedUnixMs":1694815669635,"providerDataReceivedUnixMs":1694815669867},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bnb-binance-coin\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: { [...]

2023-09-18 14:01 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```

running (09m54.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.9s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-ALUSD / USD returned 200
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-ATOM / USD returned 200
     ✓ Group-coinpaprika-BCH / USD returned 200
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-BNT / USD returned 200
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6

     checks.........................: 96.96% ✓ 5527     ✗ 173 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 3.03%  ✓ 173      ✗ 5527
     http_req_blocked...............: avg=15.59µs min=104ns   med=168ns   max=87.3ms  p(90)=263ns    p(95)=319ns   
     http_req_connecting............: avg=12.93µs min=0s      med=0s      max=73.75ms p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=72.32ms min=1.76ms  med=3.15ms  max=2.34s   p(90)=5.23ms   p(95)=6.76ms  
       { expected_response:true }...: avg=5.26ms  min=1.76ms  med=3.12ms  max=1.63s   p(90)=4.91ms   p(95)=5.67ms  
   ✓ http_req_failed................: 3.03%  ✓ 173      ✗ 5527
     http_req_receiving.............: avg=82.54µs min=10.57µs med=55.4µs  max=42.71ms p(90)=101.73µs p(95)=142.61µs
     http_req_sending...............: avg=69.78µs min=11.06µs med=35.47µs max=93.98ms p(90)=100.56µs p(95)=182.85µs
     http_req_tls_handshaking.......: avg=1µs     min=0s      med=0s      max=5.75ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=72.17ms min=1.65ms  med=3.03ms  max=2.29s   p(90)=5.03ms   p(95)=6.58ms  
     http_reqs......................: 5700   9.454214/s
     iteration_duration.............: avg=5.28s   min=4.99s   med=5s      max=18.42s  p(90)=5s       p(95)=5.58s   
     iterations.....................: 114    0.189084/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m02.9s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ATOM","to":"USD"}} response: {"result":7.387983461439297,"data":{"result":7.387983461439297},"timestamps":{"providerDataRequestedUnixMs":1695045633746,"providerDataReceivedUnixMs":1695045634005},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"atom-cosmos\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"COMP","to":"ETH"}} response: {"result":0.02409047459037887,"data":{"result":0.02409047459037887},"timestamps":{"providerDataRequestedUnixMs":1695045623377,"providerDataReceivedUnixMs":1695045623639},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"comp-compoundd\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BTC","to":"ETH"}} response: {"result":16.4417062218409,"data":{"result":16.4417062218409},"timestamps":{"providerDataRequestedUnixMs":1695045623377,"providerDataReceivedUnixMs":1695045623639},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"btc-bitcoin\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"AXS","overrides":{"nomics": [...]

2023-09-18 14:42 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```

running (09m54.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.5s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-ARPA / USD returned 200
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-ANKR / USD returned 200
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-BAL / USD returned 200
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✓ Group-coinpaprika-ADA / USD returned 200
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2

     checks.........................: 97.10% ✓ 5535     ✗ 165 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.89%  ✓ 165      ✗ 5535
     http_req_blocked...............: avg=2.5µs   min=111ns  med=160ns   max=13.01ms  p(90)=245ns    p(95)=308ns   
     http_req_connecting............: avg=110ns   min=0s     med=0s      max=627.99µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=69.7ms  min=1.75ms med=3.12ms  max=2.3s     p(90)=5.29ms   p(95)=7.14ms  
       { expected_response:true }...: avg=5.76ms  min=1.75ms med=3.08ms  max=1.49s    p(90)=4.95ms   p(95)=5.69ms  
   ✓ http_req_failed................: 2.89%  ✓ 165      ✗ 5535
     http_req_receiving.............: avg=68.15µs min=9.73µs med=58.72µs max=2.75ms   p(90)=129.96µs p(95)=149.37µs
     http_req_sending...............: avg=53.25µs min=19.2µs med=33.87µs max=518.48µs p(90)=110.18µs p(95)=194.27µs
     http_req_tls_handshaking.......: avg=893ns   min=0s     med=0s      max=5.09ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=69.58ms min=1.62ms med=3.01ms  max=2.3s     p(90)=5.11ms   p(95)=7.04ms  
     http_reqs......................: 5700   9.445498/s
     iteration_duration.............: avg=5.29s   min=4.99s  med=5s      max=18.95s   p(90)=5s       p(95)=5.57s   
     iterations.....................: 114    0.18891/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m03.5s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ANT","overrides":{"coingecko":{"ANT":"aragon"}},"to":"ETH"}} response: {"result":0.002602178209188219,"data":{"result":0.002602178209188219},"timestamps":{"providerDataRequestedUnixMs":1695048108449,"providerDataReceivedUnixMs":1695048108816},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"ant-aragon\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BADGER","to":"USD"}} response: {"result":2.1013417912494106,"data":{"result":2.1013417912494106},"timestamps":{"providerDataRequestedUnixMs":1695048098081,"providerDataReceivedUnixMs":1695048098345},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"badger-badger\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"endpoint":"crypto","from":"BAT","overrides":{"coingecko":{"BAT":"basic-attention-token"},"coinpaprika":{"BAT":"bat-basic-attention-token"}},"to":"USD"}} response: {"result":0.1750296416435422,"data":{"result":0.1750296416435422},"timestamps":{"providerDataRequestedUnixMs":1695048098081,"providerDataReceivedUnixMs":1695048098345},"statusCode":200,"meta": [...]

2023-09-18 14:58 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.3s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.3s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-AMPL / ETH returned 200
     ✓ Group-coinpaprika-BNT / ETH returned 200
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  95% — ✓ 109 / ✗ 5

     checks.........................: 96.96% ✓ 5527     ✗ 173 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 3.03%  ✓ 173      ✗ 5527
     http_req_blocked...............: avg=4.33µs   min=118ns   med=202ns   max=23.15ms  p(90)=298ns    p(95)=373ns   
     http_req_connecting............: avg=122ns    min=0s      med=0s      max=698.02µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=72.78ms  min=1.49ms  med=3.38ms  max=2.29s    p(90)=6.1ms    p(95)=8.93ms  
       { expected_response:true }...: avg=5.68ms   min=1.49ms  med=3.34ms  max=1.6s     p(90)=5.6ms    p(95)=6.8ms   
   ✓ http_req_failed................: 3.03%  ✓ 173      ✗ 5527
     http_req_receiving.............: avg=100.43µs min=10.66µs med=59.07µs max=71.12ms  p(90)=164.31µs p(95)=275.52µs
     http_req_sending...............: avg=57.83µs  min=21.45µs med=41.35µs max=533.37µs p(90)=103.03µs p(95)=180.69µs
     http_req_tls_handshaking.......: avg=1.47µs   min=0s      med=0s      max=8.41ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=72.62ms  min=1.39ms  med=3.24ms  max=2.29s    p(90)=5.89ms   p(95)=8.73ms  
     http_reqs......................: 5700   9.447806/s
     iteration_duration.............: avg=5.29s    min=4.99s   med=5s      max=18.85s   p(90)=5s       p(95)=5.03s   
     iterations.....................: 114    0.188956/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m03.3s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"crypto","from":"C98","overrides":{"coingecko":{"C98":"coin98"},"coinpaprika":{"C98":"c98-coin98"}},"to":"USD"}} response: {"result":0.1394677865223859,"data":{"result":0.1394677865223859},"timestamps":{"providerDataRequestedUnixMs":1695049050771,"providerDataReceivedUnixMs":1695049051063},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"c98-coin98\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CELO","overrides":{"coinpaprika":{"CELO":"celo-celo"}},"to":"ETH"}} response: {"result":0.00027119793321627583,"data":{"result":0.00027119793321627583},"timestamps":{"providerDataRequestedUnixMs":1695049061139,"providerDataReceivedUnixMs":1695049061476},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"celo-celo\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ANKR","to":"USD"}} response: {"result":0.018942938299579767,"data":{"result":0.018942938299579767},"timestamps":{"providerDataRequestedUnixMs":1695049050771,"providerDataReceivedUnixMs":1695049051063},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA", [...]

2023-09-19 10:30 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m53.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinpaprika-AMP / USD returned 200
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-BADGER / USD returned 200
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✓ Group-coinpaprika-ALUSD / USD returned 200
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7

     checks.........................: 97.58% ✓ 5611     ✗ 139 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.41%  ✓ 139      ✗ 5611
     http_req_blocked...............: avg=2.66µs   min=111ns   med=168ns   max=13.94ms  p(90)=282ns    p(95)=333ns   
     http_req_connecting............: avg=98ns     min=0s      med=0s      max=568.07µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=60.05ms  min=1.34ms  med=3.06ms  max=2.31s    p(90)=5.53ms   p(95)=7.89ms  
       { expected_response:true }...: avg=6.42ms   min=1.34ms  med=3.03ms  max=2.09s    p(90)=5.19ms   p(95)=6.31ms  
   ✓ http_req_failed................: 2.41%  ✓ 139      ✗ 5611
     http_req_receiving.............: avg=93.71µs  min=9.43µs  med=67.06µs max=36.51ms  p(90)=150.32µs p(95)=177.04µs
     http_req_sending...............: avg=137.88µs min=17.25µs med=36.64µs max=77.08ms  p(90)=120.78µs p(95)=201.67µs
     http_req_tls_handshaking.......: avg=886ns    min=0s      med=0s      max=5.09ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=59.82ms  min=1.29ms  med=2.93ms  max=2.3s     p(90)=5.34ms   p(95)=7.74ms  
     http_reqs......................: 5750   9.553902/s
     iteration_duration.............: avg=5.23s    min=4.99s   med=5s      max=18.31s   p(90)=5s       p(95)=5s      
     iterations.....................: 115    0.191078/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m01.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"endpoint":"crypto","from":"BCH","overrides":{"coingecko":{"BCH":"bitcoin-cash"},"coinpaprika":{"BCH":"bch-bitcoin-cash"}},"to":"USD"}} response: {"result":219.8460559174764,"data":{"result":219.8460559174764},"timestamps":{"providerDataRequestedUnixMs":1695119355654,"providerDataReceivedUnixMs":1695119355907},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bch-bitcoin-cash\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CELO","overrides":{"coinpaprika":{"CELO":"celo-celo"}},"to":"ETH"}} response: {"result":0.0002787569238727942,"data":{"result":0.0002787569238727942},"timestamps":{"providerDataRequestedUnixMs":1695119386758,"providerDataReceivedUnixMs":1695119387026},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"celo-celo\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALUSD","overrides":{"coinpaprika":{"ALUSD":"alusd-alchemixusd"}},"to":"USD"}} response: {"result":0.9933319259413543,"data":{"result":0.9933319259413543},"timestamps":{"providerD [...]

2023-09-19 17:12 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m53.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.7s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.7s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.1s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✓ Group-coinpaprika-AMP / USD returned 200
     ✓ Group-coinpaprika-ANKR / USD returned 200
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✓ Group-coinpaprika-AAVE / USD returned 200
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7

     checks.........................: 97.42% ✓ 5602     ✗ 148 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.57%  ✓ 148      ✗ 5602
     http_req_blocked...............: avg=2.68µs   min=112ns   med=166ns   max=14.22ms  p(90)=250ns    p(95)=320ns   
     http_req_connecting............: avg=57ns     min=0s      med=0s      max=327.96µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=64.16ms  min=2.6ms   med=3.6ms   max=2.29s    p(90)=6.21ms   p(95)=8.04ms  
       { expected_response:true }...: avg=7.12ms   min=2.6ms   med=3.56ms  max=2.1s     p(90)=5.91ms   p(95)=6.75ms  
   ✓ http_req_failed................: 2.57%  ✓ 148      ✗ 5602
     http_req_receiving.............: avg=116.45µs min=10.67µs med=66.64µs max=58.31ms  p(90)=146.21µs p(95)=175.41µs
     http_req_sending...............: avg=55.51µs  min=21.84µs med=35.65µs max=608.39µs p(90)=111.89µs p(95)=199.67µs
     http_req_tls_handshaking.......: avg=1.04µs   min=0s      med=0s      max=5.98ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=63.98ms  min=2.52ms  med=3.47ms  max=2.29s    p(90)=5.96ms   p(95)=7.8ms   
     http_reqs......................: 5750   9.550435/s
     iteration_duration.............: avg=5.23s    min=4.99s   med=5s      max=18.61s   p(90)=5s       p(95)=5.03s   
     iterations.....................: 115    0.191009/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m02.1s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"CAKE","overrides":{"coingecko":{"CAKE":"pancakeswap-token"}},"to":"USD"}} response: {"result":1.1843984829151877,"data":{"result":1.1843984829151877},"timestamps":{"providerDataRequestedUnixMs":1695143473682,"providerDataReceivedUnixMs":1695143473961},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cake-pancakeswap\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"1INCH","to":"ETH"}} response: {"result":0.00015421880527903884,"data":{"result":0.00015421880527903884},"timestamps":{"providerDataRequestedUnixMs":1695143494419,"providerDataReceivedUnixMs":1695143494671},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"1inch-1inch\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CRO","to":"ETH"}} response: {"result":0.00003109624714694061,"data":{"result":0.00003109624714694061},"timestamps":{"providerDataRequestedUnixMs":1695143494419,"providerDataReceivedUnixMs":1695143494671},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedI [...]

2023-09-20 19:48 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m51.8s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.8s/10m0s

running (09m52.8s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.8s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.8s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.1s), 0/1 VUs, 113 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  93% — ✓ 106 / ✗ 7
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  93% — ✓ 106 / ✗ 7
     ✓ Group-coinpaprika-ALPHA / ETH returned 200
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✓ Group-coinpaprika-BAND / ETH returned 200
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  95% — ✓ 108 / ✗ 5
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  93% — ✓ 106 / ✗ 7
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  93% — ✓ 106 / ✗ 7
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  95% — ✓ 108 / ✗ 5
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  92% — ✓ 105 / ✗ 8
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  94% — ✓ 107 / ✗ 6
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  95% — ✓ 108 / ✗ 5
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  99% — ✓ 112 / ✗ 1
     ✓ Group-coinpaprika-ATOM / ETH returned 200
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 111 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  97% — ✓ 110 / ✗ 3
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  92% — ✓ 105 / ✗ 8

     checks.........................: 96.83% ✓ 5471     ✗ 179 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 800 kB 1.3 kB/s
     errors.........................: 3.16%  ✓ 179      ✗ 5471
     http_req_blocked...............: avg=2.53µs  min=110ns   med=172ns   max=12.92ms  p(90)=266ns    p(95)=344ns   
     http_req_connecting............: avg=65ns    min=0s      med=0s      max=369.75µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=75.15ms min=1.99ms  med=3.11ms  max=2.34s    p(90)=5.27ms   p(95)=6.4ms   
       { expected_response:true }...: avg=4.94ms  min=1.99ms  med=3.06ms  max=1.65s    p(90)=4.92ms   p(95)=5.59ms  
   ✓ http_req_failed................: 3.16%  ✓ 179      ✗ 5471
     http_req_receiving.............: avg=78.89µs min=10.38µs med=62.52µs max=7.7ms    p(90)=136.04µs p(95)=154.5µs 
     http_req_sending...............: avg=52.7µs  min=16.45µs med=33.31µs max=3.9ms    p(90)=95.87µs  p(95)=186.22µs
     http_req_tls_handshaking.......: avg=1.05µs  min=0s      med=0s      max=5.93ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=75.02ms min=1.92ms  med=2.99ms  max=2.34s    p(90)=5.06ms   p(95)=6.26ms  
     http_reqs......................: 5650   9.415407/s
     iteration_duration.............: avg=5.31s   min=4.99s   med=5s      max=18.32s   p(90)=5s       p(95)=5.66s   
     iterations.....................: 113    0.188308/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m00.1s), 0/1 VUs, 113 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ANKR","to":"USD"}} response: {"result":0.019367603729313187,"data":{"result":0.019367603729313187},"timestamps":{"providerDataRequestedUnixMs":1695239268944,"providerDataReceivedUnixMs":1695239269207},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"ankr-ankr-network\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BAL","to":"ETH"}} response: {"result":0.0019939033641604097,"data":{"result":0.0019939033641604097},"timestamps":{"providerDataRequestedUnixMs":1695239258576,"providerDataReceivedUnixMs":1695239258899},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bal-balancer\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BNT","to":"USD"}} response: {"result":0.40703568085212993,"data":{"result":0.40703568085212993},"timestamps":{"providerDataRequestedUnixMs":1695239268944,"providerDataReceivedUnixMs":1695239269207},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bnt-bancor\",\"quote\":\"usd\",\"r [...]

2023-09-21 08:29 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.9s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-ADA / USD returned 200
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✓ Group-coinpaprika-BCH / USD returned 200
     ✓ Group-coinpaprika-CRO / USD returned 200
     ✓ Group-coinpaprika-COMP / USD returned 200
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-BNT / USD returned 200
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7

     checks.........................: 97.19% ✓ 5540     ✗ 160 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.80%  ✓ 160      ✗ 5540
     http_req_blocked...............: avg=16.77µs min=116ns   med=174ns   max=94.18ms  p(90)=270ns    p(95)=318ns   
     http_req_connecting............: avg=80ns    min=0s      med=0s      max=460.15µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=68.62ms min=2.19ms  med=3.34ms  max=2.31s    p(90)=5.63ms   p(95)=7.37ms  
       { expected_response:true }...: avg=6.55ms  min=2.19ms  med=3.3ms   max=1.61s    p(90)=5.33ms   p(95)=6.05ms  
   ✓ http_req_failed................: 2.80%  ✓ 160      ✗ 5540
     http_req_receiving.............: avg=82.52µs min=10.93µs med=60.46µs max=5.72ms   p(90)=153.06µs p(95)=261.78µs
     http_req_sending...............: avg=60.04µs min=18.91µs med=35.03µs max=26.67ms  p(90)=107.53µs p(95)=192.64µs
     http_req_tls_handshaking.......: avg=15µs    min=0s      med=0s      max=85.5ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=68.47ms min=2.08ms  med=3.22ms  max=2.31s    p(90)=5.43ms   p(95)=7.13ms  
     http_reqs......................: 5700   9.423279/s
     iteration_duration.............: avg=5.3s    min=4.99s   med=5s      max=18.86s   p(90)=5s       p(95)=5.58s   
     iterations.....................: 114    0.188466/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m04.9s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ADA","to":"USD"}} response: {"result":0.24977267265947864,"data":{"result":0.24977267265947864},"timestamps":{"providerDataRequestedUnixMs":1695284893988,"providerDataReceivedUnixMs":1695284894213},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"ada-cardano\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CAKE","overrides":{"coingecko":{"CAKE":"pancakeswap-token"}},"to":"USD"}} response: {"result":1.1661431238353093,"data":{"result":1.1661431238353093},"timestamps":{"providerDataRequestedUnixMs":1695284893988,"providerDataReceivedUnixMs":1695284894213},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cake-pancakeswap\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"1INCH","to":"ETH"}} response: {"result":0.00016961857273615688,"data":{"result":0.00016961857273615688},"timestamps":{"providerDataRequestedUnixMs":1695284904356,"providerDataReceivedUnixMs":1695284904588},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"1inch-1inch\",\"quote\":\"eth\",\"resu [...]

2023-09-21 12:21 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```

running (09m52.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.8s/10m0s

running (09m53.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.8s/10m0s

running (09m54.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.8s/10m0s

running (09m55.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.8s/10m0s

running (09m56.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.0s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-BNB / USD returned 200
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✓ Group-coinpaprika-CRO / USD returned 200
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✓ Group-coinpaprika-BAT / USD returned 200
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  0% — ✓ 0 / ✗ 115
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✓ Group-coinpaprika-ALCX / USD returned 200

     checks.........................: 95.68% ✓ 5502     ✗ 248 
     data_received..................: 2.7 MB 4.5 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 4.31%  ✓ 248      ✗ 5502
     http_req_blocked...............: avg=2.73µs   min=112ns   med=163ns   max=14.45ms  p(90)=274ns    p(95)=321ns   
     http_req_connecting............: avg=82ns     min=0s      med=0s      max=471.64µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=57.9ms   min=1.36ms  med=2.99ms  max=2.3s     p(90)=5.29ms   p(95)=7.44ms  
       { expected_response:true }...: avg=5.83ms   min=1.36ms  med=2.96ms  max=2.09s    p(90)=4.96ms   p(95)=5.95ms  
   ✓ http_req_failed................: 4.31%  ✓ 248      ✗ 5502
     http_req_receiving.............: avg=120.37µs min=9.52µs  med=62.5µs  max=68.47ms  p(90)=144.81µs p(95)=187.55µs
     http_req_sending...............: avg=57.01µs  min=21.46µs med=37.84µs max=473.56µs p(90)=109.42µs p(95)=196.07µs
     http_req_tls_handshaking.......: avg=1.02µs   min=0s      med=0s      max=5.88ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=57.73ms  min=1.18ms  med=2.86ms  max=2.3s     p(90)=5.1ms    p(95)=7.21ms  
     http_reqs......................: 5750   9.566706/s
     iteration_duration.............: avg=5.22s    min=4.99s   med=5s      max=19.14s   p(90)=5s       p(95)=5s      
     iterations.....................: 115    0.191334/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m01.0s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"AVAX","to":"USD"}} response: {"result":8.87498236809665,"data":{"result":8.87498236809665},"timestamps":{"providerDataRequestedUnixMs":1695298854948,"providerDataReceivedUnixMs":1695298855416},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"avax-avalanche\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CRO","to":"USD"}} response: {"result":0.05088415822793606,"data":{"result":0.05088415822793606},"timestamps":{"providerDataRequestedUnixMs":1695298854948,"providerDataReceivedUnixMs":1695298855416},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cro-cryptocom-chain\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALCX","to":"ETH"}} response: {"result":0.007476554424707435,"data":{"result":0.007476554424707435},"timestamps":{"providerDataRequestedUnixMs":1695298865317,"providerDataReceivedUnixMs":1695298865567},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alcx-alchemix\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
re [...]

2023-09-21 14:43 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.8s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coinpaprika-ATOM / ETH returned 200
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-AAVE / ETH returned 200
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1

     checks.........................: 97.14% ✓ 5537     ✗ 163 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.85%  ✓ 163      ✗ 5537
     http_req_blocked...............: avg=2.57µs  min=101ns   med=162ns   max=13.24ms  p(90)=260ns    p(95)=326ns   
     http_req_connecting............: avg=79ns    min=0s      med=0s      max=455.1µs  p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=70.29ms min=1.44ms  med=3.12ms  max=2.33s    p(90)=5.34ms   p(95)=7.53ms  
       { expected_response:true }...: avg=6.76ms  min=1.44ms  med=3.08ms  max=2.13s    p(90)=5.01ms   p(95)=5.73ms  
   ✓ http_req_failed................: 2.85%  ✓ 163      ✗ 5537
     http_req_receiving.............: avg=81.69µs min=9.53µs  med=52.96µs max=37.96ms  p(90)=120.89µs p(95)=243.57µs
     http_req_sending...............: avg=52.69µs min=14.59µs med=34.13µs max=608.43µs p(90)=99.96µs  p(95)=187.88µs
     http_req_tls_handshaking.......: avg=926ns   min=0s      med=0s      max=5.28ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=70.15ms min=1.36ms  med=3.02ms  max=2.33s    p(90)=5.17ms   p(95)=7.37ms  
     http_reqs......................: 5700   9.425176/s
     iteration_duration.............: avg=5.3s    min=4.99s   med=5s      max=18.74s   p(90)=5s       p(95)=5.58s   
     iterations.....................: 114    0.188504/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m04.8s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"BTC","to":"ETH"}} response: {"result":16.758149666682485,"data":{"result":16.758149666682485},"timestamps":{"providerDataRequestedUnixMs":1695307353332,"providerDataReceivedUnixMs":1695307353595},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"btc-bitcoin\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALBT","to":"USD"}} response: {"result":0.001247021283529381,"data":{"result":0.001247021283529381},"timestamps":{"providerDataRequestedUnixMs":1695307363700,"providerDataReceivedUnixMs":1695307364007},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"albt-allianceblock\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"CRO","to":"USD"}} response: {"result":0.050610861263714384,"data":{"result":0.050610861263714384},"timestamps":{"providerDataRequestedUnixMs":1695307363700,"providerDataReceivedUnixMs":1695307364007},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cro-cryptocom-chain\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BNB","to":"USD"}} response: {"r [...]

2023-09-21 15:16 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m56.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.8s/10m0s

running (09m57.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.8s/10m0s

running (09m58.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.8s/10m0s

running (09m59.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.8s/10m0s

running (10m00.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m05.0s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-BAND / USD returned 200
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✓ Group-coinpaprika-AUDIO / USD returned 200
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-ALUSD / USD returned 200
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1

     checks.........................: 97.10% ✓ 5535     ✗ 165 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.89%  ✓ 165      ✗ 5535
     http_req_blocked...............: avg=2.35µs  min=113ns   med=185ns   max=11.97ms  p(90)=319ns    p(95)=350ns   
     http_req_connecting............: avg=95ns    min=0s      med=0s      max=546.36µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=68.85ms min=1.74ms  med=3.17ms  max=2.29s    p(90)=5.47ms   p(95)=7.77ms  
       { expected_response:true }...: avg=4.94ms  min=1.74ms  med=3.15ms  max=1.6s     p(90)=5.07ms   p(95)=5.96ms  
   ✓ http_req_failed................: 2.89%  ✓ 165      ✗ 5535
     http_req_receiving.............: avg=97.41µs min=9.71µs  med=65.17µs max=46.81ms  p(90)=148.61µs p(95)=180.19µs
     http_req_sending...............: avg=66.69µs min=21.54µs med=40.69µs max=43.31ms  p(90)=109.63µs p(95)=187.87µs
     http_req_tls_handshaking.......: avg=706ns   min=0s      med=0s      max=4.02ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=68.69ms min=1.66ms  med=3.04ms  max=2.29s    p(90)=5.23ms   p(95)=7.56ms  
     http_reqs......................: 5700   9.421669/s
     iteration_duration.............: avg=5.3s    min=4.99s   med=5s      max=18.94s   p(90)=5s       p(95)=5.58s   
     iterations.....................: 114    0.188433/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m05.0s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ALCX","to":"ETH"}} response: {"result":0.007438749628263983,"data":{"result":0.007438749628263983},"timestamps":{"providerDataRequestedUnixMs":1695309366600,"providerDataReceivedUnixMs":1695309366858},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alcx-alchemix\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BUSD","to":"ETH"}} response: {"result":0.0006312750984033786,"data":{"result":0.0006312750984033786},"timestamps":{"providerDataRequestedUnixMs":1695309366600,"providerDataReceivedUnixMs":1695309366858},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"busd-binance-usd\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BUSD","to":"USD"}} response: {"result":1.0008184608372668,"data":{"result":1.0008184608372668},"timestamps":{"providerDataRequestedUnixMs":1695309376968,"providerDataReceivedUnixMs":1695309377240},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"busd-binance-usd\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"d [...]

2023-09-21 16:07 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```

running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m04.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m05.0s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✓ Group-coinpaprika-BUSD / USD returned 200
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✓ Group-coinpaprika-AMP / USD returned 200
     ✓ Group-coinpaprika-BAL / USD returned 200
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✓ Group-coinpaprika-BAT / USD returned 200
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  93% — ✓ 107 / ✗ 7
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8

     checks.........................: 96.96% ✓ 5527     ✗ 173 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 3.03%  ✓ 173      ✗ 5527
     http_req_blocked...............: avg=2.95µs  min=110ns   med=188ns   max=15.3ms   p(90)=288ns    p(95)=394ns   
     http_req_connecting............: avg=68ns    min=0s      med=0s      max=389.54µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=72.69ms min=1.94ms  med=3.49ms  max=2.26s    p(90)=6.2ms    p(95)=9.54ms  
       { expected_response:true }...: avg=5.5ms   min=1.94ms  med=3.45ms  max=1.65s    p(90)=5.76ms   p(95)=6.91ms  
   ✓ http_req_failed................: 3.03%  ✓ 173      ✗ 5527
     http_req_receiving.............: avg=80.46µs min=8.93µs  med=58.67µs max=35.76ms  p(90)=112.32µs p(95)=151.97µs
     http_req_sending...............: avg=60.73µs min=20.17µs med=35.26µs max=41.83ms  p(90)=105.38µs p(95)=187.99µs
     http_req_tls_handshaking.......: avg=999ns   min=0s      med=0s      max=5.69ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=72.55ms min=1.87ms  med=3.38ms  max=2.26s    p(90)=5.99ms   p(95)=9.1ms   
     http_reqs......................: 5700   9.421788/s
     iteration_duration.............: avg=5.3s    min=4.99s   med=5s      max=18.19s   p(90)=5s       p(95)=5.58s   
     iterations.....................: 114    0.188436/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m05.0s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"AAVE","to":"ETH"}} response: {"result":0.04000418245513673,"data":{"result":0.04000418245513673},"timestamps":{"providerDataRequestedUnixMs":1695312436883,"providerDataReceivedUnixMs":1695312437147},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"aave-new\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BADGER","to":"USD"}} response: {"result":1.9965667526096835,"data":{"result":1.9965667526096835},"timestamps":{"providerDataRequestedUnixMs":1695312426514,"providerDataReceivedUnixMs":1695312426818},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"badger-badger\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BAL","to":"USD"}} response: {"result":3.156791781296412,"data":{"result":3.156791781296412},"timestamps":{"providerDataRequestedUnixMs":1695312426514,"providerDataReceivedUnixMs":1695312426818},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"bal-balancer\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BNB","to":"USD"}} response: {"res [...]

2023-09-25 05:46 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```

running (09m54.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.6s/10m0s

running (09m55.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinpaprika-1INCH / ETH returned 200
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-BNB / ETH returned 200
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✓ Group-coinpaprika-BUSD / ETH returned 200
     ✓ Group-coinpaprika-AAVE / ETH returned 200
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  95% — ✓ 110 / ✗ 5
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7

     checks.........................: 97.54% ✓ 5609     ✗ 141 
     data_received..................: 2.7 MB 4.4 kB/s
     data_sent......................: 815 kB 1.4 kB/s
     errors.........................: 2.45%  ✓ 141      ✗ 5609
     http_req_blocked...............: avg=17.4µs   min=115ns   med=180ns   max=98.75ms  p(90)=298ns    p(95)=352ns   
     http_req_connecting............: avg=98ns     min=0s      med=0s      max=568.45µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=59.59ms  min=1.12ms  med=3.38ms  max=2.3s     p(90)=6.67ms   p(95)=10.1ms  
       { expected_response:true }...: avg=5.2ms    min=1.12ms  med=3.34ms  max=2.09s    p(90)=6.11ms   p(95)=7.87ms  
   ✓ http_req_failed................: 2.45%  ✓ 141      ✗ 5609
     http_req_receiving.............: avg=100.21µs min=10.14µs med=59.85µs max=48.65ms  p(90)=141.05µs p(95)=215.86µs
     http_req_sending...............: avg=77.49µs  min=10.63µs med=40.77µs max=80.48ms  p(90)=125.59µs p(95)=220.23µs
     http_req_tls_handshaking.......: avg=1.5µs    min=0s      med=0s      max=8.63ms   p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=59.41ms  min=1.04ms  med=3.24ms  max=2.3s     p(90)=6.44ms   p(95)=9.88ms  
     http_reqs......................: 5750   9.54088/s
     iteration_duration.............: avg=5.24s    min=4.99s   med=5s      max=18.42s   p(90)=5s       p(95)=5s      
     iterations.....................: 115    0.190818/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m02.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"CEL","to":"ETH"}} response: {"result":0.00008740029095255817,"data":{"result":0.00008740029095255817},"timestamps":{"providerDataRequestedUnixMs":1695620767903,"providerDataReceivedUnixMs":1695620768164},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"cel-celsius\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BUSD","to":"ETH"}} response: {"result":0.0006343407435637099,"data":{"result":0.0006343407435637099},"timestamps":{"providerDataRequestedUnixMs":1695620767903,"providerDataReceivedUnixMs":1695620768164},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"busd-binance-usd\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"ALCX","to":"USD"}} response: {"result":12.621240118871619,"data":{"result":12.621240118871619},"timestamps":{"providerDataRequestedUnixMs":1695620788639,"providerDataReceivedUnixMs":1695620788907},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alcx-alchemix\",\"quote\":\"usd\",\"resultPath\":\"price\"}"}}}
request: {"dat [...]

2023-09-25 06:10 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m55.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.6s/10m0s

running (09m56.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.6s/10m0s

running (09m57.6s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.6s/10m0s

running (09m58.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.6s/10m0s

running (09m59.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.6s/10m0s

running (10m00.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.6s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.5s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.5s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-ALCX / USD returned 200
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✓ Group-coinpaprika-CAKE / USD returned 200
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / USD returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✓ Group-coinpaprika-AVAX / USD returned 200
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  95% — ✓ 109 / ✗ 5
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AAVE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  94% — ✓ 108 / ✗ 6

     checks.........................: 97.08% ✓ 5534     ✗ 166 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.91%  ✓ 166      ✗ 5534
     http_req_blocked...............: avg=5.05µs  min=108ns   med=168ns   max=27.33ms  p(90)=256ns    p(95)=309ns   
     http_req_connecting............: avg=94ns    min=0s      med=0s      max=539.93µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=70.7ms  min=1.87ms  med=3.41ms  max=2.27s    p(90)=6.14ms   p(95)=9.25ms  
       { expected_response:true }...: avg=6.22ms  min=1.87ms  med=3.37ms  max=2.11s    p(90)=5.67ms   p(95)=6.98ms  
   ✓ http_req_failed................: 2.91%  ✓ 166      ✗ 5534
     http_req_receiving.............: avg=90.61µs min=10.39µs med=63.81µs max=24.85ms  p(90)=147.11µs p(95)=201.44µs
     http_req_sending...............: avg=56.75µs min=10.96µs med=36.09µs max=678.31µs p(90)=115.31µs p(95)=204.04µs
     http_req_tls_handshaking.......: avg=2.4µs   min=0s      med=0s      max=13.71ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=70.56ms min=1.76ms  med=3.28ms  max=2.27s    p(90)=5.91ms   p(95)=9.02ms  
     http_reqs......................: 5700   9.444942/s
     iteration_duration.............: avg=5.29s   min=4.99s   med=5s      max=19.06s   p(90)=5s       p(95)=5.54s   
     iterations.....................: 114    0.188899/s
     vus............................: 1      min=0      max=1 
     vus_max........................: 1      min=0      max=1 


running (10m03.5s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ALPHA","overrides":{"coingecko":{"ALPHA":"alpha-finance"},"coinpaprika":{"ALPHA":"alpha-alpha-finance"},"nomics":{"ALPHA":"ALPHA7"}},"to":"ETH"}} response: {"result":0.00004838055085122463,"data":{"result":0.00004838055085122463},"timestamps":{"providerDataRequestedUnixMs":1695622198354,"providerDataReceivedUnixMs":1695622198608},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"alpha-alpha-finance\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BTC","to":"ETH"}} response: {"result":16.570342528361248,"data":{"result":16.570342528361248},"timestamps":{"providerDataRequestedUnixMs":1695622198354,"providerDataReceivedUnixMs":1695622198608},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"btc-bitcoin\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BIT","overrides":{"coinpaprika":{"BIT":"bit-bitdao"},"nomics":{"BIT":"BIT2"},"tiingo":{"BIT":"BITDAO"}},"to":"USD"}} response: {"result":0.3904944160172158,"data":{"result":0.3904944160172158},"timestamps":{"providerDataRequeste [...]

2023-09-25 06:44 UTC, cl-ea-js-service commented
<details><summary>:heavy_check_mark: Soak test for coinpaprika succeeded</summary>

```
running (09m55.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.7s/10m0s

running (09m56.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.7s/10m0s

running (09m57.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.7s/10m0s

running (09m58.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.7s/10m0s

running (09m59.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.7s/10m0s

running (10m00.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m01.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinpaprika-BAND / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BTC / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-APE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-AMPL / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AXS / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-CREAM / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ALCX / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✓ Group-coinpaprika-BAL / USD returned 200
     ✗ Group-coinpaprika-BAND / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BIT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BAL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BAT / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ALUSD / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CRO / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-AVAX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BORING / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ANT / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BCH / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ADX / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✓ Group-coinpaprika-COMP / USD returned 200
     ✗ Group-coinpaprika-CRV / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-BNB / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-AUDIO / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ADA / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-ALPHA / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ATOM / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-BAT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-CEL / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-COMP / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BUSD / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-CRO / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AMPL / ETH returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✓ Group-coinpaprika-AAVE / USD returned 200
     ✗ Group-coinpaprika-ALCX / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-ALBT / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-1INCH / ETH returned 200
      ↳  97% — ✓ 111 / ✗ 3
     ✗ Group-coinpaprika-C98 / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AAVE / ETH returned 200
      ↳  94% — ✓ 108 / ✗ 6
     ✗ Group-coinpaprika-ANKR / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-CELO / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BNB / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-ARPA / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-BNT / USD returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-CAKE / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BNT / ETH returned 200
      ↳  99% — ✓ 113 / ✗ 1
     ✗ Group-coinpaprika-ATOM / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2
     ✗ Group-coinpaprika-BADGER / USD returned 200
      ↳  92% — ✓ 106 / ✗ 8
     ✗ Group-coinpaprika-AMP / USD returned 200
      ↳  98% — ✓ 112 / ✗ 2

     checks.........................: 97.10% ✓ 5535    ✗ 165 
     data_received..................: 2.6 MB 4.4 kB/s
     data_sent......................: 808 kB 1.3 kB/s
     errors.........................: 2.89%  ✓ 165     ✗ 5535
     http_req_blocked...............: avg=1.33µs  min=106ns   med=159ns   max=6.33ms  p(90)=248ns    p(95)=308ns   
     http_req_connecting............: avg=89ns    min=0s      med=0s      max=512.9µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=69.31ms min=1.24ms  med=3.09ms  max=2.29s   p(90)=5.72ms   p(95)=8.86ms  
       { expected_response:true }...: avg=5.18ms  min=1.24ms  med=3.06ms  max=1.41s   p(90)=5.3ms    p(95)=6.43ms  
   ✓ http_req_failed................: 2.89%  ✓ 165     ✗ 5535
     http_req_receiving.............: avg=81.2µs  min=9.88µs  med=67.47µs max=3.83ms  p(90)=144.43µs p(95)=164.53µs
     http_req_sending...............: avg=55.28µs min=15.23µs med=35.17µs max=552.9µs p(90)=112.78µs p(95)=203.54µs
     http_req_tls_handshaking.......: avg=999ns   min=0s      med=0s      max=5.69ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=69.17ms min=1.14ms  med=2.97ms  max=2.29s   p(90)=5.53ms   p(95)=8.63ms  
     http_reqs......................: 5700   9.44202/s
     iteration_duration.............: avg=5.29s   min=4.99s   med=5s      max=19.07s  p(90)=5s       p(95)=5.58s   
     iterations.....................: 114    0.18884/s
     vus............................: 1      min=0     max=1 
     vus_max........................: 1      min=0     max=1 


running (10m03.7s), 0/1 VUs, 114 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s
```
</details>

<details><summary>:heavy_check_mark: Assertions loaded: 1, applied: 1</summary>

```
Applied:
Assertion applied: {"request":{},"expectedResponse":{"result":{"greaterThan":0}}}

Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```
request: {"data":{"from":"ATOM","to":"ETH"}} response: {"result":0.004442338052101687,"data":{"result":0.004442338052101687},"timestamps":{"providerDataRequestedUnixMs":1695624222162,"providerDataReceivedUnixMs":1695624222402},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"atom-cosmos\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BAND","overrides":{"coingecko":{"BAND":"band-protocol"},"coinpaprika":{"BAND":"band-band-protocol"}},"to":"ETH"}} response: {"result":0.0006698707444890427,"data":{"result":0.0006698707444890427},"timestamps":{"providerDataRequestedUnixMs":1695624222162,"providerDataReceivedUnixMs":1695624222402},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feedId":"{\"base\":\"band-band-protocol\",\"quote\":\"eth\",\"resultPath\":\"price\"}"}}}
request: {"data":{"from":"BORING","to":"USD"}} response: {"result":0.0017993323707022001,"data":{"result":0.0017993323707022001},"timestamps":{"providerDataRequestedUnixMs":1695624211794,"providerDataReceivedUnixMs":1695624212036},"statusCode":200,"meta":{"adapterName":"COINPAPRIKA","metrics":{"feed [...]

2023-09-25 17:29 UTC, austinborn requested changes
Need to wait on current deployed feeds to ensure operators aren't relying on the default

2024-10-15 15:30 UTC, closed without merging