docs(README): add list adapters section
smartcontractkit/external-adapters-js pull request #3219
Opened 2024-03-08 10:32 UTC by czar0

## Closes #3218

## Description

A section in the README to explain how to generate a list of all available adapters.

## Changes

A bunch of lines in the README (only docs) and one line in .gitignore.

## Steps to Test

N/A

## Quality Assurance

N/A

2024-03-20 06:47 UTC, karen-stepanyan commented
Hey @czar0 . Thanks for opening the PR. What's the intention of this change ? The `MASTERLIST.md` is created/updated automatically after every release, so it contains up-to-date information and is available at a root level. Why would anyone want to generate it manually ?

2024-03-21 10:04 UTC, czar0 commented
oh, shoot! I wondered whether that script was even called anywhere😄 (apologies). Anyway, this unclarity builds even a stronger case for this simple addition. The intent is to slightly improve the user experience by presenting to the end user a list of available adapters (the culprit `MASTERLIST.md`).
Put it in a story format: _As an end user, I want to have a concise list of available external adapters and their properties so that I can quickly understand their purpose and start using them_.
I believe a small addition to the README should be enough (changes just pushed).
Let me know if that makes sense to you.

2024-03-21 11:38 UTC, karen-stepanyan requested changes
I agree that we can include information about Masterlist in the main readme. Suggested a minot change

2024-03-21 11:38 UTC, karen-stepanyan commented on README.md
> +The [MASTERLIST.md](./MASTERLIST.md) file in the root directory contains the list of all the external adapters available in this repository, together with their version, type, level of support, and o
Do you mind to change this to 
```suggestion
The [MASTERLIST.md](./MASTERLIST.md) file in the root directory contains the list of all the external adapters available in this repository, together with their version, type, supported environment variables, endpoints and other helpful information. Check their linked README to learn more about them.
```

2024-03-21 14:32 UTC, karen-stepanyan approved these changes

2024-03-21 14:34 UTC, merged