Update CVI
smartcontractkit/external-adapters-js pull request #499
Opened 2021-05-06 14:05 UTC by vladi-coti

improved the time resolution from days to seconds and smooth-out the effect of added strikes

2021-06-03 09:57 UTC, boxhock requested changes
Thanks for submitting this PR! Left a few comments

2021-06-03 12:30 UTC, vladi-coti commented
Fixed requested changed

2021-06-03 13:09 UTC, boxhock requested changes
Just a couple more things I noticed in the test. Besides this we should be good, and I'll merge once fixed.

2021-06-03 13:09 UTC, boxhock commented on packages/composites/crypto-volatility-index/test/integration/adapter.test.ts
> +  process.env.COINGECKO_DATA_PROVIDER_URL = 'http://localhost:3000'
We should not hard-code this env var, instead we should have it set when running the test.

```suggestion
```

2021-06-03 13:09 UTC, boxhock commented on packages/composites/crypto-volatility-index/test/integration/adapter.test.ts
> +jest.setTimeout(10000)
This should also be set when running the test, instead of hard-coding here

```suggestion
```

2021-06-03 13:24 UTC, boxhock commented
@vladi-coti looks like you'll have to rebase as well, as I can't merge if the branch is out of date with the base branch

2021-06-03 13:41 UTC, boxhock approved these changes

2021-06-03 13:41 UTC, merged

2021-07-02 18:30 UTC, justinkaseman commented
Hey @vladi-coti, we are currently hitting a scenario where `https://www.deribit.com/api/v2/public/get_book_summary_by_currency` only returns one `expiration` timestamp that passes
```
      olderThanHour(instrumentName, hourAgo, instruments) &&
        moment.unix(expiration).weekday() == 5
```
making this check fail

```
  if (!e1) throw new Error('Could not find an expiration date before a full month')
  if (!e2) throw new Error('Could not find an expiration date after a full month')
```

How would you like to proceed?