augur: adjust rundown adapter
smartcontractkit/external-adapters-js pull request #773
Opened 2021-08-09 18:53 UTC by pgebheim

2021-08-10 22:31 UTC, pgebheim commented
@boxhock This needs review

2021-08-11 18:20 UTC, robert-e-davidson3 requested changes

2021-08-11 18:25 UTC, pgebheim commented on packages/composites/augur/src/methods/resolveMarkets.ts
> +    Logger.debug(`Augur: status info`, {id: id.toHexString().slice(2), status, needs_resolve: statusCompleted.includes(status)})
```
const statusCompleted = [
  4, // Cancelled
  2, // Final
  3 // Postponed
]
```

It is there -- SUSPENDED maps to `4` (Canceled)

2021-08-11 18:43 UTC, robert-e-davidson3 approved these changes

2021-08-11 21:38 UTC, boxhock approved these changes

2021-08-11 21:38 UTC, merged