Upvest.gasprice
smartcontractkit/external-adapters-js pull request #794
Opened 2021-08-14 00:08 UTC by bogos

2021-08-16 17:54 UTC, cds95 requested changes

2021-08-16 17:54 UTC, cds95 commented on packages/sources/upvest/src/endpoint/gasprice.ts
> +interface ResponseSchema  {
Can we export this?

2021-08-17 09:32 UTC, bogos commented on packages/sources/upvest/src/endpoint/gasprice.ts
> +interface ResponseSchema  {
done!

2021-08-20 12:28 UTC, boxhock commented
@bogos Could you please rebase the PR and make sure the CI is still passing? Besides this it looks good

2021-08-24 05:42 UTC, closed without merging