Enable WS support for tiingo equities
smartcontractkit/external-adapters-js pull request #867
Opened 2021-08-31 22:01 UTC by cds95

This PR adds a new function property to WSHandler to filter out requests that should not be served using WS.  This is applied to the Tiingo adapter so that only requests to the IEX endpoint are served using WS.  I've intentionally left out tests for now and will add them to the PR once we feel good about how this is handled.

2021-08-31 22:02 UTC, cds95 commented on packages/sources/tiingo/src/config.ts
> -export const DEFAULT_WS_API_ENDPOINT = 'wss://api.tiingo.com/crypto'
We should extend our framework in the future to allow supporting multiple WS endpoints.  This should be ok for now as we want to disable WS for `crypto` anyways.

2021-09-02 12:14 UTC, boxhock requested changes

2021-09-02 12:14 UTC, boxhock commented on packages/sources/tiingo/src/adapter.ts
> +      shouldNotServeInputUsingWS: (input) => input.data.endpoint !== 'iex',
We should also accept any of the aliases for iex. In other words, any entry in this array: https://github.com/smartcontractkit/external-adapters-js/blob/4e34ac7a144de024dcc45a62acddbf5f5fd92826/packages/sources/tiingo/src/endpoint/iex.ts#L4

2021-09-02 18:17 UTC, boxhock approved these changes

2021-09-02 18:20 UTC, merged