WIP: Onchain gas EA POC
smartcontractkit/external-adapters-js pull request #918
Opened 2021-09-17 13:54 UTC by cds95

This PR implements a new adapter to fetch gas prices from on chain.  It does this by subscribing to the RPC's WS endpoint to listen to new heads and determines the gas price by taking the median gas price of it's transactions.

2021-09-17 20:35 UTC, cds95 commented
Missing integration and e2e tests as our current testing framework does not allow us to write tests for WS only adapters.  I've created a ticket for us to handle this in the future. https://app.shortcut.com/chainlinklabs/story/17228/implement-testing-framework-for-ws-only-adapters.  I think it should be ok to leave this out for now as the adapter is still a POC at this point.  Open to discussion on this though.

2021-09-17 20:46 UTC, cds95 commented on packages/core/types/@chainlink/index.d.ts
> +    toSaveFromFirstMessage?: (message: any) => any
I'm open to a better name for this.  This function is called if we ever need to save anything from the first message received from the WS endpoint.

2021-09-20 18:19 UTC, thodges-gh requested changes

2021-09-20 18:19 UTC, thodges-gh commented on packages/sources/onchain-gas/src/adapter.ts
> +        const medianGasPrices = await endpoints.gas.getTransactionsInPastBlocks(
One thing that we might want to account for is I know the node used to have an issue when the result contained an array. So we might want the response data to look like:
```json
{
    "data": {
        "values": [101768070829],
        "result": 101768070829
    },
    "result": 101768070829
}
```

This also means when there are multiple blocks queried, we'll want another param to specify which individual value we come to for the `result`.

2021-09-20 18:19 UTC, thodges-gh commented on packages/sources/onchain-gas/src/config.ts
> +export const NAME = 'ONCHAIN_GAS' // This should be filled in with a name corresponding to the data provider using UPPERCASE and _underscores_.
:scissors: comment

2021-09-20 18:19 UTC, thodges-gh commented on packages/sources/onchain-gas/src/endpoint/gas.ts
> +// This should be filled in with a lowercase name corresponding to the API endpoint
:scissors: comment

2021-09-21 18:13 UTC, thodges-gh requested changes
Just one thing to correct.

2021-09-21 18:13 UTC, thodges-gh commented on packages/sources/onchain-gas/README.md
> +|           | `blockIdx`  | The index of the block used for the result field in the response |         |      1      |
```suggestion
|           | `blockIdx`  | The index of the block used for the result field in the response |         |      0      |
```

2021-09-21 19:05 UTC, thodges-gh approved these changes

2021-09-21 19:12 UTC, merged